### ISSUE TITLE
Plane is off-center

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2763] opened 2018-01-23 01:20 UTC
Can't tell if this is an error in the icon or the export feature, but I can't seem to center the `plane` icon in a circle.

![plane](https://user-images.githubusercontent.com/18021678/35253094-a36e6dae-ffb1-11e7-95ef-981cfe633f8a.png)

**Comment by Templarian** [comment] 2018-01-23 01:25
[![plane](https://materialdesignicons.com/icon/airplane)](https://materialdesignicons.com/icon/airplane)

Yea, the icon is off center to the left by design (for some reason).

**Comment by MrGrigri** [comment] 2018-01-26 20:31
I thought that it could be something with the `airplane-off` needing some extra room for the slash...but it doesn't look like that's the case. The slash is centered with the plane and not the bounding box. It might be that they want the points to ly on the whole axis and not the half; makes the raster image better.

![airplane-off](https://materialdesignicons.com/icon/airplane-off)

![image](https://user-images.githubusercontent.com/4528551/35459401-3cdc0dbe-029d-11e8-94c2-e2750ba894af.png)

**Comment by Templarian** [comment] 2018-01-26 20:33
I think we'll just have to deal with this one being off center. You could rotate it 45deg to get around this I believe (then optionally shift down 0.5 pixels).

Closing out this issue as we're not going to make it thicker or off the grid.

**Closed by Templarian** 2018-01-26 20:33 UTC
Labels: Question
