### ISSUE TITLE
Magento

### ISSUE THREAD

**Issue by IgnaciodeNuevo** [Templarian/MaterialDesign#788] opened 2015-11-01 22:54 UTC
Design some CMS logos, as there is one for Worpress, make some others like Joomla, Prestashop, Magento etc

![joomla-logo](https://cloud.githubusercontent.com/assets/10051329/10871865/eaf38310-80f3-11e5-80b6-d62eaab3ac7d.png)
![magento-logo](https://cloud.githubusercontent.com/assets/10051329/10871866/eaf5b342-80f3-11e5-9898-5880ec021dea.png)
![prestashop-logo](https://cloud.githubusercontent.com/assets/10051329/10871867/eaf9603c-80f3-11e5-97dd-11fb3e4e074a.jpg)

**Comment by CoDEmanX** [comment] 2015-11-02 00:22
Partially a duplicate of #546

**Comment by PeterShaggyNoble** [comment] 2018-03-01 15:58
Joomla, as mentioned, is being tracked in #546. Prestashop is probably going to be too niche. Leaving this open (for now) as a request for Magento.

**Comment by goyney** [comment] 2019-05-23 13:10
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Closed by goyney** 2019-05-23 13:10 UTC
Labels: Brand Icon :bookmark:, Icon Request :pencil2:
