### ISSUE TITLE
Add Google Allo & Duo icons

### ISSUE THREAD

**Issue by mistermantas** [Templarian/MaterialDesign#2277] opened 2017-07-24 18:49 UTC
I like the Whicons implementation.

![](http://i.imgur.com/nxEMDmo.png)

**Comment by k5cents** [comment] 2017-07-24 19:48
I know it's not exactly the same, but I've been using `message-plus` and `message-video` in [my app drawer](http://i.imgur.com/3A6tJgr.png). I second the addition of real icons though.

Although I think just the Allo "A" shape (as seen in [Allo notifications](https://www.androidcentral.com/sites/androidcentral.com/files/styles/xlarge_wm_brw/public/article_images/2017/01/allo-notification-reply.jpg?itok=0uW-QdUj)) and the `camcorder` (which, by the way, is a duplicate of `video`, not an alias) icons might work better. Maybe a version with and without their containers?

**Comment by mistermantas** [comment] 2017-07-24 20:32
> I know it's not exactly the same, but I've been using message-plus and message-video in my app drawer . I second the addition of real icons though.

It seems odd for a project like this not to have a Google logo, that's the thing. Also the allo is great as an alternative "comment" or "new message" icon.

And, is that really your drawer with this project's icons? You fancied up the screenshots, too?

> Although I think just the Allo "A" shape (as seen in Allo notifications ) and the camcorder (which, by the way, is a duplicate of video , not an alias) icons might work better. Maybe a version with and without their containers?

Perfect opportunity to open an issue for the duplicate and have versions with and without their containers! ☺️

**Comment by MrGrigri** [comment] 2017-07-25 00:00
Just because it's a Google logo, doesn't mean that it follows the MD guidelines; although this one does. With that being said, those are 'product icons' and not 'system icons'. You can read more [here](https://material.io/guidelines/style/icons.html#icons-product-icons) and [here](https://material.io/guidelines/style/icons.html#icons-system-icons).

**Comment by mistermantas** [comment] 2017-07-25 08:14
> Just because it’s a Google logo, doesn’t mean that it follows the MD guidelines

I never said that, I just think that one of the largest companies in the world that also gave light to this project should be given first-class treatment or something like that.

**Comment by MrGrigri** [comment] 2017-07-25 14:33
Don't get me wrong. I'm not about them not getting added. The point I was attempting to make is that the product icons are created at a 192 x 192 grid, giving them more flexibility for detail. So when we shrink them down to 24 x 24, more than likely they will not meet the MD guidelines.

**Comment by MrGrigri** [comment] 2017-07-25 15:12
# Google Duo

![google-duo](https://user-images.githubusercontent.com/4528551/28579187-21e635b8-7119-11e7-900a-790eeab69093.png)

[google - duo.zip](https://github.com/Templarian/MaterialDesign/files/1173828/google.-.duo.zip)

# Google Allo

![google-allo](https://user-images.githubusercontent.com/4528551/28579243-4d76a3a2-7119-11e7-9b46-2b57768b207f.png)

[google - allo.zip](https://github.com/Templarian/MaterialDesign/files/1173831/google.-.allo.zip)

**Comment by k5cents** [comment] 2017-07-25 15:26
Those don't look half bad; maybe a little iffy at the 24x24 size. They look like [the icon Google uses](https://www.androidcentral.com/sites/androidcentral.com/files/styles/larger_wm_brw/public/article_images/2017/07/allo-duo-calls.jpg?itok=VhxTzABf) in the Allo app to have you make an Duo call. 

Do you have a version of Allo without the container?

**Comment by MrGrigri** [comment] 2017-07-25 15:40
Yeah, these are product icons, as such, they have to be treated as a logo. So I don't believe that changing their logo to fit the needs of MD is not right. That's why Allo uses the Duo logo the way they do and not just a video icon. Would the Allo icon be better visually if it were just the rounded chat bubble, probably? But that's not the point.

**Comment by k5cents** [comment] 2017-07-25 15:54
Yeah, but Google uses just the "rounded chat bubble" as the notification icon (without the container), [as seen here](https://www.androidcentral.com/sites/androidcentral.com/files/styles/xlarge_wm_brw/public/article_images/2017/01/allo-notification-reply.jpg?itok=0uW-QdUj). Just another example of Google's infamous inconsistency, I suppose. I personally think the "rounded chat bubble" is unique enough to work outside the container, whereas Duo's camera looks just like every over `video` icon used throughout Android, so it might not work on its own.

**Comment by MrGrigri** [comment] 2017-07-25 16:13
@Templarian, what are your thoughts on the matter?

**Comment by MrGrigri** [comment] 2017-07-25 16:21
# Google Allo Variant

![google-allo-variant](https://user-images.githubusercontent.com/4528551/28582517-e53cd50e-7122-11e7-9c47-b0b29a656e35.png)

[google - allo.zip](https://github.com/Templarian/MaterialDesign/files/1174065/google.-.allo.zip)

**Comment by mistermantas** [comment] 2017-07-25 19:14
Everything looks fine to me.

This variant would look nice as just any/random/unaffiliated bubble, like for messages, but I think I said that earlier. Think I saw it used like that on Ars Technica for the comment button (desktop only).

**Comment by Templarian** [comment] 2017-11-16 05:48
[![allo](https://materialdesignicons.com/icon/allo)](https://materialdesignicons.com/icon/allo)

**Closed by Templarian** 2017-11-16 05:48 UTC
Labels: Brand Icon, Contribution, Icon Request
