### ISSUE TITLE
Icons for keyboard keys

### ISSUE THREAD

**Issue by grafanauser** [Templarian/MaterialDesign#4627] opened 2019-11-22 08:45 UTC
Icon request
---
It would be nice to have icons for all keyboard keys (F1, CTRL, ESC, RETURN, ENTER, SHIFT, TAB, 0, 1, a, b ....).

Usage
---
Those can be used to display Hotkeys/Shortcuts to a user like "press F1 to open Help". F1 would be replaced by the key icon.

Appearance
---
I am not sure. Maybe some Square with rounded corners and the key name inside? 
Outlined version: square has a black border and the keyname text inside is black. rest ist transparent
Not outlined version: square is filled with color. the keyname text inside is transparent.
similiar to those arrows
![grafik](https://user-images.githubusercontent.com/47564534/69411204-ca1eb480-0d0c-11ea-9cdf-d6cb3fb3b2a0.png)

**Comment by JapanYoshi** [comment] 2019-11-22 13:32
Duplicate of request #1348 which was rejected.

**Comment by Templarian** [comment] 2019-11-23 00:24
The F1-F12 might be useful to have for hot keys. Might be useful to have these all just need designs that work.

![image](https://user-images.githubusercontent.com/338885/69469207-37563800-0d55-11ea-8d11-9cf94478adab.png)
![image](https://user-images.githubusercontent.com/338885/69469180-11c92e80-0d55-11ea-81ac-3711fce08f8f.png)
![image](https://user-images.githubusercontent.com/338885/69469132-daf31880-0d54-11ea-81c8-c2d08bb3164a.png)

**Comment by St-Ex** [comment] 2019-11-26 07:53
There is another solution to your problem : the [**kbd** html tag](https://developer.mozilla.org/fr/docs/Web/HTML/Element/kbd)

Exemple :

```html
<span>Presll <kbd>Ctrl</kbd> + <kbd>F1</kbd> + <kbd>E</kbd></span>
```
Which render as
<span>Presll <kbd>Ctrl</kbd> + <kbd>F1</kbd> + <kbd>E</kbd></span>

**Comment by Templarian** [comment] 2019-11-28 05:42
Added F1-F12 and ESC.

**Comment by goyney** [comment] 2019-12-03 03:12
I think we covered what we wanted to add here. Closing.

**Closed by goyney** 2019-12-03 03:12 UTC
Labels: Icon Request
