### ISSUE TITLE
Wide ticket barrier icon

### ISSUE THREAD

**Issue by macaronlover** [Templarian/MaterialDesign#5500] opened 2020-09-20 22:44 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Examples

https://2.bp.blogspot.com/-PLrsqCDhZVs/UfM60m5NduI/AAAAAAAABYs/qb74TbEMG-A/s1600/Wide+Ticket+Entrance+London.jpg

**Comment by goyney** [comment] 2020-09-21 13:17
Duplicate of #5501. Please keep icon variants in one request.

**Closed by goyney** 2020-09-21 13:17 UTC
Labels: Icon Request
