### ISSUE TITLE
a sailboat! (yes i saw ferry, its just not the same!)

### ISSUE THREAD

**Issue by gregcostanzo** [Templarian/MaterialDesign#3919] opened 2019-02-18 17:40 UTC
Sailboat
![image](https://user-images.githubusercontent.com/21691237/52968130-4e0cd000-337a-11e9-9730-22b4dd9700d6.png)

**Comment by PeterShaggyNoble** [comment] 2019-02-18 17:41
Duplicate of #2365

**Closed by PeterShaggyNoble** 2019-02-18 17:41 UTC
