### ISSUE TITLE
Letter Icons

### ISSUE THREAD

**Issue by DaveHenning** [Templarian/MaterialDesign#1656] opened 2016-11-27 20:50 UTC
Sometimes there just isn't a good icon to use for a situation. I tend to just fall back to a letter in those cases. That way all icons can match style. I guess numbers would be helpful too.

**Comment by Templarian** [comment] 2016-11-28 04:06
There is an open issue for this and plans to have this in the future. Marking as duplicate of #911.

We do have numeric icons though for 0-10 in a few variations.

**Closed by Templarian** 2016-11-28 04:06 UTC
