### ISSUE TITLE
Shutter Mid icon

### ISSUE THREAD

**Issue by kiloupi** [Templarian/MaterialDesign#7152] opened 2023-07-03 07:38 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Add Shutter Mid icon

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/795821/c3b94817-c008-4b2a-a3d7-43671fdacc50)

### Upload the icon source.

![window-shutter-mid](https://github.com/Templarian/MaterialDesign/assets/795821/d73e8143-1d33-4e73-953b-a65b45b69e00)

**Comment by mririgoyen** [comment] 2023-07-05 14:24
Please search (as you stated you had).

Duplicate of https://github.com/Templarian/MaterialDesign/issues/5733, https://github.com/Templarian/MaterialDesign/issues/5872, https://github.com/Templarian/MaterialDesign/issues/6277, https://github.com/Templarian/MaterialDesign/issues/6740, https://github.com/Templarian/MaterialDesign/issues/6754, https://github.com/Templarian/MaterialDesign/issues/7129.

**Closed by mririgoyen** 2023-07-05 14:24 UTC
Labels: Icon Request, Contribution
