### ISSUE TITLE
Icon request: Project

### ISSUE THREAD

**Issue by dontbyte** [Templarian/MaterialDesign#1971] opened 2017-03-29 05:17 UTC
Maybe something like 
![image](https://cloud.githubusercontent.com/assets/25500244/24439614/9ecfafea-144f-11e7-8e30-37923d4a8aa7.png)
![image](https://cloud.githubusercontent.com/assets/25500244/24439602/9295a7de-144f-11e7-8f61-56e68846e07b.png)

What do you think? Any other ideas?

**Comment by Chan4077** [comment] 2017-03-29 05:48
Duplicate of #1605.

**Comment by PeterShaggyNoble** [comment] 2017-03-29 13:16
Closing here in favour of #1605.

**Closed by PeterShaggyNoble** 2017-03-29 13:16 UTC
