### ISSUE TITLE
issue Accusoft, request for solarpanels icon

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#2887] opened 2018-03-07 15:56 UTC
HI,

was looking for a nice SolarPanels icon but couldn't find a dedicated one, either for flat roof or tiled roof on te house.

mdi:accusoft icon came close, but somehow it wont load. Anything wrong with it? Now using mdi:azure instead ;-)

Also, please consider creating dedicated SolarPanels?

Cheers,
Marius

**Comment by PeterShaggyNoble** [comment] 2018-03-07 16:00
`solar-panel` is a duplicate of #1672.

`accusoft` and `azure` are brand icons which we don't recommend using for any other purposes than representing those brands. Having said that, `accusoft` was added in the latest release published last weekend, so please check that the version you are using is up to date.

**Closed by PeterShaggyNoble** 2018-03-07 16:00 UTC

**Comment by goyney** [comment] 2018-03-08 15:07
I had to chime in here because I find this awesome.

@hvbhome I work for Accusoft and we're a green company with solar panels all over our headquarters building, but we never even thought that our logo kinda looks like a solar panel.

**Comment by hvbhome** [comment] 2018-03-08 16:34
Now only have to get it to show ;-)
