### ISSUE TITLE
living room icon

### ISSUE THREAD

**Issue by yakov-cohen** [Templarian/MaterialDesign#6025] opened 2021-06-14 11:11 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment] 2021-06-20 19:27
@yakov-cohen The template is not optional. Can you please include example images, so we have an idea of what this icon needs to represent.

**Comment by yakov-cohen** [comment] 2021-06-20 19:50
![living-room-icon-png-3](https://user-images.githubusercontent.com/78301655/122686482-e4d34b00-d219-11eb-8d60-41f3bce1441e.jpg)

**Comment by yakov-cohen** [comment] 2021-06-20 19:51
![living-room-icon-png-21](https://user-images.githubusercontent.com/78301655/122686515-10563580-d21a-11eb-81ab-86117fdd6af6.jpg)

**Comment by goyney** [comment] 2021-07-06 14:19
Duplicate of #4293.

**Closed by goyney** 2021-07-06 14:19 UTC
Labels: Icon Request, Needs More Info
