### ISSUE TITLE
Customer service icon

### ISSUE THREAD

**Issue by chuanyinglily** [Templarian/MaterialDesign#3035] opened 2018-04-10 02:52 UTC
![sideicon2](https://user-images.githubusercontent.com/38234899/38533703-1bd10f1c-3cad-11e8-9c8a-31c03a137e21.png)

this icon usually used in webpage , very useful ,so you can take my advice .thanks.

**Comment by PeterShaggyNoble** [comment] 2018-04-10 08:08
Duplicate of #2474.

**Closed by PeterShaggyNoble** 2018-04-10 08:08 UTC
