### ISSUE TITLE
Google Home App Icon

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2097] opened 2017-05-19 18:07 UTC
A monotone version of the new Google Home icon (the app that replaced Google Cast).

![homeappicon](https://cloud.githubusercontent.com/assets/18021678/26260763/74360372-3c9c-11e7-8d55-3bcf9fbc039c.png)
Something like this:

![home](https://cloud.githubusercontent.com/assets/18021678/26260731/4effd5c4-3c9c-11e7-8c34-33e56e2f70c5.png)

**Comment by Templarian** [comment] 2017-05-19 18:23
Duplicate of #1811

**Closed by Templarian** 2017-05-19 18:23 UTC
