### ISSUE TITLE
Fan Speed 4

### ISSUE THREAD

**Issue by atflack** [Templarian/MaterialDesign#7206] opened 2023-08-09 23:10 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Many fans go between 0% and 100% in jumps of 25%. I would use this icon in conjunction with the fan-speed-1 through fan-speed-3 to reflect the jumps accurately in an icon template.

### Give us an example of what this icon might look like.

https://pictogrammers.com/library/mdi/icon/fan-speed-1/

...but instead of a 1 it's a 4.

**Comment by mririgoyen** [comment] 2023-08-10 00:00
Duplicate of #7200, #6987, #6780, #6832, #6833... Please search.

**Closed by mririgoyen** 2023-08-10 00:00 UTC
Labels: Icon Request
