### ISSUE TITLE
Invoice icon

### ISSUE THREAD

**Issue by IYASSDEV** [Templarian/MaterialDesign#3038] opened 2018-04-11 00:32 UTC
Something like that:

![image](https://user-images.githubusercontent.com/32555430/38590295-2a148f88-3d28-11e8-9b71-2ea6a382dd71.png)

Thanks.

**Comment by Templarian** [comment] 2018-04-11 00:40
Duplicate of #1010

Please use the search.

**Closed by Templarian** 2018-04-11 00:40 UTC
