### ISSUE TITLE
Apple's share icon

### ISSUE THREAD

**Issue by brilliantmojo** [Templarian/MaterialDesign#4728] opened 2020-01-10 18:07 UTC
Is there any way we can get the iconic Apple Share icon? [The box with an arrow jumping up](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/). 

![sf-symbols-scales-weights_2x](https://user-images.githubusercontent.com/7403271/72175359-0041f180-33aa-11ea-9195-ff97b3b62435.png)

**Comment by PeterShaggyNoble** [comment] 2020-01-10 18:14
Duplicate of #3574

**Closed by PeterShaggyNoble** 2020-01-10 18:14 UTC
