### ISSUE TITLE
Water Tank

### ISSUE THREAD

**Issue by simonjowett** [Templarian/MaterialDesign#5456] opened 2020-08-28 02:09 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by simonjowett** [comment] 2020-08-28 02:12
I have rainwater tanks which are used on my remote property as the water supply for the whole house.  I have a level sensor attached to the tank and this is feeding information to Homeassistant.  Icon should look like a water tank!

**Comment by Xenomorph99** [comment] 2020-08-28 15:25
Would you need a cross section showing levels such as low, medium, high similar to [hydraulic-oil-level](https://materialdesignicons.com/icon/hydraulic-oil-level)? Water tanks come in many shapes and sizes. Some more information would be helpful.

![image](https://user-images.githubusercontent.com/1837101/91584660-323f9e00-e910-11ea-96f5-0f9320f8e1b4.png)

**Comment by simonjowett** [comment] 2020-08-29 12:37
Thanks for replying - a fairly simple outline similar to the 1st icon with a wavy line for the water.  I'm not expecting the icon to display the level in the tank, a displayed value will do that.  Most water tanks here are ground mounted, circular (about 3-4metres diameter is typical) and 2-3metres tall.  Outlet is at the bottom.

**Comment by MrGrigri** [comment] 2020-08-31 01:58
Will `tower-fire` not suffice?

**Comment by AtomicLaser** [comment] 2020-09-18 10:53
I would second this, something similar to the mdi-hydraulic-oil-level with a wavy line to indicate water would be suffice for me, and an additional one with an explanation mark

> Thanks for replying - a fairly simple outline similar to the 1st icon with a wavy line for the water. I'm not expecting the icon to display the level in the tank, a displayed value will do that. Most water tanks here are ground mounted, circular (about 3-4metres diameter is typical) and 2-3metres tall. Outlet is at the bottom.

**Comment by goyney** [comment] 2021-09-01 19:32
Duplicate of #2866.

Follow #5662 for this icon's addition.

**Closed by goyney** 2021-09-01 19:32 UTC
Labels: Icon Request
