### ISSUE TITLE
Content-codes changed between versions

### ISSUE THREAD

**Issue by tonvanalebeek** [Templarian/MaterialDesign#746] opened 2015-10-12 09:34 UTC
I sometimes set the icons in my stylesheet using the content-codes e.g. 
```
font-family: 'MaterialDesignIcons';
content: "\f437";
```

I tried to update to the latest version today (I'm using 1.1.70 right now), but saw that all my icons changed to other icons because of the content-codes that changed. Is this really necessary? Makes updating quite hard I think.

**Comment by REJack** [comment] 2015-10-12 09:40
idk but i would say the changes of the content-codes does the grunt webfont builder. it creates the whole font files and css.

**Comment by CoDEmanX** [comment] 2015-10-12 12:05
Duplicate of #644.

**Closed by CoDEmanX** 2015-10-12 12:05 UTC
