### ISSUE TITLE
fan speed 4 and others

### ISSUE THREAD

**Issue by kubiksamek** [Templarian/MaterialDesign#6833] opened 2022-11-06 09:31 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In Home Assistant for fan speed. There are use cases where three fan speeds are not enough. It would be nice to have options 0 to 9.

```
fan-speed-0
fan-speed-1 # exists
fan-speed-2 # exists
fan-speed-3 # exists
fan-speed-4
fan-speed-5
fan-speed-6
fan-speed-7
fan-speed-8
fan-speed-9
```

Additionally, it would be nice to have options like `fan-speed-turbo` where there would be `T` instead of number. Or if it's possible, add the whole alphabet.

### Give us an example of what this icon might look like.

Like https://materialdesignicons.com/icon/fan-speed-1 but with different numbers/letters.

**Comment by mririgoyen** [comment] 2022-11-06 13:15
Dupe of #6780.

We're not interested in adding more fan variations. 1/2/3 was used to avoid language conflicts with H/M/L.

**Closed by mririgoyen** 2022-11-06 13:15 UTC
Labels: Icon Request
