### ISSUE TITLE
User terms, Legal paper, Agreement

### ISSUE THREAD

**Issue by AAronsson** [Templarian/MaterialDesign#3100] opened 2018-04-22 07:44 UTC
Could be the same but could also be some alternatives.

Suggestions 
Paper with lines and a check down to right
A clean paper with lines.
Paper with a pen and a signature at bottom. Could be hard to do in such a small resolution.

**Comment by PeterShaggyNoble** [comment] 2018-04-24 14:04
Possible duplicate of #2151?

**Comment by MrGrigri** [comment] 2018-11-08 18:46
Closing because the `Consider Closing` label was added more than 10 days ago.

**Closed by MrGrigri** 2018-11-08 18:46 UTC
Labels: Consider Closing :door:, Icon Request :pencil2:
