### ISSUE TITLE
water pump

### ISSUE THREAD

**Issue by ezequiellop** [Templarian/MaterialDesign#5615] opened 2020-11-03 12:24 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

![99444944-water-pump-icon-on-white-](https://user-images.githubusercontent.com/62359004/97984965-4c857480-1db6-11eb-8e3a-f379b296ec67.jpg)

**Comment by Templarian** [comment] 2020-11-04 04:39
Could you use `pump` for this? I think a side view might be difficult to convey at the small size.

**Comment by goyney** [comment] 2022-03-26 00:02
Dupe of #5296.

**Closed by goyney** 2022-03-26 00:02 UTC
Labels: Icon Request
