### ISSUE TITLE
Apple Share

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5377] opened 2020-07-28 17:25 UTC
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

![exploration](https://user-images.githubusercontent.com/1837101/88699005-06888880-d0c4-11ea-8852-31b6ba447b44.png)

Here's a material version of the Apple iOS share icon. It's similar to [exit-to-app](https://materialdesignicons.com/icon/exit-to-app) except that I lined it up to the grid. The rectangle in options A and B felt a little too wide and D felt a little too narrow. I settled on C as the happy medium.

## Preview

![apple-share](https://user-images.githubusercontent.com/1837101/88698989-01c3d480-d0c4-11ea-9bda-fb87c04bf0d7.png)

## Zip Download

[apple-share.zip](https://github.com/Templarian/MaterialDesign/files/4989999/apple-share.zip)

**Comment by Templarian** [comment] 2020-07-28 18:13
Duplicate of #3574

**Closed by Templarian** 2020-07-28 18:13 UTC
Labels: Contribution, Icon Request
