### ISSUE TITLE
Steam iron for ironing clothes

### ISSUE THREAD

**Issue by irowan** [Templarian/MaterialDesign#5919] opened 2021-04-05 10:04 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

Icon for use in Home Assistant.

![iron-icon-vector-black-white-background-47088362](https://user-images.githubusercontent.com/36939297/113562745-f045ab80-9606-11eb-8ce6-10c81f37f20c.jpg)

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment] 2021-04-05 21:56
Duplicate of #2752.

**Closed by goyney** 2021-04-05 21:56 UTC
Labels: Icon Request
