### ISSUE TITLE
Tip: new icon

### ISSUE THREAD

**Issue by matheus-souza** [Templarian/MaterialDesign#1338] opened 2016-07-05 21:22 UTC
I'm in a project and realize it has no icon for User Groups (https://icons8.com/web-app/14804/user-groups) as does Floating Guru (https://icons8.com/web-app/15379/floating-guru) would be of great benefit to adding the same.

**Comment by JamesCoyle** [comment] 2016-07-06 00:07
I usually recommend using `account-multiple` when an icon showing several people is required. 
[![account-multiple](https://materialdesignicons.com/icon/account-multiple)](https://materialdesignicons.com/icon/account-multiple)

For reference this is the guru icon linked above. 
![guru](http://i.imgur.com/hDkyEoe.png)

**Comment by PeterShaggyNoble** [comment] 2018-03-01 15:55
As well as `account-multiple`, there's also now [`account-group`](https://materialdesignicons.com/icon/account-group). And the guru/meditation request is a duplicate of #176

**Closed by PeterShaggyNoble** 2018-03-01 15:55 UTC
Labels: Icon Request :pencil2:
