### ISSUE TITLE
currency-rupee(-generic)

### ISSUE THREAD

**Issue by niklas-e** [Templarian/MaterialDesign#5052] opened 2020-04-19 10:46 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There's many Rupee currencies, but this generic icon could be used for multiple ones as some of them have the same symbol. I'm mostly interested in Mauritian Rupee (MUR).

Icon aliases could be at least:
- currency-mur
- currency-pkr
- currency-npr

## Examples

Unicode: ₨

![image](https://user-images.githubusercontent.com/8472329/79685670-3281ab80-8243-11ea-8cab-7093d772db4e.png)

**Comment by goyney** [comment] 2020-04-19 13:32
Related to https://github.com/Templarian/MaterialDesign/issues/4030.

**Comment by Templarian** [comment] 2020-04-21 05:17
![image](https://user-images.githubusercontent.com/338885/79827960-49202380-8365-11ea-98f7-35c92b7b17ad.png)

But with a 2px consistent stroke. If anyone wants to give try that's the general size above.

**Comment by JapanYoshi** [comment] 2020-04-27 01:19
Redraw in Material font?

**Comment by Templarian** [comment] 2020-04-27 01:23
We don't use Roboto for the currency fonts. So this one needs to be redrawn with 2px width.

**Comment by JapanYoshi** [comment] 2020-05-18 03:08
![image](https://user-images.githubusercontent.com/8707990/82170728-a5e11080-9908-11ea-9ebc-47a7a4bb471b.png)
```
M 4 6 L 4 18 L 6 18 L 6 13 L 7.1171875 13 L 8.9375 18 L 11.064453 18 L 9.1601562 12.761719 C 9.1601562 12.761719 9.1621094 12.761719 9.1621094 12.761719 C 10.237189 12.303518 11 11.233757 11 10 L 11 9 C 11 7.3549904 9.6450096 6 8 6 L 4 6 z M 6 8 L 8 8 C 8.5641294 8 9 8.4358706 9 9 L 9 10 C 9 10.564129 8.5641291 11 8 11 L 6 11 L 6 8 z M 15.5 9 C 14.132297 9 13 10.132297 13 11.5 L 13 12 C 13 13.367703 14.132297 14.5 15.5 14.5 L 17.5 14.5 C 17.794297 14.5 18 14.705703 18 15 L 18 15.5 C 18 15.794297 17.794297 16 17.5 16 L 13 16 L 13 18 L 17.5 18 C 18.867703 18 20 16.867703 20 15.5 L 20 15 C 20 13.632297 18.867703 12.5 17.5 12.5 L 15.5 12.5 C 15.205703 12.5 15 12.294297 15 12 L 15 11.5 C 15 11.205703 15.205703 11 15.5 11 L 20 11 L 20 9 L 15.5 9 z
```

**Comment by Templarian** [comment] 2020-05-18 03:23
@JapanYoshi Too Material, we still want to keep the look/connected `Rs` design at 2dp.

**Comment by goyney** [comment] 2021-09-21 19:06
Yeah this is an absolute duplicate of #4030.

**Closed by goyney** 2021-09-21 19:06 UTC
Labels: Icon Request
