### ISSUE TITLE
window-shutter-partly-open

### ISSUE THREAD

**Issue by Pirol62** [Templarian/MaterialDesign#6740] opened 2022-08-09 11:42 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To display a shutter which is only partly closed/open

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/48820003/183638676-012af4a0-edfc-46f2-a8c5-75caae4bfeb0.png)

**Comment by mririgoyen** [comment] 2022-08-09 13:03
Duplicate of #5733.

**Closed by mririgoyen** 2022-08-09 13:03 UTC
Labels: Icon Request
