### ISSUE TITLE
Pet Door Icons

### ISSUE THREAD

**Issue by PeteCooney** [Templarian/MaterialDesign#6813] opened 2022-10-20 11:24 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Pet door (eg; cat flap) icons would be really helpful when working with these types of devices in Home Assistant.

### Give us an example of what this icon might look like.

https://github.com/elax46/custom-brand-icons has a couple of great examples (I believe original credit goes to [@rchiileea](https://github.com/rchiileea) for these)...

Pet Flap: Open - ![img](https://raw.githubusercontent.com/elax46/custom-brand-icons/dev/icon-svg/petflap-open.svg)
Pet Flap: Closed - ![img](https://raw.githubusercontent.com/elax46/custom-brand-icons/dev/icon-svg/petflap-closed.svg)

**Comment by mririgoyen** [comment] 2022-10-20 13:40
Duplicate of #6330.

**Closed by mririgoyen** 2022-10-20 13:40 UTC
Labels: Icon Request
