### ISSUE TITLE
need some icons

### ISSUE THREAD

**Issue by rohamishop** [Templarian/MaterialDesign#6119] opened 2021-08-16 14:34 UTC
Excuse me sir
I'm not a Developer. I can just search icons in template that you created on **"material design icon site"**  and I need **meat grinder, steam Iron, bowl blender, hand blender ,....**
 How can I find there?
 would please show me a sample to find or create ? 
or would you please add them so I use it in my word press site.
Thank you so much

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment] 2021-08-16 14:39
Duplicate of #6118.

**Closed by goyney** 2021-08-16 14:39 UTC
Labels: Icon Request
