### ISSUE TITLE
Corridor/Alleyway icon

### ISSUE THREAD

**Issue by Murder3D** [Templarian/MaterialDesign#5891] opened 2021-03-14 16:44 UTC
Hi,

could someone please add a corridor/alleyway icon?

I am building a dashboard on HA with lights / group of lights mapped to different rooms, and a corridor/alleyway it's all I am missing to finish it.

Here are some examples:
![3310023-200](https://user-images.githubusercontent.com/68924586/111076521-e2f83e00-84ec-11eb-95fc-65f2747bba88.png)
![hallway-icon-17](https://user-images.githubusercontent.com/68924586/111076523-e2f83e00-84ec-11eb-9a0e-52c8d9cf9874.jpg)

Thank you!

**Comment by goyney** [comment] 2021-08-30 21:34
Duplicate of #5344.

**Closed by goyney** 2021-08-30 21:34 UTC
Labels: Icon Request
