### ISSUE TITLE
Please add mdi-flicker and mdi-flicker-box 

### ISSUE THREAD

**Issue by mrhieu** [Templarian/MaterialDesign#2205] opened 2017-06-26 13:56 UTC
We're missing icons for one of the most popular social networks Flicker (https://www.flickr.com/). Can anyone add them? Thanks

**Comment by GreenTurtwig** [comment] 2017-06-26 14:12
Duplicate of #409 
We really should have this by now.

**Closed by GreenTurtwig** 2017-06-26 14:12 UTC
Labels: Duplicate
