### ISSUE TITLE
Puppy/Dog Icon

### ISSUE THREAD

**Issue by eddieberklee** [Templarian/MaterialDesign#1278] opened 2016-06-09 20:36 UTC
There's a cat one, I'm just asking for animal equality y'all.

Something like 🐶 ?

**Comment by Templarian** [comment] 2016-06-10 03:17
It's been suggested a ton of times in the past... no one has designed one yet. Weird.

Duplicate of #736 (now marked as a high priority icon).

**Closed** 2016-06-10 03:24 UTC
Labels: Duplicate
