### ISSUE TITLE
Add Leaderboard, Podium and Medals with Position 1, 2 and 3

### ISSUE THREAD

**Issue by husenmemon** [Templarian/MaterialDesign#3656] opened 2018-10-23 14:37 UTC
Please add icons for Leaderboard, Podiums with Position, Medals with Positions and Level i.e., Gold, Silver and Bronze.

**Comment by Templarian** [comment] 2018-10-23 15:54
Duplicate of #979 (sort of)

Not sure how we could represent gold/silver/bronze. Any ideas/examples?

**Comment by MrGrigri** [comment] 2018-10-24 15:34
I was thinking something like this. It is a little on the larger size because of the starts and their minimal recognizable size...but I think it works.

![image](https://user-images.githubusercontent.com/4528551/47442500-aab30200-d76f-11e8-9d25-c8cf65241584.png) ![image](https://user-images.githubusercontent.com/4528551/47442538-b999b480-d76f-11e8-9715-495e9ef17c09.png) ![image](https://user-images.githubusercontent.com/4528551/47442568-cd451b00-d76f-11e8-91e9-d0d151d91530.png) ![image](https://user-images.githubusercontent.com/4528551/47442628-ddf59100-d76f-11e8-8667-5eeb3a6839e1.png)

[podium.zip](https://github.com/Templarian/MaterialDesign/files/2511188/podium.zip)

**Comment by husenmemon** [comment] 2018-10-24 17:43
Gold, Silver and Bronze can be represented by Color or Position. Check the example:
![gold silver bronze](https://user-images.githubusercontent.com/28763246/47450253-61e86100-d7e2-11e8-8b9f-92af1e760bfb.png)

**Comment by MrGrigri** [comment] 2018-10-24 17:47
This could be handled with `numeric-*circle`. I know that it's discussed in another issue somewhere, just cannot remember where.

**Comment by husenmemon** [comment] 2018-10-29 14:12
Any update?

**Comment by MrGrigri** [comment] 2018-11-20 18:39
@husenmemon, it has been added to the `3.1.xx` milestone and will be added then.

**Comment by Templarian** [comment] 2018-12-22 04:53
[![podium](https://materialdesignicons.com/icon/podium)](https://materialdesignicons.com/icon/podium) [![podium-bronze](https://materialdesignicons.com/icon/podium-bronze)](https://materialdesignicons.com/icon/podium-bronze) [![podium-silver](https://materialdesignicons.com/icon/podium-silver)](https://materialdesignicons.com/icon/podium-silver) [![podium-gold](https://materialdesignicons.com/icon/podium-gold)](https://materialdesignicons.com/icon/podium-gold)

**Closed by Templarian** 2018-12-22 04:53 UTC
Labels: Contribution :heavy_check_mark:, Icon Request :pencil2:
