### ISSUE TITLE
Icon Request: Discordapp.com

### ISSUE THREAD

**Issue by Adryd** [Templarian/MaterialDesign#1166] opened 2016-04-13 14:07 UTC
Could someone make an icon for discordapp.com?

**Comment by Templarian** [comment] 2016-04-13 15:21
Duplicate of #944.

**Closed by Templarian** 2016-04-13 15:21 UTC
Labels: Duplicate

**Comment by Templarian** [comment] 2016-05-14 19:33
[![discord](https://materialdesignicons.com/icon/discord)](https://materialdesignicons.com/icon/discord)
