### ISSUE TITLE
atmospheric pressure

### ISSUE THREAD

**Issue by casey-zebrowski** [Templarian/MaterialDesign#5157] opened 2020-05-14 18:43 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

BAROMETRIC PRESSURE / ATMOSPHERIC PRESSURE

## Examples

https://www.google.com/search?q=barometric+pressure+icon&rlz=1C1CHBF_enUS840US840&sxsrf=ALeKk03JAj6Nj71dZl9XNS4B63gsjRtPIA:1589481730838&tbm=isch&source=iu&ictx=1&fir=3tWVxp6zYWq1yM%253A%252CUNd_Y3h3xTeT9M%252C_&vet=1&usg=AI4_-kQOkGpXXK4myuBzLxWqG1ieaM7XWg&sa=X&ved=2ahUKEwjf0MXvgLTpAhWIUt8KHTmGCjEQ9QEwAHoECBsQGg#imgrc=3tWVxp6zYWq1yM:

**Comment by goyney** [comment] 2020-05-19 02:06
Related, if not duplicates #4567.

Would the `gauge` icons not work for this?

**Comment by casey-zebrowski** [comment] 2020-05-19 13:29
Not really. It is more of a pressure than a gauge, for example [Atmospheric Pressure Icon](https://www.visualpharm.com/free-icons/atmospheric%20pressure-595b40b85ba036ed117dbef9)
![Atmospheric Pressure](https://user-images.githubusercontent.com/530803/82332238-252b1e80-99b3-11ea-862a-252893195824.png)

**Comment by goyney** [comment] 2020-05-19 13:37
That's pretty abstract. There's gotta be a better way. 🤔

**Comment by goyney** [comment] 2020-09-09 02:57
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/4753.

**Closed by goyney** 2020-09-09 02:57 UTC
Labels: Icon Request
