### ISSUE TITLE
Windsock

### ISSUE THREAD

**Issue by ricardomartins** [Templarian/MaterialDesign#3585] opened 2018-10-10 17:06 UTC

**Comment by PeterShaggyNoble** [comment] 2018-10-10 17:08
Duplicate of #1921. See also #831.

**Closed by PeterShaggyNoble** 2018-10-10 17:08 UTC
Labels: Duplicate/Already Included :bookmark_tabs:

**Comment by ricardomartins** [comment] 2018-10-11 10:35
Just realised that searching for "wind" doesn't return "windsock" results. My apologies.

**Comment by PeterShaggyNoble** [comment] 2018-10-12 12:29
Yeah, that's an unfortunate limitation within GitHub; it only searches complete words.
