### ISSUE TITLE
The CDN is not setting the headers to cache in the browser

### ISSUE THREAD

**Issue by rzel** [Templarian/MaterialDesign#5167] opened 2020-05-19 03:36 UTC
If you embed via cdn.materialdesignicons.com, the CDN is not setting the headers to cache in the browser.

This is MASSIVELY increasing the load times, and using up bandwidth.

Can someone please do something about this by enabling caching with the CDN?

Thanks

**Comment by goyney** [comment] 2020-05-19 12:27
Duplicate of #5124. Please search.

**Closed** 2020-05-19 12:27 UTC
Labels: Duplicate
