### ISSUE TITLE
Ultraviolet Icon

### ISSUE THREAD

**Issue by Swamp-Ig** [Templarian/MaterialDesign#4060] opened 2019-03-19 23:49 UTC
An icon representing ultraviolet level would be useful.

There's a [free example here](http://chittagongit.com/icon/ultraviolet-icon-27.html).

**Comment by terreng** [comment] 2019-03-20 00:13
This issue already exists as #3347, though I created the icon anyway because the other issue seems to have taken up designing a uv sensor icon instead. Here I tried two different sizes for the lettering:

![image](https://user-images.githubusercontent.com/11605395/54649896-461f7900-4a69-11e9-85c0-1fccd1f7eee7.png)
[ultraviolet.svg](https://github.com/terreng/samples/blob/master/ultraviolet.svg)

![image](https://user-images.githubusercontent.com/11605395/54650061-e2e21680-4a69-11e9-8fd8-50548cc3d89a.png)
[ultraviolet-2.svg](https://github.com/terreng/samples/blob/master/ultraviolet-2.svg)

**Comment by Swamp-Ig** [comment] 2019-03-20 00:50
Wow looks great! I wonder if rounded off corners on the sun rays would look better?

**Comment by goyney** [comment] 2019-03-20 00:51
This is a duplicate of #3347.

**Closed by goyney** 2019-03-20 00:51 UTC
