### ISSUE TITLE
Table icons

### ISSUE THREAD

**Issue by mate-h** [Templarian/MaterialDesign#1292] opened 2016-06-16 23:13 UTC
I made some table icons (3, actually) since I haven't found any. They all align to the official material system icon guidelines. I thought maybe it would be great for the others to be available.

![table-icon-3](https://cloud.githubusercontent.com/assets/14351670/16136156/961c610c-3428-11e6-89c2-3a15219ba5fd.png)
![table-icon-1](https://cloud.githubusercontent.com/assets/14351670/16136157/961cd42a-3428-11e6-9de1-9174291354de.png)
![table-icon-2](https://cloud.githubusercontent.com/assets/14351670/16136158/9622dd16-3428-11e6-9857-68134d40aa68.png)

**Comment by CoDEmanX** [comment] 2016-06-27 10:10
They don't seem fully compliant to the specs:

> Shapes are bold and geometric (1st icon could be more minimalist)
> Don’t tilt, rotate, or make icons appear dimensional (2nd icon)

The 3rd icon looks like a cake with legs hm...

**Comment by goyney** [comment] 2018-11-25 05:02
This is a duplicate of #624.

**Closed by goyney** 2018-11-25 05:02 UTC
Labels: Icon Request :pencil2:
