### ISSUE TITLE
WebMoney

### ISSUE THREAD

**Issue by Yanovsky** [Templarian/MaterialDesign#3178] opened 2018-05-15 13:44 UTC
Icons are required for web payment providers. Such as WebMoney, PayPal, KIWI, Yandex, Sendy Pay, AliPay

**Comment by PeterShaggyNoble** [comment] 2018-05-15 16:32
- `paypal` already exists
- `yandex` is a duplicate of #1405

The rest are probably too obscure for inclusion at this time.

**Comment by goyney** [comment] 2018-10-03 04:00
Going to close this issue. If there are specific pay providers you'd like to see added, please create a separate issue for each one. Thanks!

**Closed by goyney** 2018-10-03 04:00 UTC
Labels: Brand Icon :bookmark:, Consider Closing :door:, Icon Request :pencil2:
