### ISSUE TITLE
Network Attached Server (w/ multiple bays)

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [Templarian/MaterialDesign#2842] opened 2018-02-26 06:24 UTC
Icons for NAS do not seem to exist. It could be nice to have variations on this with 2 bays, 4 bays, 8 bays, 12 bays+.
I've included examples that I made for my home floorplan.

[NAS4&8BAYS.zip](https://github.com/Templarian/MaterialDesign/files/1757430/NAS4.8BAYS.zip)

**Comment by PeterShaggyNoble** [comment] 2018-02-26 12:50
This is a duplicate of #2842.

One or more of the generic [`server` icons](https://petershaggynoble.github.io/MDI-Sandbox/?filter=server) should definitely be fit for purpose here and I think multiple bay variations would be a bit too specific, not too mention too detailed, for inclusion.

**Closed by PeterShaggyNoble** 2018-02-26 12:50 UTC
