### ISSUE TITLE
Material Design Alphabet and Numeric Icons (on their own)

### ISSUE THREAD

**Issue by Mancerrss** [Templarian/MaterialDesign#3458] opened 2018-09-09 09:37 UTC
Hi. I hope someone here recreate all the Alphabet letters (maybe even some popular foreign or phonetic alphabet too like ñ, é, etc) on Material design Iconography aesthetics. Like on Filter_2, HD, PIN, HQ, NEW icons. In their own icons itself. In full scale in Material design Iconography grid. This would be helpful bc some might need it but also for us that makes icons too that'll need an Alphabet letter inside, were having a hard time remaking it from scratch, what sides to curve and how we'll construct the tails and other letter features, how to pixel compensate it when it's inevitable to go beyond the grid

Here's some examples
[examples.zip](https://github.com/Templarian/MaterialDesign/files/2364103/examples.zip)

I hope you'll do the 1 - 9 numeric as well too

**Comment by Templarian** [comment] 2018-09-09 17:36
Duplicate of #1299

**Closed by Templarian** 2018-09-09 17:36 UTC
