### ISSUE TITLE
Index for Air Quality (IAQ)

### ISSUE THREAD

**Issue by stefferber** [Templarian/MaterialDesign#5732] opened 2021-01-01 11:26 UTC
## Usage

Index for Air Quality (IAQ) is measured for human health [indoor](https://en.wikipedia.org/wiki/Indoor_air_quality) and [outside](https://en.wikipedia.org/wiki/Air_quality_index).

I found a  [IAQ visualization discussion](https://ux.stackexchange.com/questions/89555/how-to-visualize-air-quality-index-on-physical-widget-to-be-easily-recognized-by)

Typically, the measurement is displayed on a small device, smart phone, or computer display along with a number ranging from 0 to 500 or the air pollution level 0 to 10.

## Examples

I found some examples 

- [https://www.pngegg.com/en/png-sduyq](https://www.pngegg.com/en/png-sduyq)
- [https://www.cleanpng.com/png-air-computer-icons-astrology-symbol-classical-elem-733370/](https://www.cleanpng.com/png-air-computer-icons-astrology-symbol-classical-elem-733370/)
- [https://de.cleanpng.com/png-qx1phw/](https://de.cleanpng.com/png-qx1phw/)

 but I do not like them as they do not associate with good or bad air quality. I also believe it would be good to distinguish between inside air quality, associated with a house, and outside air quality, associated with weather symbols.

**Comment by goyney** [comment] 2021-01-08 20:25
Duplicate of #4204.

**Comment by goyney** [comment] 2021-01-08 20:26
Additionally, we have 2 of your examples, `air-filter` and `weather-windy`.

**Closed by goyney** 2021-01-08 20:25 UTC
Labels: Icon Request

**Comment by stefferber** [comment] 2021-01-09 09:08
Thx. @goyney for taking this up - really great community ;-) I will use the `air-filter` but I think there can be better designs. The `air-filter` is very well suited to depict devices cleaning air. It is good to link this up with [4204](https://github.com/Templarian/MaterialDesign/issues/4204) but be aware that IAQ is an index that is calculated based on sensor values like CO2, ppm, ...
