### ISSUE TITLE
attic window open and close Perspective version

### ISSUE THREAD

**Issue by rchiileea** [Templarian/MaterialDesign#6306] opened 2021-11-05 12:57 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

decided to make these after I saw I user request and thought I would convert image to icon, I hope the gaps works and are ok for submission 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/87599807/140513559-8a653014-9a0a-48cc-b852-87f4b014de86.png)
![image](https://user-images.githubusercontent.com/87599807/140513583-528d69db-8c69-438f-983d-e7b3b8eb1405.png)

### Upload the icon source.

[TiltWindowRoof.zip](https://github.com/Templarian/MaterialDesign/files/7486109/TiltWindowRoof.zip)

**Comment by goyney** [comment] 2021-11-05 13:06
Duplicate of #5923. This isn't possible due to perspective.

**Closed by goyney** 2021-11-05 13:06 UTC
Labels: Icon Request, Contribution

**Comment by rchiileea** [comment] 2021-11-05 13:08
I dont understand, could you explain as I am new to this, is perspective not allowed on material then?

**Comment by goyney** [comment] 2021-11-05 13:11
It's the fourth box you checked and agreed to when submitting your contribution under "Complex icon shapes."

> **Don't**
Don’t tilt, rotate, or make icons appear dimensional.

**Comment by rchiileea** [comment] 2021-11-05 13:14
ok cheers, I did not think it was complex due to nothing but straight lines :P Ok I get it a bit
