### ISSUE TITLE
Flickr Logo icon

### ISSUE THREAD

**Issue by SvenWesterlaken** [Templarian/MaterialDesign#2335] opened 2017-08-19 14:32 UTC
Still using this platform to upload some of my photo works so would be nice if I can use the icon for link buttons etc.

There are variants with a box and a circle surrounding it, but don't like those that much.

![flickr logo](http://icons.iconarchive.com/icons/uiconstock/socialmedia/512/Flickr-icon.png)

**Comment by k5cents** [comment] 2017-08-20 13:14
The problem lies in Material Design's lack of multicolored system icons. This icon would end up just being too mono-colored circles side by side. That might be enough to still identify it as Flikr, but I'm not sure.

**Comment by Templarian** [comment] 2017-08-21 00:03
Duplicate of #409

I do need to look into solving these shortly. PayPal/Flickr.

**Closed by Templarian** 2017-08-21 00:03 UTC
