### ISSUE TITLE
Bag, Grab Bag, Back Pack, Ruck Sack

### ISSUE THREAD

**Issue by rowex099** [Templarian/MaterialDesign#2905] opened 2018-03-13 20:54 UTC
No real bag centric iconography here. Would love some variety around a "bag" theme.

**Comment by Templarian** [comment] 2018-03-13 20:56
Paper grocery bag with handles **or** like a bag of gold aka sack design?

**Comment by PeterShaggyNoble** [comment] 2018-03-14 12:12
We have a couple of open issues for different types of bags including #338, #1136 and #2473. We also have one for a money bag that I can't seem to find at the moment.

**Comment by rowex099** [comment] 2018-03-14 15:49
I'm thinking more of a backpack. I was able to find a money bag but that's too specific. I'm looking for the generic idea of a bag you carry something around in. Backpack is pretty gender neutral, purses tend to not be but could still be useful.

**Comment by PeterShaggyNoble** [comment] 2018-03-14 15:58
Thanks for the clarification; this would be a duplicate of #1136, so.

**Closed by PeterShaggyNoble** 2018-03-14 15:58 UTC
Labels: Duplicate/Already Included :bookmark_tabs:
