### ISSUE TITLE
Error message during export

### ISSUE THREAD

**Issue by Neir0** [Templarian/MaterialDesign#2186] opened 2017-06-21 15:52 UTC
I'm getting following error when trying to export png icon from advanced view
Fatal error: Class 'Imagick' not found in /home/templarian/webapps/materialdesignicons/api/endpoints.php on line 1656

**Comment by MrGrigri** [comment] 2017-06-21 15:55
Duplicate of #2181

**Closed by MrGrigri** 2017-06-21 15:55 UTC
Labels: Duplicate
