### ISSUE TITLE
shoes icon

### ISSUE THREAD

**Issue by vosidiy** [Templarian/MaterialDesign#3355] opened 2018-07-31 08:35 UTC
need a male and lady shoe icon.

**Comment by MrGrigri** [comment] 2018-07-31 16:32
Could be a partial duplicate of #300.

**Comment by SarinManS** [comment] 2018-08-22 10:07
![image](https://user-images.githubusercontent.com/26505215/44457560-3bac1680-a623-11e8-925f-957ccf6d27d8.png)

![image](https://user-images.githubusercontent.com/26505215/44457578-4e265000-a623-11e8-9eb4-288376997135.png)

[Shoes-formal.zip](https://github.com/Templarian/MaterialDesign/files/2309841/Shoes-formal.zip)
[Shoes-heel.zip](https://github.com/Templarian/MaterialDesign/files/2309842/Shoes-heel.zip)

**Comment by MrGrigri** [comment] 2018-08-22 15:26
These are great...however, they are not 'material' at all.

**Comment by SarinManS** [comment] 2018-08-23 11:28
Something like this?
![image](https://user-images.githubusercontent.com/26505215/44522940-e2fa7d80-a6f7-11e8-8ec4-a7401d10f757.png)

**Comment by Templarian** [comment] 2018-09-02 04:45
@SarinManS Yea, that one works great. Can you zip the svg and attach it.

**Comment by SarinManS** [comment] 2018-09-02 10:02
This one got a little tricky.. i think it looks good when scaled down. But wierd at large
 
![image](https://user-images.githubusercontent.com/26505215/44954770-48ecbf00-aec7-11e8-925b-28e8616840ee.png)
[Shoes-heel.zip](https://github.com/Templarian/MaterialDesign/files/2343178/Shoes-heel.zip)

**Comment by Templarian** [comment] 2018-09-02 16:49
[![shoe-formal](https://materialdesignicons.com/icon/shoe-formal)](https://materialdesignicons.com/icon/shoe-formal) [![shoe-hell](https://materialdesignicons.com/icon/shoe-heel)](https://materialdesignicons.com/icon/shoe-heel)

**Closed by Templarian** 2018-09-02 16:49 UTC
Labels: Icon Request :pencil2:
