### ISSUE TITLE
 illuminance sensor icon

### ISSUE THREAD

**Issue by lpt2007** [Templarian/MaterialDesign#4549] opened 2019-10-26 14:48 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

It would be nice to have illuminance sensor icon like this:

![illuminance_sensor](https://user-images.githubusercontent.com/38924279/67621467-37275300-f810-11e9-8027-314c01001c58.png)

**Comment by MrGrigri** [comment] 2019-10-26 17:12
Might be a duplicate of #3347

**Comment by lpt2007** [comment] 2019-10-26 17:46
Ico

> Might be a duplicate of #3347

This is totally different icon. :)

**Comment by goyney** [comment] 2021-08-25 00:54
Definitely a duplicate of #3347. Both requests can be represented by a light source emitting something... In this case lumens, in the latter's case ultra-violet rays. Thought, I like the idea of the sun emitting the "wireless" signals better in this issue as opposed to the other. I'm going to keep this open for now, because I think I will work on adding this and then closing both issues out.

**Comment by goyney** [comment] 2021-08-25 15:38
![image](https://user-images.githubusercontent.com/1015040/130821115-16458637-a120-4386-a2a0-90d059053dcf.png)![image](https://user-images.githubusercontent.com/1015040/130821147-a206ed30-34ee-40a3-bc9e-34e9759e4fcf.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7048213/Archive.zip)

**Comment by goyney** [comment] 2021-08-30 03:16
Added.

**Closed by goyney** 2021-08-30 03:16 UTC
Labels: Icon Request, Contribution, Home Assistant
