### ISSUE TITLE
Advanced Export Icon Packgage Customize Problem

### ISSUE THREAD

**Issue by ulaserdegor** [Templarian/MaterialDesign#3890] opened 2019-02-06 10:42 UTC
Despite the customization with different colors, only white, black, gray colors are output for android

**Comment by PeterShaggyNoble** [comment] 2019-02-08 15:48
Duplicate of #718

I forgot to leave a comment on that issue when closing it but development on the current site has halted in favour of our new site, coming soon.

**Closed by PeterShaggyNoble** 2019-02-08 15:48 UTC
