### ISSUE TITLE
Pinterest & Flickr Icon

### ISSUE THREAD

**Issue by SvenWesterlaken** [Templarian/MaterialDesign#1877] opened 2017-02-18 16:08 UTC
Just saw this library and this is exactly what I need for my upcoming projects. The sweet balance between the formal material icon set and the diversity of font-awesome. 

Although there are a lot of icons already, I miss a few 'social media' platforms (that I use):
**Pinterest & Flickr**
_Guess you would know how the logo's look ;)_

Wanted to submit those by myself but seems the contributing part is currently disabled... so I'm here to ask for an outcome :)

**Comment by Templarian** [comment] 2017-02-18 16:16
Pinterest exists,
https://materialdesignicons/icon/pinterest
https://materialdesignicons/icon/pinterest-box

Flicker is a duplicate of #409.

**Closed by Templarian** 2017-02-18 16:16 UTC
