### ISSUE TITLE
NodeRED Icon

### ISSUE THREAD

**Issue by MiPiGamer** [Templarian/MaterialDesign#4081] opened 2019-03-30 00:58 UTC
I was wondering if there could be a Node-RED icon to use in places like Home Assistant? I was thinking removing the red and making the lines grey. I would do it myself but I have no Gimp skills.
![node-red-icon](https://user-images.githubusercontent.com/13185170/55268965-20625300-5265-11e9-9e98-af15c7f5e082.png)

**Comment by goyney** [comment] 2019-03-30 01:12
Duplicate of https://github.com/Templarian/MaterialDesign/issues/3170. Please make sure to search before posting new suggestions! 😄

**Closed by goyney** 2019-03-30 01:12 UTC
