### ISSUE TITLE
water-valve

### ISSUE THREAD

**Issue by redskinhu** [Templarian/MaterialDesign#3071] opened 2018-04-17 14:57 UTC
Hello

Is it possible to create tap and valve signs?

Something like this:
https://www.iconfinder.com/icons/1641990/bill_communal_faucet_payments_pipe_valve_water_icon#size=512

and these:
https://www.iconfinder.com/icons/1904513/compter_construction_crane_fuel_gas_oil_sensor_valve_icon#size=512
https://www.istockphoto.com/ie/vector/plumbing-valve-icon-gm874267278-244121535
https://iconscout.com/icon/pump-10

Thanks
T

**Comment by MrGrigri** [comment] 2018-04-17 16:29
FYI, we do have `water-pump`.

![water-pump](https://materialdesignicons.com/icon/water-pump)

**Comment by MrGrigri** [comment] 2018-04-17 16:31
This is also a possible duplicate of #1192

**Comment by redskinhu** [comment] 2018-05-03 21:08
Hi

LOL. I suggested valve and tap, not water pump and fire hydrant...
Yes are they similar like the match and sun (hot), are they wet. ;-)

Thx
T

**Comment by GreenTurtwig** [comment] 2018-05-03 21:16
@mrgrigri was stating that a tap is named `water-pump` in our set and a request for a valve icon was already open (alongside a fire hydrant).

**Comment by goyney** [comment] 2018-10-03 04:06
Refocused this issue for the inclusion of a water valve.

**Comment by goyney** [comment] 2021-09-02 00:38
[![pipe-valve](https://materialdesignicons.com/icon/pipe-valve)](https://materialdesignicons.com/icon/pipe-valve)

Sink or faucet is being tracked in #5137.

**Closed by goyney** 2021-09-02 00:38 UTC
Labels: Icon Request
