### ISSUE TITLE
Sports Icons (non American Football related)

### ISSUE THREAD

**Issue by pedroguedesamaral** [Templarian/MaterialDesign#1316] opened 2016-06-24 19:57 UTC
Icon request

**Comment by Templarian** [comment] 2016-06-24 20:01
@pedroguedesamaral We have a few like Australian football and a soccer ball. Are there more sports called football?

**Comment by pedroguedesamaral** [comment] 2016-06-24 20:06
@Templarian specifically i was looking for a basketball =)

**Comment by Templarian** [comment] 2016-06-24 20:08
:laughing:

(but a duplicate of #1057)

**Closed by Templarian** 2016-06-24 20:08 UTC
Labels: Needs More Information
