### ISSUE TITLE
Numerals icons

### ISSUE THREAD

**Issue by alexanderbaulin** [Templarian/MaterialDesign#2675] opened 2017-12-13 11:49 UTC
Numerals from 0 to 100. Example: numerals in statusbar "Energize - Battery Monitor" https://play.google.com/store/apps/details?id=com.halcyonwaves.apps.energize&hl=ru

**Comment by PeterShaggyNoble** [comment] 2017-12-13 12:00
Closing as a duplicate of #1299. Although, personally, I don't see a need for it.

**Closed by PeterShaggyNoble** 2017-12-13 12:00 UTC
