### ISSUE TITLE
surgical

### ISSUE THREAD

**Issue by kipkilimo** [Templarian/MaterialDesign#4115] opened 2019-04-21 14:08 UTC

**Comment by PeterShaggyNoble** [comment] 2019-04-21 22:53
This is very vague. Could you add more detail as to what you're looking for, please?

**Comment by goyney** [comment] 2019-04-22 01:58
Possible duplicate of https://github.com/Templarian/MaterialDesign/issues/864.

**Comment by goyney** [comment] 2019-04-25 17:21
Looks like the OP put this link in the issue template comment:

> https://www.svgrepo.com/show/186994/scalpel.svg

The request for a scalpel is definitely a duplicate of #864. Closing.

**Closed by goyney** 2019-04-25 17:21 UTC
Labels: Consider Closing :door:, Icon Request :pencil2:, Needs More Information :information_source:
