### ISSUE TITLE
Mosquitto (insect)

### ISSUE THREAD

**Issue by SeByDocKy** [Templarian/MaterialDesign#5979] opened 2021-05-14 10:33 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home assistant panel

## Examples

https://thenounproject.com/term/mosquito/

**Comment by wiewior81** [comment] 2021-07-31 17:28
Up! Need such icon, too!!

**Comment by goyney** [comment] 2021-08-30 21:59
Duplicate of #4637.

**Closed by goyney** 2021-08-30 21:59 UTC
Labels: Icon Request
