### ISSUE TITLE
fuel icons

### ISSUE THREAD

**Issue by Pharcon** [Templarian/MaterialDesign#2039] opened 2017-04-23 22:09 UTC
Please...

I'm not find a fuel icons. Where i find this, or not created yet?

**Comment by Templarian** [comment] 2017-04-23 23:13
[![gas-station](https://materialdesignicons.com/icon/gas-station)](https://materialdesignicons.com/icon/gas-station)

Duplicate of #1876

**Closed by Templarian** 2017-04-23 23:13 UTC
