### ISSUE TITLE
Request: Google Home

### ISSUE THREAD

**Issue by ferdydek** [Templarian/MaterialDesign#2008] opened 2017-04-10 22:53 UTC
Request for "google home" (app) icon
    https://blog.google/products/chromecast/meet-new-google-home-app/

other useful missing icons:
Google Home (device) 
   https://www.iconfinder.com/icons/2026278/google_google_home_home_icon

**Comment by Templarian** [comment] 2017-04-10 23:05
Duplicate of #1811

**Closed by Templarian** 2017-04-10 23:05 UTC
