### ISSUE TITLE
Student icon

### ISSUE THREAD

**Issue by JonasTheGamer** [Templarian/MaterialDesign#6450] opened 2022-02-05 23:14 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In a student administration system. The only alternative right now is a baby face icon. I think this kind of icon would look better. 

If possible it would be amazing if you also added an outline variant. Thanks!

### Give us an example of what this icon might look like.

![istockphoto-910023366-1024x1024](https://user-images.githubusercontent.com/38383712/152662120-13a0c9ea-f29d-433a-855b-e91f21fe0f62.jpg)

**Comment by goyney** [comment] 2022-02-06 20:51
Dupe of https://github.com/Templarian/MaterialDesign/issues/5401.

**Closed by goyney** 2022-02-06 20:51 UTC
Labels: Icon Request
