### ISSUE TITLE
Rooms

### ISSUE THREAD

**Issue by PilaScat** [Templarian/MaterialDesign#7418] opened 2024-04-06 10:15 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For floors and rooms on Home Assistant.
I need:
- Garden/Outside
- Kitchen
- Living Room
- Bathroom
- Bedroom
- Cellar/Basement
and so on

### Give us an example of what this icon might look like.

Some may correspond to the icons of the individual objects in the room, for the others I have no particular preferences

**Comment by mririgoyen** [comment] 2024-04-23 14:41
This is a duplicate of #4293. There are also several independent requests for individual rooms in the past.

The short answer is, there is no sure-fire way to represent each room in a very consistent way. However, we do have icons that will meet each room's purpose contextual. Examples of this could include a `fridge` for the Kitchen, or `flower` for Garden. If there is one specific instance where you cannot find an icon to contextually represent a room, please open an individual issue for that. Thanks!

**Closed by mririgoyen** 2024-04-23 14:41 UTC
Labels: Icon Request
