### ISSUE TITLE
window open closed european version

### ISSUE THREAD

**Issue by HomeOfSourceCode** [Templarian/MaterialDesign#6682] opened 2022-06-30 06:59 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In europe the windows are opened not horizontal, they open vertical. It would be nice to have such symbols in the TTF-font

### Give us an example of what this icon might look like.

![grafik](https://user-images.githubusercontent.com/33092270/176612945-47d80108-5559-48f3-bd53-5ac4c1221d9b.png)
![grafik](https://user-images.githubusercontent.com/33092270/176613013-2c3990ce-55eb-4f67-a552-40e3fe8b6204.png)

**Comment by goyney** [comment] 2022-06-30 12:30
Duplicate of #6184, #5923, #5710, #4770. In short, no one's come up with a valid solution for this that follows Material guidelines.

**Closed** 2022-06-30 12:31 UTC
Labels: Icon Request, Duplicate
