### ISSUE TITLE
Smoke detector

### ISSUE THREAD

**Issue by chemelli74** [Templarian/MaterialDesign#5517] opened 2020-09-23 21:45 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Current smoke detector image is not really significative.
Below example can be easier to understand.
Please consider a off version as well.

## Examples

![image](https://user-images.githubusercontent.com/57354320/94072571-3b7c3780-fdf6-11ea-8431-1e7f6648d996.png)

**Comment by Xenomorph99** [comment] 2020-09-24 00:01
I agree that the current [smoke-detector](https://materialdesignicons.com/icon/smoke-detector) icon doesn't read as well as the example you provided. We should create a `smoke-detector-variant` icon. I played around with a few ideas, but nothing was working. We'll see if anyone else can come up with a good idea for it.

I created a `fire-sensor` icon similar to [motion-sensor](https://materialdesignicons.com/icon/motion-sensor) with an "off" version.

![fire-sensor](https://user-images.githubusercontent.com/1837101/94085727-1a9bee00-fdc6-11ea-844e-8d91cec7e94e.png)
![fire-sensor-off](https://user-images.githubusercontent.com/1837101/94085726-1a035780-fdc6-11ea-85a1-0de763b5ea81.png)

I also created the "fire", "off", and "outline" variants of our current [smoke-detector](https://materialdesignicons.com/icon/smoke-detector) icon in case anyone decides to use the one we already have.

![smoke-detector-outline](https://user-images.githubusercontent.com/1837101/94085856-78c8d100-fdc6-11ea-8dfd-f39e5ebde10b.png)

![smoke-detector-off](https://user-images.githubusercontent.com/1837101/94085854-78c8d100-fdc6-11ea-9dd1-e2dfe8f956b4.png)
![smoke-detector-off-outline](https://user-images.githubusercontent.com/1837101/94085853-78303a80-fdc6-11ea-91bd-3a7577ffda13.png)

![smoke-detector-fire](https://user-images.githubusercontent.com/1837101/94085851-78303a80-fdc6-11ea-9c07-067e350df187.png)
![smoke-detector-fire-outline](https://user-images.githubusercontent.com/1837101/94085849-7797a400-fdc6-11ea-91f8-aa0ffaab4e01.png)

[smoke-detector-and-fire-sensor.zip](https://github.com/Templarian/MaterialDesign/files/5272605/smoke-detector-and-fire-sensor.zip)

**Comment by goyney** [comment] 2020-09-24 13:58
This is a duplicate of #2864. Please search before posting.

**Closed by goyney** 2020-09-24 13:58 UTC
Labels: Icon Request

**Comment by chemelli74** [comment] 2020-09-24 14:50
@goyney, Sorry didn't find it. I bag your pardon.

@Xenomorph99 can you update the other issue with your great work ?
Thx in advance,

Simone
