### ISSUE TITLE
Downlight Icon

### ISSUE THREAD

**Issue by Grubs** [Templarian/MaterialDesign#5463] opened 2020-08-29 03:27 UTC
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Could be used to show modern led downlights.

## Examples

https://i.imgur.com/zMbZOkY.png

Top row, 3rd from the left.

**Comment by goyney** [comment] 2020-08-30 00:43
Duplicate of https://github.com/Templarian/MaterialDesign/issues/1826.

**Closed by goyney** 2020-08-30 00:43 UTC
Labels: Icon Request
