### ISSUE TITLE
Icon Request: Magnet

### ISSUE THREAD

**Issue by andreibotezatu** [Templarian/MaterialDesign#557] opened 2015-07-30 13:33 UTC
Torrent Magnet Icon

**Comment by CoDEmanX** [comment] 2015-07-30 13:38
Doesn't seem to be a brand icon, thus I would consider this request as a duplicate of #447

**Comment by Templarian** [comment] 2015-07-30 16:10
Agreed this is a duplicate. I think both magnet icons will be added from 447 and either would be fine for this use case.

**Closed by Templarian** 2015-07-30 16:10 UTC
Labels: Duplicate, Icon Request
