### ISSUE TITLE
Icon for window/door with tilt position

### ISSUE THREAD

**Issue by zufivan** [Templarian/MaterialDesign#5710] opened 2020-12-17 14:16 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

**Status window or door in Home Hassistant:**
open window/door
tilt position window/door
close window/door

## Examples

![open](https://user-images.githubusercontent.com/47624226/102498331-1bb58200-407a-11eb-9828-230c8d43c754.PNG)
![tilt_position](https://user-images.githubusercontent.com/47624226/102498320-1821fb00-407a-11eb-8230-c6449b3b523a.PNG)
![close](https://user-images.githubusercontent.com/47624226/102498306-13f5dd80-407a-11eb-9be6-5253e41bb43b.PNG)

**Comment by dpeter99** [comment] 2020-12-17 20:19
Those examples have perspective and the material icons can't have that. So this might be a bit hard to represent in material icons but I'm sure the additions would be welcomed by the HA community 🙂 

I'm new in the communty.. 😄 I just picked up on that pattern.

**Comment by goyney** [comment] 2021-09-14 00:57
Duplicate of #6184, #5923, #4770. In short, no one's come up with a valid solution for this that follows Material guidelines.

**Closed by goyney** 2021-09-14 00:57 UTC
Labels: Icon Request, Home Assistant
