### ISSUE TITLE
UniPole Hoarding

### ISSUE THREAD

**Issue by sureshreddyputta** [Templarian/MaterialDesign#3856] opened 2019-01-25 05:01 UTC
Can you Please provide unipole hoarding Icon.

![image](https://user-images.githubusercontent.com/21020661/51726220-46644f00-208c-11e9-9537-4b4b8d995ffc.png)

**Comment by PeterShaggyNoble** [comment] 2019-01-25 12:59
Duplicate of #3849

**Closed by PeterShaggyNoble** 2019-01-25 12:59 UTC
