### ISSUE TITLE
Add sort-numeric-ascending/descending

### ISSUE THREAD

**Issue by Dassderdie** [Templarian/MaterialDesign#4699] opened 2019-12-28 22:15 UTC
There are already the following icons:
* sort-alphabetically
* sort-alphabetically-ascending
* sort-alphabetically-descending
* sort-numeric
![image](https://user-images.githubusercontent.com/18506183/71550047-e1b22280-29c7-11ea-8f62-1b6b85859ab7.png)

For consistency there should also be: (in a similar style to the alphabetical ones)
* sort-numeric-ascending
* sort-numeric-descending

**Comment by goyney** [comment] 2019-12-29 04:02
Please DO NOT delete the template. If you searched, you’d know this is a duplicate of #4449.

**Closed by goyney** 2019-12-29 04:02 UTC
Labels: Icon Request
