### ISSUE TITLE
Icon does not work - calendar-month (-outline)

### ISSUE THREAD

**Issue by Subwaytime** [Templarian/MaterialDesign#4220] opened 2019-06-30 09:35 UTC
Hey there,
just trying to get a Calendar working while i checked on the Icons "mdi-calendar-month" and "mdi-calendar-month-outline". Both seem to not work, while every other Icon works!

Greetings,
Subway

**Comment by Templarian** [comment] 2019-06-30 14:48
Can you verify that you have a version 3.6.95+. We're currently on 3.7.95.

https://dev.materialdesignicons.com/history This page shows when icons are added and when releases go out.

**Comment by Subwaytime** [comment] 2019-07-01 06:53
My current Version is updated to latest. Updated after the Icons did not work because i thought it might be the Problem.

> "@mdi/font": "^3.7.95"

**Comment by Templarian** [comment] 2019-07-01 15:39
@Subwaytime Did you run `npm install`? Sorry, just checking everything.

https://cdn.materialdesignicons.com/3.7.95/ Visible here in Chrome.

Maybe it's a specific browser. Which are you viewing this with?

**Comment by Subwaytime** [comment] 2019-07-02 13:26
Yes. I tried to reinstall the whole Project to see if there is an Issue with the node_modules. Unfortunately didnt change anything.

Using the newest Version of Firefox (67.0.4 - 64Bit - Windows 10)

**Comment by goyney** [comment] 2019-07-02 13:34
I am unable to reproduce this issue locally with `@mdi/font`.

I'm also unable to reproduce it using the CDN. See this CodePen: https://codepen.io/anon/pen/BgxLRq

**Comment by Templarian** [comment] 2019-07-03 03:06
I have no idea why it isn't working on your machine @Subwaytime. Do you have some addon installed that could be blocking some class names? Try in incognito.

The cdn/example above works in the browsers I've tried.

**Comment by Subwaytime** [comment] 2019-07-04 08:40
Gonna try a stripped down Version without any CSS and go through each Library to see where the Problem might be.

**Comment by Subwaytime** [comment] 2019-07-05 12:36
Guess i found the Issue, for somewhat Reason i needed to implement the Fonts from the "node_modules" into a different Folder thats located one Folder away from my "style.scss" because i am implementing MaterialDesignIcons like so:
`@import "node_modules/@mdi/font/scss/materialdesignicons.scss";`

Fonts are loaded ".../fonts" in the Library settings, it does not load them from the "node_modules/@mdi/font/fonts/" 

My local Fonts Folder was not updated to the newest Version. Small Question i have now: Why is the "fonts" Folder loaded relatively instead of absolute ?

**Comment by goyney** [comment] 2019-07-14 02:17
What benefit are you getting by trying to include the SCSS file? Just include the minified CSS file instead:

```scss
@import "node_modules/@mdi/font/css/materialdesignicons.css";
```

Much easier and avoids having to configured your SCSS processor in your bundler to handle import paths.

**Comment by Templarian** [comment] 2019-07-14 02:42
@goyney If you use the SCSS directly you get access to the SCSS variables. This can be useful in custom themes that don't want to load the `_icons.scss`.

@Subwaytime Just saw this you can set the folder to anything you want `$mdi-font-path`. 😃 

For anyone using the SCSS we assume your setup might be more custom, so everything can be overridden. If you look at the files everything is `$mdi-*` with defaults.

**Comment by goyney** [comment] 2019-07-14 02:43
Probably should add some of that info to [the docs](https://dev.materialdesignicons.com/getting-started/webfont). 😄

**Comment by Subwaytime** [comment] 2019-07-15 16:40
@Templarian Thank you! Gonna set the Path now to be Absolute :D

@goyney i am using SCSS anyways, so thats why i directly went for the SCSS and some Custom changes!
Gonna give SVG and JS a try if it fits my Project ^^

**Comment by goyney** [comment] 2019-07-15 16:41
Excellent. Going to close this issue now. If you have any other issues, feel free to comment back or open a new issue.

**Closed by goyney** 2019-07-15 16:41 UTC
Labels: Bug, Documentation :book:

**Comment by Subwaytime** [comment] 2019-07-15 17:16
As a hint for anybody that needs an Absolute Path to the Fonts

```scss
$mdi-font-path: "~node_modules/@mdi/font/fonts";`
```
