### ISSUE TITLE
Oil Rig Icon

### ISSUE THREAD

**Issue by fahadfnf** [Templarian/MaterialDesign#5446] opened 2020-08-24 04:56 UTC
Requesting to add new icon for  **oil rig**

**Comment by fahadfnf** [comment] 2020-08-24 05:11
![image](https://user-images.githubusercontent.com/53935516/91006180-58a2c800-e5f6-11ea-9240-92352b2112fc.png)

**Comment by AthulNair** [comment] 2020-08-24 05:14
I am also looking for the same can you please update this
https://github.com/Templarian/MaterialDesign/issues/5416

**Comment by goyney** [comment] 2020-08-24 12:04
Welcome to MDI and thank you for taking the time to create your first contribution. There are couple things I'd like to bring you up to speed on so you can better contribute in the future.

Please *do not* remove our issue template. They are not optional. If you would have followed the instructions in the template, you would have found #5416, which is a duplicate of this issue. We automatically close issues that do not follow the template, and we automatically close issues that are duplicates. Therefore, I am going to close this issue and direct your efforts on #5416.

Thank you!

**Closed by goyney** 2020-08-24 12:04 UTC
Labels: Contribution, Icon Request
