### ISSUE TITLE
Import and/or Export file

### ISSUE THREAD

**Issue by carmelo-ruota** [Templarian/MaterialDesign#754] opened 2015-10-15 09:18 UTC

**Comment by CoDEmanX** [comment] 2015-10-15 17:35
Tricky... some design studies:

![file-import](https://cloud.githubusercontent.com/assets/1309249/10522119/c5894746-7373-11e5-9fb4-8503fe381e0c.png)
![file-export3](https://cloud.githubusercontent.com/assets/1309249/10522120/c5991298-7373-11e5-91e9-acde373eb3ac.png)
![file-import3](https://cloud.githubusercontent.com/assets/1309249/10522121/c5a8be32-7373-11e5-9904-08874d8f74c1.png)
![file-import2](https://cloud.githubusercontent.com/assets/1309249/10522122/c5b5dee6-7373-11e5-811f-7408ec0fc930.png)
![file-export2](https://cloud.githubusercontent.com/assets/1309249/10522123/c5c20ebe-7373-11e5-8af1-d494e8ae485f.png)
![file-export](https://cloud.githubusercontent.com/assets/1309249/10522124/c5cca626-7373-11e5-84e7-eba37022e2c4.png)

I don't like any of them :frowning:

**Comment by Templarian** [comment] 2015-10-18 04:21
I like the first two the most, but 2/4 might be more "Material".

**Comment by CoDEmanX** [comment] 2015-11-22 03:15
Some more tests:
![file-export4a](https://cloud.githubusercontent.com/assets/1309249/11321854/4078ad5c-90cf-11e5-9488-5aed2a597724.png) file shape moved to the left :cactus: 
![file-import4](https://cloud.githubusercontent.com/assets/1309249/11321856/407c5998-90cf-11e5-8dcc-6ba00e305e51.png) works well for import icon...
![file-export4](https://cloud.githubusercontent.com/assets/1309249/11321855/4078c792-90cf-11e5-93ab-e04be5c481b2.png) ... but not export :disappointed:

**Comment by Templarian** [comment] 2015-11-22 23:33
I'm still thinking 2/4 from your oct 15th comment are the best, but I wouldnt' mind adding 5 as `file-move`.

**Comment by CoDEmanX** [comment] 2015-11-23 00:50
These should be the three (import, export, move):
https://www.dropbox.com/s/tzqi3gat4bxnhc1/file-import3.design?dl=0
https://www.dropbox.com/s/1vz1ph35i62dpud/file-export3.design?dl=0
https://www.dropbox.com/s/xur7s9xtamnjsvv/file-import4.design?dl=0

**Comment by Templarian** [comment] 2015-11-23 00:54
[![file-import](https://materialdesignicons.com/icon/file-import)](https://materialdesignicons.com/icon/file-import) [![file-export](https://materialdesignicons.com/icon/file-export)](https://materialdesignicons.com/icon/file-export) [![file-move](https://materialdesignicons.com/icon/file-move)](https://materialdesignicons.com/icon/file-move)

**Comment by CoDEmanX** [comment] 2015-11-23 01:29
Hm you moved the arrow in file-move, which makes somewhat a duplicate of https://materialdesignicons.com/icon/file-send :thought_balloon:

**Comment by Templarian** [comment] 2015-11-23 01:59
Oh, you're right. Deleted. We're starting to hit a point I even lose track of which icons exist.

**Closed by Templarian** 2015-11-23 01:59 UTC
Labels: Icon Request
