### ISSUE TITLE
Medal

### ISSUE THREAD

**Issue by Diggie9** [Templarian/MaterialDesign#2875] opened 2018-03-05 13:00 UTC
I have not seen a medal icon. I need one that i can convert into gold/silver/bronze.

Eventually i'd like to draw a list and display several icons per list item, i couldn't find a suitable icon

Mike
OOOO <- medals
Peter
OO
Lisa
OOOOO

**Comment by PeterShaggyNoble** [comment] 2018-03-05 13:01
Thanks for the request but this is a duplicate of #790.

**Closed by PeterShaggyNoble** 2018-03-05 13:01 UTC
