### ISSUE TITLE
account-setting-outline-variant

### ISSUE THREAD

**Issue by Laim0n** [Templarian/MaterialDesign#4107] opened 2019-04-11 18:01 UTC
### Account settings
I noticed that on the website (including material.io) no this icon and decide to do it yourself. I've seen it used in some elements from Material Design 2.0.

![account_setting_outline_variant](https://pp.userapi.com/c854420/v854420351/1fdf0/FP__hZBSg8E.jpg)

```
<svg xmlns="http://www.w3.org/2000/svg"
	style="width:24px;height:20.48px"
	viewBox="0 0 24 20.48">
  <path d="M11.31,19.03H0v-3.54c0-3.14,6.29-4.72,9.43-4.72c0.39,0,0.82,0.03,1.28,0.07c-0.34,0.69-0.59,1.42-0.73,2.2 
c-0.19-0.01-0.37-0.03-0.56-0.03c-3.51,0-7.19,1.72-7.19,2.48v1.3h8.01C10.49,17.59,10.84,18.35,11.31,19.03z M14.24,4.72 
c0,2.6-2.11,4.72-4.72,4.72c-2.6,0-4.72-2.11-4.72-4.72C4.81,2.11,6.92,0,9.53,0C12.13,0,14.24,2.11,14.24,4.72z M11.89,4.72 
c0-1.3-1.06-2.36-2.36-2.36c-1.3,0-2.36,1.06-2.36,2.36s1.06,2.36,2.36,2.36C10.83,7.07,11.89,6.02,11.89,4.72z M23.98,16.41 
l-1.27,2.1c-0.07,0.16-0.23,0.19-0.38,0.16l-1.55-0.61c-0.33,0.21-0.68,0.42-1.04,0.57l-0.25,1.6c-0.01,0.15-0.15,0.25-0.3,0.25 
h-2.47c-0.18,0-0.31-0.11-0.33-0.25l-0.24-1.6c-0.38-0.16-0.73-0.35-1.05-0.57l-1.55,0.61c-0.13,0-0.3,0-0.38-0.16l-1.25-2.1 
c-0.05-0.13-0.05-0.3,0.07-0.39l1.32-0.99c-0.02-0.21-0.05-0.4-0.05-0.61c0-0.19,0.01-0.4,0.04-0.61l-1.31-0.98 
c-0.12-0.1-0.16-0.23-0.08-0.4l1.25-2.1c0.07-0.16,0.23-0.19,0.38-0.16l1.55,0.61c0.33-0.21,0.68-0.42,1.03-0.57l0.27-1.6 
c0.02-0.15,0.16-0.25,0.34-0.25h2.46c0.16,0,0.29,0.11,0.29,0.25l0.24,1.61c0.38,0.16,0.73,0.35,1.05,0.59l1.55-0.61 
c0.13-0.04,0.3,0,0.38,0.13l1.25,2.1c0.05,0.16,0.05,0.3-0.07,0.39l-1.31,0.98c0.02,0.21,0.05,0.4,0.05,0.61s-0.02,0.4-0.05,0.61 
l1.33,0.99C23.98,16.12,24.03,16.27,23.98,16.41z M20.36,14.42c0-1.34-1.09-2.43-2.43-2.43c-1.34,0-2.43,1.09-2.43,2.43 
c0,1.34,1.09,2.43,2.43,2.43C19.28,16.84,20.36,15.76,20.36,14.42z"/> 
</svg>
```

**Comment by goyney** [comment] 2019-04-12 02:35
Duplicate of https://github.com/Templarian/MaterialDesign/issues/3415.

**Closed by goyney** 2019-04-12 02:35 UTC
