### ISSUE TITLE
Visa Icon

### ISSUE THREAD

**Issue by pixieaka** [Templarian/MaterialDesign#4161] opened 2019-05-23 00:23 UTC
![visa](https://user-images.githubusercontent.com/17777237/58217158-c54b5a80-7d01-11e9-932c-e006382101c1.png)

**Comment by goyney** [comment] 2019-05-23 00:43
Duplicate of https://github.com/Templarian/MaterialDesign/issues/367.

**Closed by goyney** 2019-05-23 00:43 UTC
