### ISSUE TITLE
chevron-triple-*

### ISSUE THREAD

**Issue by RwbyChan2** [Templarian/MaterialDesign#1083] opened 2016-03-07 20:28 UTC
Would really like to see this icon:
https://i.gyazo.com/137e7ec5bc297cda293a3dc1a906c00f.png

**Comment by CoDEmanX** [comment] 2016-03-07 20:42
Looks like a duplicate of rank #1050

**Comment by PeterShaggyNoble** [comment] 2017-12-13 15:48
This is `stat 3` from Google's extended icon set, which also includes the complementary `stat minus 3`.

![stat 3](https://user-images.githubusercontent.com/15157491/33947671-eae1ce4c-e01c-11e7-86d2-fb7dd709b2b3.png) ![stat minus 3](https://user-images.githubusercontent.com/15157491/33947702-059a58da-e01d-11e7-8e3e-2fbd644265c2.png)

**Comment by CoDEmanX** [comment] 2018-04-11 19:10
Also: `chevron-triple-left` and `chevron-triple-right`

**Comment by goyney** [comment] 2018-11-26 04:08
![image](https://user-images.githubusercontent.com/1015040/48992638-e4787f00-f106-11e8-830a-a5377cf87f2b.png)![image](https://user-images.githubusercontent.com/1015040/48992646-ecd0ba00-f106-11e8-99d9-c94320fddbee.png)
![image](https://user-images.githubusercontent.com/1015040/48992649-f3f7c800-f106-11e8-8887-c0bc007d0967.png)![image](https://user-images.githubusercontent.com/1015040/48992654-fb1ed600-f106-11e8-940f-43223e4d0564.png)

[chevron-triple.zip](https://github.com/Templarian/MaterialDesign/files/2614041/chevron-triple.zip)

**Comment by Templarian** [comment] 2019-02-16 19:15
Added.

**Closed by Templarian** 2019-02-16 19:15 UTC
Labels: Contribution :heavy_check_mark:, Icon Request :pencil2:, Stock Google Icon :shipit:
