### ISSUE TITLE
ic_benefit

### ISSUE THREAD

**Issue by guykevin** [Templarian/MaterialDesign#6048] opened 2021-07-01 11:36 UTC
![ic_benefit](https://user-images.githubusercontent.com/56883887/124118159-ef3ae380-da68-11eb-9eff-4b57f55411bd.png)

I have:

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by goyney** [comment] 2021-07-01 13:35
This seems to be a duplicate of #6042. Once again, no further information was provided about what this icon is or should represent. In its current form, it is way too complex to be depicted in Material style at native resolution. Please add comments to #6042 that might help us better understand what this icon should represent so we can see if we can come up with a good solution. Thanks!

**Closed by goyney** 2021-07-01 13:35 UTC
Labels: Contribution, Icon Request

**Comment by guykevin** [comment] 2021-07-01 15:19
ces images représentent les bénéficiaires d'une dépense

Le jeu. 1 juil. 2021 à 14:35, Michael Irigoyen ***@***.***> a
écrit :

**Comment by goyney** [comment] 2021-07-01 15:38
> ces images représentent les bénéficiaires d'une dépense Le jeu.

Google translate: "these images represent the beneficiaries of an expenditure"

**Comment by goyney** [comment] 2021-07-01 15:38
I think your best bet for this idea would be to use `account-cash`.

[![account-cash](https://materialdesignicons.com/icon/account-cash)](https://materialdesignicons.com/icon/account-cash)
