### ISSUE TITLE
Weibo social icon

### ISSUE THREAD

**Issue by he9qi** [Templarian/MaterialDesign#1150] opened 2016-04-10 19:01 UTC
A Weibo (www.weibo.com) material icon would be nice! =)
here's svg sample: [weibo.svg.zip](https://github.com/Templarian/MaterialDesign/files/211926/weibo.svg.zip)

**Comment by PeterShaggyNoble** [comment] 2017-10-06 15:34
Closing this one out as a duplicate of #2235.

**Comment by MrGrigri** [comment] 2017-10-06 15:38
Closing in favor of #2235.

**Closed by MrGrigri** 2017-10-06 15:38 UTC
Labels: Brand Icon, Duplicate, Icon Request
