### ISSUE TITLE
alphabet

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#3025] opened 2018-04-07 15:16 UTC
alphabetic-A, alphabetic-B etc.
alphabetic-a, alphabetic-b etc.
alphabetic-A-box, alphabetic-B-box etc.
alphabetic-a-box, alphabetic-b-box etc.
alphabetic-A-box-outline, alphabetic-B-box-outline etc.
alphabetic-a-box-outline, alphabetic-b-box-outline etc.
alphabetic-A-circle, alphabetic-B-circle etc.
alphabetic-a-circle, alphabetic-b-circle etc.
alphabetic-A-circle-outline, alphabetic-B-circle-outline etc.
alphabetic-a-circle-outline, alphabetic-b-circle-outline etc.

https://www.iconsdb.com/black-icons/black-letter-icons.html

**Comment by GreenTurtwig** [comment] 2018-04-07 15:34
Duplicate of #1299  
Please search before creating an issue. :cat2:

**Closed by GreenTurtwig** 2018-04-07 15:34 UTC
