### ISSUE TITLE
That would be cool to have a Olympic sports collection.

### ISSUE THREAD

**Issue by emburaman** [Templarian/MaterialDesign#579] opened 2015-08-05 15:53 UTC
https://en.wikipedia.org/wiki/Olympic_sports

**Comment by Templarian** [comment] 2015-08-05 15:57
Duplicate of #505, that was closed. Google owns rights to all the Google Fit icons, so we're waiting for them to open source them.

**Closed** 2017-03-08 14:32 UTC
Labels: Duplicate
