### ISSUE TITLE
el-car icon

### ISSUE THREAD

**Issue by sonybansi** [Templarian/MaterialDesign#4035] opened 2019-03-14 22:23 UTC
![images](https://user-images.githubusercontent.com/28208396/54395440-16aaee00-46b0-11e9-9a7b-e1404a3cfbbb.png)

**Comment by sonybansi** [comment] 2019-03-14 22:25
Please add el-car icon.

**Comment by goyney** [comment] 2019-03-14 23:21
Duplicate of https://github.com/Templarian/MaterialDesign/issues/4021.

It already exists as `ev-station`. Please search before requesting icons. Thank you!

**Closed by goyney** 2019-03-14 23:21 UTC
