### ISSUE TITLE
Icon Request - Contains, Does Not Contain, StartsWith, EndsWith

### ISSUE THREAD

**Issue by elliratech** [Templarian/MaterialDesign#4718] opened 2020-01-08 14:19 UTC
I know there are contain, contain-start and contain-end right now however I feel these versions would be more explanatory.

![starts-with](https://user-images.githubusercontent.com/40359349/71984974-e06acc00-31f7-11ea-9739-a26320aa24a9.PNG)
![does-not-contain](https://user-images.githubusercontent.com/40359349/71984975-e06acc00-31f7-11ea-8c40-f23b6e7ec21a.PNG)
![starts-with](https://user-images.githubusercontent.com/40359349/71985268-46575380-31f8-11ea-966b-2e905ed77fc9.PNG)
![ends-with](https://user-images.githubusercontent.com/40359349/71984978-e1036280-31f7-11ea-8faf-4c52bebd453b.PNG)

.

**Comment by goyney** [comment] 2020-01-08 15:24
This is a duplicate of #3883.

**Closed by goyney** 2020-01-08 15:24 UTC
