### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Maur0V** [Templarian/MaterialDesign#2567] opened 2017-10-27 14:31 UTC
an icon with  money or currency and clock  togheter
thanks

**Comment by MrGrigri** [comment] 2017-10-27 20:06
What would you need this for? Could you please include some example usage or examples of what it should look like.

**Comment by PeterShaggyNoble** [comment] 2017-10-27 20:23
Using one of the `currency-*` icons would mean doing it for all those icons which wouldn't be feasible and the `cash` icon is too small to layer anything on top of it so, as @MrGrigri said, a bit of context might help us pick a payment related icon that could be modified, or come up with a completely new one.

**Comment by Maur0V** [comment] 2017-10-28 05:58
hi to all. I'll  need it to identify a pre-paid, time based service. some think like " you pay  then you have some time of work"

**Comment by MrGrigri** [comment] 2017-10-30 14:46
I believe this request is a little too specific and will be quite difficult to make recognizable at a 24x24 size.

**Comment by PeterShaggyNoble** [comment] 2017-12-04 11:36
Closing as a duplicate of #389 which includes some samples.

**Closed by PeterShaggyNoble** 2017-12-04 11:36 UTC
Labels: Icon Request
