### ISSUE TITLE
krul-circle

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6648] opened 2022-06-15 09:33 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

In the Netherlands we make use of this symbol. It's a symbol to state 'this' is approved. We created three versions. A stand alone version. This solid circle version and a circle outline version.

### Share a preview of your contribution.

![preview-krul-circle](https://user-images.githubusercontent.com/107536590/173795155-88149bbe-5071-4159-bdf0-cc35c47bf450.png)

### Upload the icon source.

[krul-circle.svg.zip](https://github.com/Templarian/MaterialDesign/files/8907964/krul-circle.svg.zip)

**Comment by goyney** [comment] 2022-06-15 10:25
Dupe of #6647.

**Closed by goyney** 2022-06-15 10:26 UTC
Labels: Icon Request, Contribution
