### ISSUE TITLE
Angular Material: load iconSet

### ISSUE THREAD

**Issue by Zorgatone** [Templarian/MaterialDesign#854] opened 2015-11-20 13:27 UTC
I wasn't able to load the svg bundle with this API: https://material.angularjs.org/latest/api/service/$mdIconProvider

I had to make myself a bundled file like this one:
https://gist.github.com/Zorgatone/82706d72217160d8f971

**Comment by Zorgatone** [comment] 2015-11-20 13:31
For the reference I just saw what Google did on their example, and to mimic that I concatenated all the svg files, and removed the xml declarations with a regular expression.

Then I wrapped everything inside `<svg><defs></defs></svg>` and each icon inside its group.

Example:

```SVG
<svg><defs>
<g id="menu-down"><path d="M 7,10L 12,15L 17,10L 7,10 Z "/></g>
<g id="menu-left"><path d="M 14,7L 9,12L 14,17L 14,7 Z "/></g>
<g id="menu-right"><path d="M 10,17L 15,12L 10,7L 10,17 Z "/></g>
<g id="menu-up"><path d="M 7,15L 12,10L 17,15L 7,15 Z "/></g>
</defs></svg>
```

**Comment by Templarian** [comment] 2015-11-22 08:50
[Test this download](https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B)

Let me know if the above download works.

**Comment by Zorgatone** [comment] 2015-11-23 07:01
[**@Templarian**](https://github.com/Templarian) commented on [22 nov 2015, 09:50 CET](https://github.com/Templarian/MaterialDesign/issues/854#issuecomment-158737655 "2015-11-22T08:50:11Z - Replied by Github Comment Enhancer"):
> [Test this download](https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B)
> 
> Let me know if the above download works.

As I read through the SVG code, that I'm 99.99% sure that'll work... I'll try it anyway, the format seems correct.

**Comment by Templarian** [comment] 2015-11-23 07:10
Let me know if this updated getting started section makes sense for Angular Material.

https://materialdesignicons.com/getting-started

**Comment by Zorgatone** [comment] 2015-11-23 09:48
Confirmed to be functional.

See the screenshot:
![Screenshot](https://sc-cdn.scaleengine.net/i/cc6de3ec9eefa5a62a507f68ffc2d6f8.png)

**Comment by Zorgatone** [comment] 2015-11-23 09:50
@Templarian, the correct usage of the tag `<md-icon>` is this:

```HTML
<md-icon md-svg-icon="play"></md-icon>
```

**Comment by xenit-raven** [comment] 2015-11-23 11:20
Thanks for this! I'm looking forward to using this in my angular material project!

**Comment by Zorgatone** [comment] 2015-11-23 11:21
:+1:

**Comment by xenit-raven** [comment] 2015-11-23 11:28
Confirmed working. I'll start migrating my project to this solution soon.

**Comment by Templarian** [comment] 2015-11-23 15:14
Thanks guys! Closing out the issue.

Also, I updated the example usage to the correct tag, along with the button example.

**Closed by Templarian** 2015-11-23 15:14 UTC
Labels: Question

**Comment by Zorgatone** [comment] 2015-11-23 15:20
Maybe you could also separate the two code snippets, otherwise some "newbies" may think they have to write the full code in the example...

Or you could just add a comment in between 😇

**Comment by Zorgatone** [comment] 2015-11-23 15:21
I mean, separating the simple icon from the button with the icon..

**Comment by Templarian** [comment] 2015-11-23 15:21
Yea, I'll assume that if they are far enough along to replace the default icon set they'll figure that out. Ha.

**Comment by Zorgatone** [comment] 2015-11-23 15:22
The real issue is that Google didn't provide a "default" one. There are actually some really small examples, but no official icon set.

That's why I used this repo

**Comment by jbcpollak** [comment] 2016-12-13 17:40
I can't find this svg in the package published to npm

**Comment by Templarian** [comment] 2016-12-13 17:48
@jbcpollak We don't publish this to NPM, just the webfont. If you think this would be useful please create an issue requesting this feature.

**Comment by jbcpollak** [comment] 2016-12-13 17:51
Thanks for the quick response. is there a benefit to using the svg or font system? I'm wrestling with how integrate one or the other.

**Comment by Templarian** [comment] 2016-12-13 17:59
@jbcpollak Uhh, both are fine. Some people write scripts to only include the icons they are using rather than including all 1722 icons currently released in the webfont. I will say mobile renders SVG slightly slower than webfonts, but it's not really noticeable until you have like 100+ icons visible.

A lot use the webfont because they are use to Font Awesome, but SVG is more ideal if you're including only the icons you're using in the build process.
