### ISSUE TITLE
Country-codes

### ISSUE THREAD

**Issue by boheme61** [Templarian/MaterialDesign#6254] opened 2021-10-19 13:32 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Country-codes, for the Scandinavian countries, SE ( Sweden), DK (Denmark) etc. ... and similar Currency-codes i.e. SEK (Swedish Kronor)  DKK /Danish kronor , NO (Norway ) etc. ... like they are shown at various sites worldwide.

Could be used on multiple-sites and Apps, where needed other than $ £ 0r euro, personally im new to  HomeAssistant, and im  a little annoyed over the missing Currency symbols, for the Scandinavian Currencies
Country-codes and currency-codes tables is easy to find , so they should be in this repository as well

Best regards Jörgen

### Give us an example of what this icon might look like.

COUNTRY CODES ALPHA-2 (2 digits)

https://www.iban.com/country-codes#:~:text=Country%20Codes%20Alpha-2%20%26%20Alpha-3%20%20%20,%20%20016%20%2079%20more%20rows%20

CURRENCY CODES (3 Digits)

https://currencysystem.com/codes/

Both above could be in a simple Circle , or similar

**Comment by goyney** [comment] 2021-10-19 15:44
Letter-only icons are not a good fit for this library. We only add them in extreme circumstances in which something cannot be distinguished in any other way. In this case, asking for us to create country codes won't happen. You can use the alpha/numeric icons to create your own words/phrases/etc.

To further your original concern for the Scandinavian kroner, that would be a duplicate of #6027.

**Closed by goyney** 2021-10-19 15:44 UTC
Labels: Icon Request
