### ISSUE TITLE
Footprint

### ISSUE THREAD

**Issue by MrMarlin** [Templarian/MaterialDesign#2096] opened 2017-05-19 17:34 UTC
I would really appreciate if you could add a footsteps icon just like this: 

https://cdn4.iconfinder.com/data/icons/maps-and-navigation-solid-icons-vol-1/72/28-512.png

Thanks!

**Comment by augustin32** [comment] 2017-10-01 07:51
![footstep24](https://user-images.githubusercontent.com/14167196/31052761-70fa80d4-a696-11e7-99ea-667888abb0ff.png)
![footstep36](https://user-images.githubusercontent.com/14167196/31052762-71a03a56-a696-11e7-8b75-248f0a908719.png)
![footstep48](https://user-images.githubusercontent.com/14167196/31052763-72ce6722-a696-11e7-86a0-63738a096676.png)
[footstep.zip](https://github.com/Templarian/MaterialDesign/files/1346999/footstep.zip)

**Comment by PeterShaggyNoble** [comment] 2017-10-04 16:33
Would this not be a dupe of #755?

**Comment by MrGrigri** [comment] 2017-10-04 16:48
Nope, however, I don't believe that this icon is Material at all.

**Comment by aardloper** [comment] 2018-02-03 10:04
Which one?
![ic_footprint_black_24px](https://user-images.githubusercontent.com/13365040/35766050-910dc916-08d0-11e8-9d8d-78a5ac707a29.png)
[ic_footprint_black_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/1691592/ic_footprint_black_24px.svg.zip)

**Comment by Templarian** [comment] 2018-02-03 18:34
The 2nd, what do you guys think, definitely not the 1st of 4th it looks like people.

**Comment by MrGrigri** [comment] 2018-02-03 23:54
I believe 2 works. Man, I wish there was a way to have polls on Github Issues.

**Comment by JamesCoyle** [comment] 2018-02-04 02:36
I kinda prefer the third.

**Comment by PeterShaggyNoble** [comment] 2018-02-07 09:26
I'm with @JamesCoyle on the 3rd but still don't think it's quite right.

**Comment by PeterShaggyNoble** [comment] 2018-11-07 10:55
@MrMarlin, please leave this issue open until the request has been fulfilled.

**Comment by goyney** [comment] 2018-11-25 03:17
![image](https://user-images.githubusercontent.com/1015040/48975065-b0ce2400-f036-11e8-8023-b7e782d0b352.png)

[footprints.zip](https://github.com/Templarian/MaterialDesign/files/2612799/footprints.zip)

**Comment by JapanYoshi** [comment] 2019-02-14 12:27
![image](https://user-images.githubusercontent.com/8707990/52786822-42ca5380-309f-11e9-8d76-1b548ec7b4a7.png)
I tried my hand at a non-shoe footprint. I had to merge the toes for abstraction.

**Comment by aardloper** [comment] 2019-02-14 12:35
> ![image](https://user-images.githubusercontent.com/8707990/52786822-42ca5380-309f-11e9-8d76-1b548ec7b4a7.png)
> I tried my hand at a non-shoe footprint. I had to merge the toes for abstraction.

Nice:-) But, my first impression of this icon is a footprint of 2 feet in socks.

**Comment by PeterShaggyNoble** [comment] 2019-02-22 11:10
Yeah, that's a bit too abstract, @JapanYoshi.

**Comment by goyney** [comment] 2019-07-24 00:37
Here's the third option from above with some slight tweaks:
![image](https://user-images.githubusercontent.com/1015040/61756365-9a28ca00-ad89-11e9-9e1b-55158cf42e32.png)

[footprint.svg.zip](https://github.com/Templarian/MaterialDesign/files/3424527/footprint.svg.zip)

**Comment by goyney** [comment] 2019-07-24 01:26
[![foot-print](https://materialdesignicons.com/icon/foot-print)](https://materialdesignicons.com/icon/foot-print)

**Closed by goyney** 2019-07-24 01:26 UTC
Labels: Contribution, Icon Request
