### ISSUE TITLE
icon: mdi:sprinkler-variant

### ISSUE THREAD

**Issue by Houblonde** [Templarian/MaterialDesign#6941] opened 2023-01-22 23:20 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Sprinkler when non active could have the stick only without any water comming out of it....

### Give us an example of what this icon might look like.

exactly like icon: mdi:sprinkler-variant but without water

**Comment by mririgoyen** [comment] 2023-01-23 00:24
Dupe of #5881.

**Closed** 2023-01-23 00:24 UTC
Labels: Icon Request, Duplicate
