### ISSUE TITLE
receipt-add / receipt-remove

### ISSUE THREAD

**Issue by PapyElGringo** [Templarian/MaterialDesign#6336] opened 2021-11-21 10:40 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For when you need to manage libraries of receipts to add or remove a receipt.

### Give us an example of what this icon might look like.

It's should be similar to the existing `receipt` with a `plus` and a `cross` at the bottom right like others Material icons.
Outline variant could be a good addition.

**Comment by Simran-B** [comment] 2021-12-01 21:37
![image](https://user-images.githubusercontent.com/7819991/144317914-a4de2dc8-0c32-4590-939a-8cc9cd01c162.png) ![image](https://user-images.githubusercontent.com/7819991/144317947-e37474b8-70af-457d-9aca-f349a1bb1de3.png)
![image](https://user-images.githubusercontent.com/7819991/144317986-1088d15a-1e5b-4dbb-b3a7-bd7c0c6748c5.png) ![image](https://user-images.githubusercontent.com/7819991/144318021-2451d4a9-d0be-4c54-abe6-15b7d63c9da6.png)

[receipt-add.zip](https://github.com/Templarian/MaterialDesign/files/7637243/receipt-add.zip)

**Comment by PapyElGringo** [comment] 2021-12-01 22:46
Great

**Comment by goyney** [comment] 2022-03-21 03:43
Thanks for the request. However, this is a duplicate of #____. Please go give that issue a 👍  and subscribe to watch for updates.

Also, please remember to search existing icons and issues before posting a request.

**Closed by goyney** 2022-03-21 03:43 UTC
Labels: Icon Request, Contribution

**Comment by goyney** [comment] 2022-03-21 03:45
These all use the new base name of `receipt-text`, even though the original `receipt` icons won't be [renamed until v7](https://github.com/Templarian/MaterialDesign/issues/6504).
[![receipt-text-plus](https://materialdesignicons.com/icon/receipt-text-plus)](https://materialdesignicons.com/icon/receipt-text-plus)[![receipt-text-plus-outline](https://materialdesignicons.com/icon/receipt-text-plus-outline)](https://materialdesignicons.com/icon/receipt-text-plus-outline)
[![receipt-text-minus](https://materialdesignicons.com/icon/receipt-text-minus)](https://materialdesignicons.com/icon/receipt-text-minus)[![receipt-text-minus-outline](https://materialdesignicons.com/icon/receipt-text-minus-outline)](https://materialdesignicons.com/icon/receipt-text-minus-outline)
[![receipt-text-remove](https://materialdesignicons.com/icon/receipt-text-remove)](https://materialdesignicons.com/icon/receipt-text-remove)[![receipt-text-remove-outline](https://materialdesignicons.com/icon/receipt-text-remove-outline)](https://materialdesignicons.com/icon/receipt-text-remove-outline)
[![receipt-text-check](https://materialdesignicons.com/icon/receipt-text-check)](https://materialdesignicons.com/icon/receipt-text-check)[![receipt-text-check-outline](https://materialdesignicons.com/icon/receipt-text-check-outline)](https://materialdesignicons.com/icon/receipt-text-check-outline)
