### ISSUE TITLE
iron

### ISSUE THREAD

**Issue by guiumb** [Templarian/MaterialDesign#4183] opened 2019-06-09 15:27 UTC
Dear All,

is it possible to have iron icon implemented ? In a Home Automation enviroment  is very important as Fridge, Washing Machines and all the other already usable.

Many thanks in advance

Umberto

**Comment by MrGrigri** [comment] 2019-06-10 20:41
I would love to know how a 'smart iron' exists?!

**Comment by goyney** [comment] 2019-06-22 02:02
Duplicate of #2752.

**Closed by goyney** 2019-06-22 02:02 UTC
Labels: Icon Request
