### ISSUE TITLE
Master Card Icon

### ISSUE THREAD

**Issue by pixieaka** [Templarian/MaterialDesign#4162] opened 2019-05-23 00:24 UTC
![38943](https://user-images.githubusercontent.com/17777237/58217182-d5fbd080-7d01-11e9-9702-800419405c83.png)

**Comment by goyney** [comment] 2019-05-23 00:43
Duplicate of https://github.com/Templarian/MaterialDesign/issues/367.

**Closed by goyney** 2019-05-23 00:43 UTC
