### ISSUE TITLE
puzzle-plus

### ISSUE THREAD

**Issue by Ertego** [Templarian/MaterialDesign#5123] opened 2020-04-29 13:10 UTC
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
This icon partially fulfills [this request](https://github.com/Templarian/MaterialDesign/issues/5110)
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/26722878/80599270-fad8e780-8a2a-11ea-907a-ac1736a6a4c3.png)

## Zip Download

[puzzle-plus.zip](https://github.com/Templarian/MaterialDesign/files/4551830/puzzle-plus.zip)

**Comment by goyney** [comment] 2020-04-29 13:42
Duplicate of #5110.

**Closed by goyney** 2020-04-29 13:42 UTC
Labels: Contribution, Icon Request
