### ISSUE TITLE
Australian power socket icon contribution 

### ISSUE THREAD

**Issue by bigwoof** [Templarian/MaterialDesign#2279] opened 2017-07-25 01:55 UTC
Hi There,

I have adapted the power socket provided by @greenturtwig to make an Australian socket:
[power-socket-au.zip](https://github.com/Templarian/MaterialDesign/files/1171706/power-socket-au.zip)

I am not sure how to go about getting it into the project, as I am not familiar with gitub.

Also I put it together in inksacape as an SVG as that is the only software I have for this. 

Cheers

Phil

**Comment by PeterShaggyNoble** [comment] 2017-10-06 15:04
Closing this out as a dupe of #2444 as there's more activity on that issue.

**Closed by PeterShaggyNoble** 2017-10-06 15:04 UTC
Labels: Contribution, Icon Request
