### ISSUE TITLE
foot icon

### ISSUE THREAD

**Issue by dgaenko** [Templarian/MaterialDesign#3499] opened 2018-09-21 12:41 UTC
Hello guys!

Make steps icon, please. For example as link
https://image.freepik.com/free-icon/footsteps-silhouette-variant_318-48762.jpg

**Comment by MrGrigri** [comment] 2018-09-21 17:56
I could have sworn we already had an issue for this.

**Comment by PeterShaggyNoble** [comment] 2018-09-22 09:16
Duplicate of #755

**Closed by PeterShaggyNoble** 2018-09-22 09:16 UTC
Labels: Icon Request :pencil2:
