### ISSUE TITLE
phone-off

### ISSUE THREAD

**Issue by savaka2** [Templarian/MaterialDesign#1634] opened 2016-11-14 23:39 UTC
probably going to have to reverse the off slash though

**Comment by Templarian** [comment] 2016-11-17 05:12
Just for clarity, what is this icon going to represent?

I'm mostly asking since I think `phone-hangup` might be a better choice. It's an odd icon to add a slash to, but we have broken the direction of the `off` slash a few times.

**Comment by savaka2** [comment] 2016-11-17 12:46
If you need to separate ringtone and notification volumes, you'd use it to turn off ringtone volume

**Comment by GreenTurtwig** [comment] 2016-11-25 08:56
Here:
[phone-off.zip](https://github.com/Templarian/MaterialDesign/files/612838/phone-off.zip)
The slash has been flipped to avoid removing detail. :cat2:

**Comment by PeterShaggyNoble** [comment] 2018-03-05 16:49
Possible duplicate of #1062?

**Comment by CoDEmanX** [comment] 2018-03-15 13:04
I guess phone-off would work for #1062 (broken cellphone) as well. Although I wonder in what way broken and in which situation to use it...

**Comment by Templarian** [comment] 2019-02-01 06:56
[![phone-off](https://materialdesignicons.com/icon/phone-off)](https://materialdesignicons.com/icon/phone-off)

**Closed by Templarian** 2019-02-01 06:56 UTC
Labels: Contribution :heavy_check_mark:, Icon Request :pencil2:
