### ISSUE TITLE
medicine-bottle

### ISSUE THREAD

**Issue by djm228** [Templarian/MaterialDesign#6566] opened 2022-04-26 18:48 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I'm designing a website that sells natural remedies. I needed an icon for vitamins, so I designed this. I believe other users may benefit from its use.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/56743122/165370503-54948e1f-33c6-4ad6-b556-a6c909bf8463.png)

### Upload the icon source.

[medicine-bottle.zip](https://github.com/Templarian/MaterialDesign/files/8566030/medicine-bottle.zip)

**Comment by goyney** [comment] 2022-04-26 19:03
Dupe of #6565.

**Closed by goyney** 2022-04-26 19:04 UTC
Labels: Icon Request, Contribution
