### ISSUE TITLE
Divers(Gender) Icon

### ISSUE THREAD

**Issue by PrinzKenny1** [Templarian/MaterialDesign#5597] opened 2020-10-25 22:23 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This item could be used in Register Forms for the selection of the gender.

## Examples

The icon could look like this: https://t4.ftcdn.net/jpg/02/23/04/53/500_F_223045392_C6MrcGzmJ0PWSUYAKWaQMINThRFpmNNo.jpg

But the two pieces connected.

Thanks
PrinzKenny1

**Comment by goyney** [comment] 2020-10-26 12:26
Would `human-male-female` not fulfill this need?
[![human-male-female](https://materialdesignicons.com/icon/human-male-female)](https://materialdesignicons.com/icon/human-male-female)

**Comment by PrinzKenny1** [comment] 2020-10-26 15:48
Nah I don't think so. This icon is more like that there are two persons and not one.... Furthermore it would look awkward if you have the icons male, female and then you have male female...

Greetings

**Comment by GreenTurtwig** [comment] 2020-10-26 17:27
I'm not opposed to adding this, but it really shouldn't be used in situations such as this since not everybody fits into the spectrum of male and female. Is it being used alongside the question on the form, or are there indivdual icons representing each option?  
Would `human` or `account` not work instead?  
[![human](https://materialdesignicons.com/icon/human)](https://materialdesignicons.com/icon/human)[![account](https://materialdesignicons.com/icon/account)](https://materialdesignicons.com/icon/account)

**Comment by PrinzKenny1** [comment] 2020-10-26 20:44
Currently I`m using human, as you suggested. But I think it would be a lot nicer to have this extra icon.
Here a Screenshot of my app where I would need this icon: https://i.imgur.com/OzuHffx.png

**Comment by goyney** [comment] 2020-10-26 20:51
Have you considered using the `gender-*` icons we already have? We have more options there for gender alignments.

**Comment by GreenTurtwig** [comment] 2020-10-26 21:03
Oh that's great, ta. I assume the centre option is "Other"? If so that won't fit for everyone as the layout represents a binary spectrum, which not everybody falls into. Ideally it'd be to the right and not the centre with an additional option for "Prefer not to say" or the question simply wouldn't be asked.  
I hope I'm don't sound too bossy, just want to help make it as inclusive as possible. :-)  
Worth noting we're missing a fair few `gender-*` symbols, specifically neutral. and agender.

**Comment by PrinzKenny1** [comment] 2020-10-27 20:11
@goyney that would probably be a good solution, thanks!

@GreenTurtwig The option in the center means "Divers" in Germany and is a synonym for all different kinds of genders, as far as I understood it. I only have these 3 icons because I want to ask for the physical gender first and after that for the emotional gender (how the person feels itself). And last but not least I totally agree to the missing icons you mentioned.

**Comment by PrinzKenny1** [comment] 2020-10-27 20:20
@GreenTurtwig As you can see here, that`s the next page: https://i.imgur.com/xaFxYKr.png
Also since it`s a dating app, it is necessary to provide a gender... At least the physical

**Comment by GreenTurtwig** [comment] 2020-10-27 21:41
Ahh yes, thank you so much for all that information, fab. I assume you mean intersex then? If so `gender-male-female` would work. If you want to go the `human-*` route though I'd still recommend using `human`, but I'll add the suggestion anyway, only issue is in the naming.  
One suggestion I would make would be to present the gender option before the one for sex, as otherwise it could be a bit confusing. :-)

**Comment by GreenTurtwig** [comment] 2020-10-29 20:07
😕 

![](https://user-images.githubusercontent.com/15905797/97626721-2c565e00-1a22-11eb-8810-afed4216fe51.png)![](https://user-images.githubusercontent.com/15905797/97626778-455f0f00-1a22-11eb-9bc4-c30f8f6155f7.png)
[human-male-female-variant.zip](https://github.com/Templarian/MaterialDesign/files/5460968/human-male-female-variant.zip)

**Comment by Templarian** [comment] 2020-10-29 20:10
That just looks like our pregnant icon. 🤔

**Comment by GreenTurtwig** [comment] 2020-10-29 21:07
> 
> 
> That just looks like our pregnant icon. 🤔

Exactly what I was thinking.

**Comment by Xenomorph99** [comment] 2020-10-30 15:54
@GreenTurtwig, would it be possible to split the icon down the center with a vertical line and some negative space similar to how our `-off` modifier works? However, that might ruin the meaning.

I found this image:

![image](https://user-images.githubusercontent.com/1837101/97726951-6745a980-1a95-11eb-8df7-88b9ae770bd5.png)

Perhaps there's some way to add arms?

**Comment by goyney** [comment] 2021-09-02 17:49
Duplicate of #2581.

**Closed by goyney** 2021-09-02 17:49 UTC
Labels: Icon Request, Contribution
