### ISSUE TITLE
Google Scatter Plot Icon

### ISSUE THREAD

**Issue by ohsk** [Templarian/MaterialDesign#3640] opened 2018-10-19 14:32 UTC
Requesting this icon from the Google:
https://material.io/tools/icons/?search=scatt&icon=scatter_plot&style=baseline

![image](https://user-images.githubusercontent.com/1689222/47224749-40bee500-d38a-11e8-876a-a98dc9f8f640.png)

Thanks!

**Comment by PeterShaggyNoble** [comment] 2018-10-19 14:37
Duplicate of #2316 - we'll use that to track this icon so can you post the link there and give the issue a 👍, please?

**Closed by PeterShaggyNoble** 2018-10-19 14:37 UTC

**Comment by ohsk** [comment] 2018-10-19 15:49
@PeterShaggyNoble I saw #2316 but got the impression that he was requesting a scatter plot icon that had the plot points AND a vertical/horizontal axis in the icon. Also noted in the other linked issue #498 there: 

![image](https://user-images.githubusercontent.com/1689222/47229087-dd868000-d394-11e8-9fab-10f32a1b326e.png)

I was specifically requesting just the plot points as shown in Google's existing example. But maybe I'm misreading #2316 and happy to just 👍 that one if that's how you interpret it!

**Comment by PeterShaggyNoble** [comment] 2018-10-19 17:02
No, I could well have been misreading #2316, been one of those day 😕 May as well use that issue to track both, though, anyway, as they're very closely related.
