### ISSUE TITLE
Icon for stamp

### ISSUE THREAD

**Issue by kovkus** [Templarian/MaterialDesign#1552] opened 2016-10-05 15:05 UTC
It will be nice to have icon for stamp - something like outline of [this](http://ajotte.com/wp-content/uploads/symbiostock_rf_content/1852-old-rubber-stamp.jpg)

**Comment by Templarian** [comment] 2016-10-06 03:57
Going to mark this as a duplicate of #621. I have a feeling it will end up being a stamper in the end due to detail limits in these smaller sizes.

**Closed by Templarian** 2016-10-06 03:57 UTC
