### ISSUE TITLE
car-plus 

### ISSUE THREAD

**Issue by AlixH** [Templarian/MaterialDesign#6173] opened 2021-09-05 15:27 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

An icon to add a car. There are already car-2-plus and car-3-plus but no simple car-plus

### Give us an example of what this icon might look like.

<img width="200" alt="Screenshot 2021-09-05 at 17 27 13" src="https://user-images.githubusercontent.com/32574035/132132250-9811879f-a213-46bd-9d44-6c4cd038fce3.png">
this without the '2'

**Comment by goyney** [comment] 2021-09-05 17:53
Duplicate of #5821.

**Closed by goyney** 2021-09-05 17:53 UTC
Labels: Icon Request
