### ISSUE TITLE
New item Doors

### ISSUE THREAD

**Issue by turboc1208** [Templarian/MaterialDesign#1976] opened 2017-03-29 23:21 UTC
I see you have a glass door.  

How about a solid open and closed door.  Like a traditional door showing door frame a thin white line inside it framing the actual door and a door knob of some type.  and a door frame with the door open maybe 45 degrees or something.

**Comment by Templarian** [comment] 2017-03-29 23:30
Duplicate of #1822

**Closed by Templarian** 2017-03-29 23:30 UTC

**Comment by PeterShaggyNoble** [comment] 2017-03-29 23:40
`glassdoor`, by the way, is a [brand icon](http://glassdoor.com).
