### ISSUE TITLE
Garden Uplighter

### ISSUE THREAD

**Issue by Builder-DE-TH** [Templarian/MaterialDesign#6748] opened 2022-08-15 09:11 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

A spotlight in the ground that illuminates trees and plants upwards at night.

For use in Home Assistant

### Give us an example of what this icon might look like.

![garden uplighter](https://user-images.githubusercontent.com/109861242/184608561-6a4393f7-547e-426f-9fe2-fd478cefd0fb.png)

**Comment by Circeus** [comment] 2022-08-15 18:58
Wouldn't it be enough to rotate track-light 180°?

**Comment by Builder-DE-TH** [comment] 2022-08-18 09:03
Yes that would do fine

**Comment by mririgoyen** [comment] 2022-08-24 02:18
Duplicate of #5295.

**Closed by mririgoyen** 2022-08-24 02:18 UTC
Labels: Icon Request
