### ISSUE TITLE
Icons for public administration and city council

### ISSUE THREAD

**Issue by chof1** [Templarian/MaterialDesign#5552] opened 2020-10-02 08:16 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

we create apps and web projects for german public administration to support the work of city councils et al.
Therefore, I am looking for icons representing meetings, councils, management boards etc.
also different kinds of votings, ballots, Pie-charts, Council buildings such as a city hall or congress center and so on

## Examples

![grafik](https://user-images.githubusercontent.com/72249627/94902161-09bf3c80-0498-11eb-9779-afc5f8311773.png)
![grafik](https://user-images.githubusercontent.com/72249627/94902318-3f642580-0498-11eb-9d09-75c184b6f1bc.png)

Thanks in advance
chris

**Comment by goyney** [comment] 2021-09-05 01:55
We've recently added `town-hall`.

Otherwise, this is a duplicate of #5168.

**Closed by goyney** 2021-09-05 01:55 UTC
Labels: Icon Request
