### ISSUE TITLE
New linux icon

### ISSUE THREAD

**Issue by yassinemaaroufi** [Templarian/MaterialDesign#2863] opened 2018-03-02 00:33 UTC

**Comment by PeterShaggyNoble** [comment] 2018-03-02 11:03
Do you mean the square icon below? I don't know that we're going to be able to add it as it looks like it needs to be duotone.

![Linux Foundation](https://user-images.githubusercontent.com/15157491/36895950-ac733798-1e08-11e8-811e-d0ea4a50b070.png)

**Comment by yassinemaaroufi** [comment] 2018-03-02 11:12
I meant the tux icon that represents linux as a whole like the one
attached.

There is an icon labelled linux but it doesn't look very good in particular
when it is beside the windows and mac icons for software downloads.

**Comment by PeterShaggyNoble** [comment] 2018-03-02 11:19
I'm going to close this as a duplicate of #2664. It was also brought up in #2591 and see #41 for the original request where @Templarian highlights some of the issues with getting Tux right.

Sidenote: email attachments don't get included in GitHub comments.

**Closed by PeterShaggyNoble** 2018-03-02 11:19 UTC
Labels: Brand Icon :bookmark:, Needs More Information :information_source:
