### ISSUE TITLE
redis

### ISSUE THREAD

**Issue by matinwd** [Templarian/MaterialDesign#4922] opened 2020-02-25 06:30 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

![787xlgwc2hhq3ctzxcvs](https://user-images.githubusercontent.com/52950867/75220777-7ad99b80-57b5-11ea-9aef-98526b23fc7b.png)

**Comment by Templarian** [comment] 2020-02-25 06:40
@matinwd Pasted the issue template back in. As it says 1 icon request per issue.

**Comment by Templarian** [comment] 2020-02-25 06:42
@matinwd `mysql` was a duplicate of #1782

**Comment by Templarian** [comment] 2020-02-25 06:42
@matinwd Please keep the titles to just the icon name.

**Comment by matinwd** [comment] 2020-02-25 06:42
OK thanks.

**Comment by goyney** [comment] 2020-02-25 06:56
Seems like a better request for Simple Icons.

**Comment by Templarian** [comment] 2020-02-25 07:07
Yeah, they already have it. While we do usually allow tech iconography it may not make sense for databases as most database icons wouldn't work at the small size.

- https://simpleicons.org/?q=redis
- https://simpleicons.org/?q=mysql

**Comment by goyney** [comment] 2020-02-25 14:34
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Closed by goyney** 2020-02-25 14:34 UTC
Labels: Brand Icon, Icon Request
