### ISSUE TITLE
chef's hat 

### ISSUE THREAD

**Issue by mowmoth** [Templarian/MaterialDesign#3089] opened 2018-04-19 09:32 UTC
I think something like this could make an excellent addition (hopefully not just for me). I'm sadly not versed enough in Illustrator or other software of that kind.

Reference from [https://icons8.com](url)
![chefshat](https://user-images.githubusercontent.com/21076995/38983695-42e7c3ba-43c5-11e8-8de3-59e35095d846.PNG)

**Comment by PeterShaggyNoble** [comment] 2018-04-19 09:34
Thanks for the request. However, this is a duplicate of #659.

Don't forget to search existing issues and icons before posting new requests.

**Closed by PeterShaggyNoble** 2018-04-19 09:34 UTC
