### ISSUE TITLE
Phabricator Logo

### ISSUE THREAD

**Issue by TimDiekmann** [Templarian/MaterialDesign#4380] opened 2019-08-29 17:49 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't **an [active]** request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Notes on "an active" request

#3120 already asked for a Phabricator icon over 1,5 years ago and Phabricator isn't such a niche anymore. There ws no response since one year, meanwhile, fontawesome also added a Phabricator logo. Additionally, the logo in #3120 is very outdated.

## Usage

On concourse-CI it's possible to mark resources with a material icon and many resources comes from a Phabricator instance. It would be very nice to add an appropriate icon there.

## Examples

The logo should look like [the official one](https://secure.phabricator.com/F4999200) on https://secure.phabricator.com/ (the official dev-instance of Phacility)
![image](https://user-images.githubusercontent.com/21277928/63963974-5fa40280-ca96-11e9-8119-aa40f9a3013e.png)

**Comment by PeterShaggyNoble** [comment] 2019-08-29 17:54
Duplicate of #3120

**Closed by PeterShaggyNoble** 2019-08-29 17:54 UTC
Labels: Icon Request
