### ISSUE TITLE
Fun-icon

### ISSUE THREAD

**Issue by haseri** [Templarian/MaterialDesign#3751] opened 2018-12-03 09:22 UTC
Icon for category "Fun"
[fun.zip](https://github.com/Templarian/MaterialDesign/files/2638795/fun.zip)

**Comment by JamesCoyle** [comment] 2018-12-03 12:21
Your contribution doesn't really fit in with the material style. Make sure to keep designs geometric. For reference please read the [guidelines](https://material.io/design/iconography/system-icons.html).

We also have the following which may suit this purpose:
[![](https://materialdesignicons.com/icon/emoticon)](https://materialdesignicons.com/icon/emoticon)[![](https://materialdesignicons.com/icon/emoticon-excited)](https://materialdesignicons.com/icon/emoticon-excited)

**Comment by MrGrigri** [comment] 2018-12-03 16:06
**_FOR REFERENCE ONLY_**

---

![rejected](https://user-images.githubusercontent.com/4528551/49385445-b5e83e80-f6da-11e8-8e92-79cafa5884e6.png)

**Comment by PeterShaggyNoble** [comment] 2018-12-03 18:01
Duplicate of #3148

**Closed by PeterShaggyNoble** 2018-12-03 18:01 UTC
Labels: Icon Request :pencil2:
