### ISSUE TITLE
New Website status?

### ISSUE THREAD

**Issue by JokerMartini** [Templarian/MaterialDesign#6629] opened 2022-06-10 13:48 UTC
### What is your question?

A few years ago you guys were working on a new website. I was wondering if that is still happening or if there were any updates. The current website is quite slow and clunky at times even with Google Fiber as a provider.

It would great to see little quality of life improvements to the website as well like a simple button [copy] which just copies the icon name to clipboard for ease use in web development.

FontAwesome https://fontawesome.com recently updated their website and it's slick and super fast. I hope MaterialDesign has some updates, ive been a long supportive fan of what you guys are doing here.

**Comment by goyney** [comment] 2022-06-10 20:34
Duplicate of #5161.

The short is, we're still working on it. We're just a handful of volunteers who work on MDI when time permits.

**Closed by goyney** 2022-06-10 20:34 UTC
Labels: Question

**Comment by mririgoyen** [comment] 2023-01-24 05:19
Just an update, in case you haven't seen, but we did launch our new website!

https://pictogrammers.com/library/mdi/

**Comment by JokerMartini** [comment] 2023-01-24 20:52
sweet ill have to check it out. im pretty excited about it. initially testing it, it's incredibly slow. im guessing it's just still in beta maybe. It's been 'gathering icons' for multiple minutes now...

**Comment by mririgoyen** [comment] 2023-01-24 20:54
Yeah, we know. 😢 

See: https://github.com/Pictogrammers/pictogrammers.com/issues/25

We just rolled back. Something is killing the server and we're trying to figure out what.
