### ISSUE TITLE
Chandelier icon

### ISSUE THREAD

**Issue by Box2112** [Templarian/MaterialDesign#5524] opened 2020-09-25 04:43 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same as other light icons except for different type

## Examples

Include any example images so we know what the icon should look like.
![chandelier](https://user-images.githubusercontent.com/46469423/94227290-62915100-ff3d-11ea-812a-186aca33b2d6.png)

**Comment by Templarian** [comment] 2020-09-25 04:44
Duplicate of #5301 Please use the search.

**Closed by Templarian** 2020-09-25 04:44 UTC
Labels: Icon Request
