### ISSUE TITLE
Lizard shape

### ISSUE THREAD

**Issue by jds11111** [Templarian/MaterialDesign#5403] opened 2020-08-04 21:04 UTC
I have:

- [X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I know that others have requested nature icons, such as those in unicode.  However, some would be easily recognized, like the shape of a lizard.  

## Examples

For example, look at [this one:](https://pngriver.com/wp-content/uploads/2017/12/download-lizard-PNG-transparent-images-transparent-backgrounds-PNGRIVER-COM-lizard-002.png)

**Comment by goyney** [comment] 2020-08-05 02:10
There's a lot of detail required here to make this work. This one will be a challenge.

**Comment by goyney** [comment] 2020-08-05 03:40
This is also a duplicate of #5153.

**Closed by goyney** 2020-08-05 03:40 UTC
Labels: Icon Request
