### ISSUE TITLE
An icon for https://dumdarac.com/

### ISSUE THREAD

**Issue by cachopawa** [Templarian/MaterialDesign#2730] opened 2018-01-08 09:07 UTC
An icon for https://dumdarac.com/
I think one like favicon will be cool
http://dumdarac.com/imgs/logo/logo_white.png

**Comment by GreenTurtwig** [comment] 2018-01-08 09:08
Duplicate of https://github.com/Templarian/MaterialDesign/issues/2728

**Comment by cachopawa** [comment] 2018-01-08 09:09
Why!? 😭

**Closed by GreenTurtwig** 2018-01-08 09:08 UTC
