### ISSUE TITLE
brush

### ISSUE THREAD

**Issue by leninjo** [Templarian/MaterialDesign#5313] opened 2020-07-10 20:57 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment] 2020-07-12 19:41
Can you fill in the issue template. We have a paint brush, so I assume this mean a hair brush or cosmetic brush.

**Comment by goyney** [comment] 2020-07-12 19:43
If this is for a hairbrush, it's a duplicate of https://github.com/Templarian/MaterialDesign/issues/3752.

**Closed** 2020-07-24 02:01 UTC
Labels: Consider Closing, Icon Request
