### ISSUE TITLE
`LaTeX'icon

### ISSUE THREAD

**Issue by allen5261** [Templarian/MaterialDesign#2297] opened 2017-07-30 05:41 UTC
code:
`<svg version="1.1"  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"y="0px" width="24px" height="24px" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
<g>
	<path style="fill-rule:evenodd;clip-rule:evenodd;" d="M12.065,15.537c0-0.07,0-0.129,0-0.208c0.125,0,0.244,0.004,0.363-0.001
		c0.21-0.008,0.272-0.064,0.294-0.26c0.005-0.05,0.005-0.1,0.005-0.149c0-1.388,0-2.775,0-4.163c0-0.36-0.045-0.405-0.421-0.42
		c-0.077-0.003-0.155,0-0.24,0c0-0.069,0-0.127,0-0.201c0.181,0,0.361,0,0.56,0c-0.01-0.102-0.013-0.189-0.026-0.275
		c-0.032-0.2-0.06-0.401-0.106-0.598c-0.083-0.356-0.334-0.556-0.706-0.588c-0.356-0.031-0.716-0.031-1.075-0.035
		c-0.141-0.001-0.189,0.057-0.199,0.193c-0.003,0.042-0.002,0.085-0.002,0.128c0,1.419,0,2.839,0,4.259c0,0.05,0,0.1,0.004,0.149
		c0.01,0.11,0.067,0.192,0.187,0.211c0.143,0.021,0.288,0.034,0.434,0.043c0.104,0.007,0.207,0.002,0.318,0.002
		c0,0.073,0,0.135,0,0.199c-0.814,0-1.621,0-2.437,0c0-0.062,0-0.123,0-0.199c0.102,0,0.201,0.005,0.301-0.001
		c0.148-0.01,0.298-0.021,0.445-0.042c0.122-0.018,0.188-0.096,0.191-0.216c0.002-0.057,0.007-0.113,0.007-0.171
		c0-1.405,0-2.81,0-4.215c0-0.324-0.021-0.351-0.36-0.348C9.302,8.633,9.002,8.64,8.705,8.669C8.272,8.71,8.044,8.906,7.953,9.314
		C7.898,9.564,7.876,9.82,7.84,10.074c-0.005,0.031-0.006,0.063-0.01,0.101c-0.048,0-0.09,0-0.146,0
		C7.729,9.596,7.775,9.02,7.822,8.435c1.605,0,3.205,0,4.817,0c0.046,0.561,0.091,1.123,0.138,1.694c1.17,0,2.329,0,3.501,0
		c0.068,0.587,0.135,1.165,0.202,1.751c-0.052,0-0.095,0-0.14,0c-0.038-0.217-0.066-0.436-0.117-0.649
		c-0.14-0.574-0.436-0.834-1.055-0.871c-0.549-0.032-1.1-0.022-1.649-0.022c-0.188,0-0.241,0.053-0.242,0.223
		c-0.003,0.676-0.001,1.352,0,2.027c0,0.007,0.005,0.013,0.01,0.025c0.011,0.003,0.024,0.01,0.038,0.01
		c0.313-0.001,0.628-0.002,0.942-0.007c0.067-0.001,0.135-0.013,0.2-0.027c0.25-0.056,0.388-0.197,0.421-0.44
		c0.02-0.144,0.027-0.289,0.041-0.442c0.041,0,0.083,0,0.134,0c0,0.68,0,1.361,0,2.042c-0.137,0.029-0.14,0.026-0.146-0.1
		c-0.006-0.113-0.013-0.228-0.028-0.34c-0.035-0.239-0.168-0.378-0.413-0.435c-0.076-0.018-0.155-0.033-0.232-0.034
		c-0.317-0.004-0.635-0.002-0.968-0.002c0,0.042,0,0.079,0,0.117c0,0.694,0,1.387,0,2.081c0,0.029-0.001,0.058,0.001,0.086
		c0.012,0.16,0.051,0.211,0.217,0.21c0.591-0.002,1.184,0.007,1.772-0.028c0.571-0.034,0.949-0.334,1.099-0.869
		c0.056-0.198,0.096-0.4,0.145-0.611c-0.197,0-0.375,0-0.561,0c0-0.063,0-0.124,0-0.164c0.2-0.053,0.395-0.091,0.577-0.155
		c0.193-0.068,0.343-0.203,0.46-0.364c0.474-0.653,0.944-1.308,1.419-1.96c0.035-0.049,0.036-0.082,0.001-0.131
		c-0.522-0.725-1.044-1.451-1.563-2.176c-0.111-0.154-0.259-0.243-0.458-0.251c-0.107-0.005-0.216-0.013-0.331-0.019
		c0-0.061,0-0.12,0-0.187c0.591,0,1.179,0,1.773,0c0,0.06,0,0.119,0,0.177c-0.083,0.027-0.172,0.045-0.249,0.084
		c-0.113,0.058-0.139,0.144-0.07,0.239c0.415,0.583,0.833,1.165,1.256,1.755c0.024-0.029,0.044-0.048,0.061-0.07
		c0.353-0.486,0.707-0.971,1.056-1.459c0.044-0.062,0.077-0.141,0.086-0.214c0.016-0.145-0.073-0.253-0.219-0.297
		c-0.035-0.01-0.071-0.019-0.104-0.028c0-0.066,0-0.125,0-0.188c0.51,0,1.014,0,1.523,0c0,0.064,0,0.123,0,0.184
		c-0.125,0.019-0.248,0.03-0.367,0.057c-0.281,0.064-0.5,0.218-0.665,0.442c-0.403,0.552-0.805,1.105-1.209,1.657
		c-0.036,0.048-0.038,0.083-0.002,0.132c0.601,0.829,1.2,1.659,1.798,2.489c0.107,0.149,0.25,0.231,0.438,0.241
		c0.107,0.005,0.216,0.01,0.33,0.015c0,0.067,0,0.129,0,0.193c-0.588,0-1.17,0-1.764,0c0-0.059,0-0.119,0-0.183
		c0.076-0.025,0.161-0.043,0.235-0.079c0.124-0.06,0.148-0.149,0.073-0.254c-0.482-0.673-0.968-1.344-1.452-2.016
		c-0.004-0.006-0.011-0.009-0.023-0.02c-0.018,0.021-0.038,0.039-0.054,0.061c-0.427,0.589-0.853,1.178-1.279,1.767
		c-0.074,0.103-0.112,0.209-0.062,0.331c0.053,0.128,0.168,0.173,0.304,0.197c0,0.064,0,0.127,0,0.188c-0.198,0-0.396,0-0.592,0
		c-0.222-0.001-0.222-0.002-0.252,0.209c-0.069,0.475-0.14,0.95-0.21,1.426c-0.004,0.027-0.013,0.055-0.021,0.088
		C14.951,15.537,13.513,15.537,12.065,15.537z"/>
	<path style="fill-rule:evenodd;clip-rule:evenodd;" d="M2.516,8.409c0.676,0,1.352,0,2.034,0c0,0.062,0,0.121,0,0.197
		c-0.083,0-0.168-0.004-0.251,0.001c-0.131,0.009-0.262,0.018-0.39,0.038c-0.12,0.019-0.18,0.095-0.184,0.21
		C3.725,8.901,3.723,8.947,3.723,8.993c0,1.438,0,2.875,0,4.312c0,0.29,0.028,0.319,0.333,0.317c0.358-0.002,0.72,0.013,1.076-0.021
		c0.652-0.06,1.044-0.393,1.196-0.998c0.063-0.251,0.092-0.51,0.138-0.775c0.031,0,0.074,0,0.133,0
		c-0.066,0.665-0.132,1.328-0.198,1.996c-1.299,0-2.589,0-3.89,0c0-0.063,0-0.124,0-0.207c0.111,0,0.222,0.004,0.332,0
		c0.256-0.01,0.325-0.076,0.325-0.32c0.001-1.455,0.001-2.91,0-4.365c0-0.243-0.058-0.3-0.313-0.317
		C2.746,8.608,2.638,8.615,2.516,8.615C2.516,8.54,2.516,8.477,2.516,8.409z"/>
	<path style="fill-rule:evenodd;clip-rule:evenodd;" d="M8.528,12.938c0,0.063,0,0.11,0,0.164c-0.489,0-0.974,0-1.465,0
		c0-0.053,0-0.101,0-0.153c0.09-0.012,0.18-0.018,0.265-0.037c0.146-0.032,0.188-0.111,0.137-0.246
		c-0.13-0.352-0.262-0.703-0.39-1.056c-0.024-0.068-0.053-0.102-0.14-0.101c-0.542,0.005-1.085,0.004-1.628,0.001
		c-0.072,0-0.103,0.022-0.126,0.087c-0.1,0.279-0.206,0.556-0.31,0.834c-0.113,0.305-0.03,0.443,0.312,0.513
		c0,0.049,0,0.101,0,0.157c-0.378,0-0.754,0-1.137,0c0-0.051,0-0.099,0-0.149c0.009-0.004,0.018-0.012,0.027-0.012
		c0.341-0.013,0.533-0.192,0.642-0.489c0.475-1.291,0.956-2.58,1.435-3.869c0.011-0.03,0.016-0.067,0.036-0.089
		C6.214,8.464,6.255,8.43,6.289,8.431c0.033,0,0.072,0.037,0.099,0.066C6.408,8.52,6.413,8.556,6.425,8.585
		c0.497,1.34,0.994,2.68,1.491,4.02c0.107,0.291,0.162,0.327,0.489,0.333C8.442,12.938,8.479,12.938,8.528,12.938z M6.126,9.06
		c-0.288,0.775-0.565,1.52-0.846,2.271c0.568,0,1.122,0,1.691,0C6.69,10.576,6.414,9.832,6.126,9.06z"/>
</g>
</svg>`

**Comment by Templarian** [comment] 2017-07-30 20:44
Duplicate of #1614

@allen5261 Can you attach a zip file with the SVG.

**Closed by Templarian** 2017-07-30 20:44 UTC

**Comment by allen5261** [comment] 2017-07-31 06:53
The zip is here：
[LaTeX.zip](https://github.com/Templarian/MaterialDesign/files/1186627/LaTeX.zip)
