### ISSUE TITLE
Overlay smaller icon on larger parent

### ISSUE THREAD

**Issue by kentonbmax** [Templarian/MaterialDesign#1170] opened 2016-04-14 12:36 UTC
Have you guys considered the ability to take a larger parent icon, set the font size, color and then lay a smaller one on top of it, also with color and font set differently. You could break up location of the smaller icon location on the parent into 7 locations. center and then combine right and left with top, center, bottom. This would allow someone to take say an existing icon like a factory or a wrench and apply a smaller heart or +/- to it. The possibilities would be nearing endless. This might be a new icon directive for angular material. The child icons should be constricted to those less complex, +/-, heart, check, maybe person, maybe solid triangle or octagon.

**Comment by Templarian** [comment] 2016-04-14 18:19
We've gotten this request before to mimic the functionality that font awesome provides for overlaying icons and have decided to not include this feature. Ideally developers can roll their own solution as they need it.

Please post on #245 your solution and we'll review it and see if we can get it added to the documentation for others to use.

Duplicate of #245.

**Closed by Templarian** 2016-04-14 18:19 UTC
