### ISSUE TITLE
Tank

### ISSUE THREAD

**Issue by samnup** [Templarian/MaterialDesign#3032] opened 2018-04-09 20:45 UTC
It would be nice if a tank icon is included!

**Comment by PeterShaggyNoble** [comment] 2018-04-10 09:51
If the vehicle then this is a dupe of #365

**Comment by Templarian** [comment] 2018-04-10 20:03
Or the shirt type? We have crew/v-neck. 😆 English is awesome.

**Closed** 2018-07-11 17:58 UTC
Labels: Consider Closing :door:, Icon Request :pencil2:, Needs More Information :information_source:
