### ISSUE TITLE
fan-speed-5

### ISSUE THREAD

**Issue by toughvj** [Templarian/MaterialDesign#7201] opened 2023-08-08 12:51 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I need this icon in my home assistant environment

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/31914712/1cd86614-ebdb-4918-aa70-fe1b2760c500)

### Upload the icon source.

[fan-speed-5.svg.zip](https://github.com/Templarian/MaterialDesign/files/12291433/fan-speed-5.svg.zip)

**Comment by mririgoyen** [comment] 2023-08-08 14:08
Duplicate of #6987, #6780, #6832, #6833...

**Closed by mririgoyen** 2023-08-08 14:08 UTC
Labels: Icon Request, Contribution
