### ISSUE TITLE
waterfall

### ISSUE THREAD

**Issue by farsonic** [Templarian/MaterialDesign#5611] opened 2020-10-31 23:38 UTC
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For me this would be used for a water feature in my pool automation that is a waterfall. This could be used for other similar use cases in pools, gardens etc. The existing icons such as sprinkler or fountain are not ideally suitable. 

## Examples

Just thinking of water cascading over a simple object

**Comment by goyney** [comment] 2021-09-04 04:29
Duplicate of #2249.

**Closed by goyney** 2021-09-04 04:29 UTC
Labels: Icon Request
