### ISSUE TITLE
Google Home / Nest Hub, Home Max & Home Mini smart speaker icons.

### ISSUE THREAD

**Issue by Mancerrss** [Templarian/MaterialDesign#5505] opened 2020-09-22 12:37 UTC
- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This isn't **brand icon request.** These are device icons. I know Google has an official Google Home smart speaker icon, but I needed the other icons for Google Home Hub (now Nest Hub / Nest Hub Max), Home Mini & Home Max, for an audio output project / concept that I'm working on. I needed specific device icons so users would know if a certain audio output is passed to the other device, is playing on that device remotely, or view existing playback sessions.

## Examples

This is the official [Google Home smart speaker](https://materialdesignicons.com/icon/google-home) that Google shipped on Material Design Icons library. Please use this as reference / inspiration.

##Thanks

**Comment by goyney** [comment] 2020-09-22 13:33
Duplicate of #5279, #4521.

**Closed** 2020-09-22 18:11 UTC
Labels: Duplicate, Icon Request
