### ISSUE TITLE
New icon mdi:sprinkler-off

### ISSUE THREAD

**Issue by hollosipeti** [Templarian/MaterialDesign#7423] opened 2024-04-16 08:19 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I couldn't find a sprinkler-off icon. I would like to use this.
![sprinkler-off](https://github.com/Templarian/MaterialDesign/assets/72294562/2641cfc6-0666-4c82-a9e0-d7515ddb99f2)
I made a sample.
I found a closed topic about this, but no concrete icon yet.

### Give us an example of what this icon might look like.

In my irrigation system, it would indicate the status of the turned off sprinkler.

**Comment by mririgoyen** [comment] 2024-04-23 14:37
Dupe of #5581.

**Closed by mririgoyen** 2024-04-23 14:37 UTC
Labels: Icon Request

**Comment by frieduser** [comment] 2024-06-18 17:09
I was able to create code here: [https://github.com/Templarian/MaterialDesign/issues/5881](url) but I dpn't how to create here in mdi database in order to have it available for all. thx
