### ISSUE TITLE
icon request: dog

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#3026] opened 2018-04-07 15:52 UTC
setting the motion sensors icons, there;s a definite need for a guard-dog ;-)

maybe Ive overlooked, but could only find cat...

So, please consider creating a mdi:dog..

![image](https://user-images.githubusercontent.com/33354141/38457113-79d476bc-3a8c-11e8-9251-64d71cee9554.png)
cheers,
Marius

**Comment by GreenTurtwig** [comment] 2018-04-07 15:54
Duplicate of #736
Please search before creating an issue. :cat2:

**Closed by GreenTurtwig** 2018-04-07 15:54 UTC
