### ISSUE TITLE
save & close

### ISSUE THREAD

**Issue by bladsolutions** [Templarian/MaterialDesign#6137] opened 2021-08-19 19:01 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Save and Close

### Give us an example of it's usage.

when I edit form in modal I need a button to save form and close modal

**Comment by goyney** [comment] 2021-08-19 19:23
Duplicate of #5924.

**Closed by goyney** 2021-08-19 19:23 UTC
Labels: Icon Request
