### ISSUE TITLE
hen icons please

### ISSUE THREAD

**Issue by r3npogi** [Templarian/MaterialDesign#7255] opened 2023-10-12 14:49 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have a chicken coop that i want to automate, there's no icon for live chickens (hens in particular) there's an icon for the drumstick (food) and eggs but that's it. thanks in advance

### Give us an example of what this icon might look like.

https://th.bing.com/th/id/OIP.moCBKM0-t3tbOwcnczRRUwHaHa?pid=ImgDet&rs=1

**Comment by mririgoyen** [comment] 2023-10-17 13:09
Dupe of #3455.

**Closed by mririgoyen** 2023-10-17 13:09 UTC
Labels: Icon Request
