### ISSUE TITLE
Improve chart-bar

### ISSUE THREAD

**Issue by RodrigolcSouza** [Templarian/MaterialDesign#3400] opened 2018-08-15 19:22 UTC
I would like to improve the chart-bar or create a chart-bar-2. I believe the actual chart-bar is simple and we can update with stylization. Here an example:

![chart-bar](https://user-images.githubusercontent.com/38769285/44168315-499feb80-a0a7-11e8-9000-6e3db0ef719e.png)

[chart-bar-svg.zip](https://github.com/Templarian/MaterialDesign/files/2291424/chart-bar-svg.zip)

**Comment by Templarian** [comment] 2018-08-15 20:02
We're afraid that may be confused with `chart-histogram`. The reason we separated the  lines is to prevent this confusion with histogram at smaller sizes.

Closing this issue as it's more of a duplicate of `chart-histogram`.

**Closed by Templarian** 2018-08-15 20:02 UTC
