### ISSUE TITLE
restaurant

### ISSUE THREAD

**Issue by dgproductions88** [Templarian/MaterialDesign#3319] opened 2018-07-11 11:05 UTC
I know there was a 'restaurant' icon request but i need the one is in material labeled as 'restaurant' no 'silverware'.

Thanks and regards

**Comment by PerthTotty** [comment] 2018-07-11 13:44
could you add a screenshot of that icon?

**Comment by goyney** [comment] 2018-07-11 14:36
https://material.io/tools/icons/?search=res&icon=restaurant&style=baseline

**Comment by PeterShaggyNoble** [comment] 2018-07-12 09:18
If that is the icon being requested then this is a duplicate of #1802.

**Comment by Templarian** [comment] 2018-07-15 02:43
Added and aliased.

**Closed by Templarian** 2018-07-15 02:43 UTC
Labels: Icon Request :pencil2:, Stock Google Icon :squirrel:
