### ISSUE TITLE
cart-minus

### ISSUE THREAD

**Issue by SantiagoGilDH** [Templarian/MaterialDesign#2311] opened 2017-08-04 19:09 UTC
Like cart plus but with a minus symbol

**Comment by augustin32** [comment] 2017-08-05 11:07
[cart-minus.zip](https://github.com/Templarian/MaterialDesign/files/1202320/cart-minus.zip)

**Comment by goyney** [comment] 2018-11-25 05:57
Duplicate of #775.

**Closed** 2018-11-25 05:57 UTC
Labels: Contribution :heavy_check_mark:, Icon Request :pencil2:
