### ISSUE TITLE
Cryptocurrencies

### ISSUE THREAD

**Issue by adrianTNT** [Templarian/MaterialDesign#2503] opened 2017-10-10 11:06 UTC
Not sure how suggestions work but ...
Is it possible to get icons like PayPal and cryptocurrencies like Bitcoin and others ?

**Comment by JamesCoyle** [comment] 2017-10-10 11:09
Do a search of the site and the issues...

**Comment by GreenTurtwig** [comment] 2017-10-10 11:14
PayPal is a duplicate of: https://github.com/Templarian/MaterialDesign/issues/297
We already have Bitcoin and Ethereum.
[![](https://materialdesignicons.com/icon/currency-btc)](https://materialdesignicons.com/icon/currency-btc)[![](
https://materialdesignicons.com/icon/currency-eth)](https://materialdesignicons.com/icon/currency-eth)
Do you have any other a cryptocurrencies in mind?

**Comment by PeterShaggyNoble** [comment] 2017-10-10 11:29
`currency-eth` could probably do with being aliased with its full name.

**Comment by adrianTNT** [comment] 2017-10-10 12:03
Ooops, I did a search in list for "bitcoin" but there is an existent icon "btc", my bad. 
It was the btc that I needed most and paypal (that I see above it has a request).
Thank you all.

**Comment by JapanYoshi** [comment] 2017-10-10 12:17
This is how I felt reading *yet another* PayPal request (before realizing the full currency name alias problem).
![Uploading Cuphead-Journalist.png…]()

**Comment by PeterShaggyNoble** [comment] 2017-10-10 13:15
Strange, `currency-btc` is aliased as `bitcoin` so it should have shown up in your search.

**Comment by adrianTNT** [comment] 2017-10-11 16:24
@PeterShaggyNoble yes, unless you search by CTRL+F in preview.html from downloaded zip file :)

**Comment by PeterShaggyNoble** [comment] 2017-10-11 16:28
@adrianTNT, you might find [this](https://petershaggynoble.github.io/MDI-Sandbox/) of use, so.

**Comment by volrath911** [comment] 2017-10-11 20:15
any MDI icons on other crypto currencies? Ripple maybe, QTUM? others?

**Comment by JamesCoyle** [comment] 2017-10-11 20:25
We're only gonna consider accepting currencies that have over 100,000 transactions per day. Anything lower than that is way too niche at the moment.

**Comment by MrGrigri** [comment] 2017-10-11 20:54
That's a good benchmark for now.

**Comment by JamesCoyle** [comment] 2017-10-11 20:57
Unique transactions as tracked here: https://bitinfocharts.com

**Comment by GreenTurtwig** [comment] 2017-10-16 09:35
`currency-eth` has been given the alias `ethereum`.

**Closed by GreenTurtwig** 2017-10-16 09:35 UTC
Labels: Alias Icon, Icon Request
