### ISSUE TITLE
Calendar-Minus

### ISSUE THREAD

**Issue by sikrinick** [Templarian/MaterialDesign#2314] opened 2017-08-06 13:27 UTC
Vector drawable code for such icon:
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="24dp"
    android:width="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path android:fillColor="#000" android:pathData="M19,19V7H5V19H19M16,1H18V3H19A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5C3.89,21 3,20.1 3,19V5C3,3.89 3.89,3 5,3H6V1H8V3H16V1M11,9HV12H16V14H13VH11V14H8V12H11V9Z" />
</vector>
```

**Comment by PeterShaggyNoble** [comment] 2018-03-08 17:09
Duplicate of #1974

**Closed by PeterShaggyNoble** 2018-03-08 17:09 UTC
Labels: Icon Request :pencil2:
