### ISSUE TITLE
BLANK ICON

### ISSUE THREAD

**Issue by robertbrower** [Templarian/MaterialDesign#1167] opened 2016-04-13 22:38 UTC
I need an icon that is blank so I can keep my UL treeview looking good. Can someone please add?

**Comment by PeterShaggyNoble** [comment] 2016-04-13 22:40
Can you not just use padding or an empty element?

**Comment by Templarian** [comment] 2016-04-13 22:41
I agree we should add one. Duplicate of #352.

**Closed by Templarian** 2016-04-13 22:41 UTC
