### ISSUE TITLE
3 states window: Open, Close, Hopper

### ISSUE THREAD

**Issue by gasparirob** [Templarian/MaterialDesign#7245] opened 2023-09-24 11:53 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I will use it in Home Assistant to identify status of all my windows: Open, Close, Hopper.
These 3 cases are repeated for:
2 side full height window (only right side has hopper)
1 side full height window (with hopper)
2 side middle height window (only right side has hopper)
1 side middle height window (with hopper)

### Give us an example of what this icon might look like.

2 side full height opened window:
![PXL_20230924_133003938 MV](https://github.com/Templarian/MaterialDesign/assets/4035919/10e23467-d503-4888-9db9-4bdde64dca62)

2 side full height closed window:
![PXL_20230924_133024911 MV](https://github.com/Templarian/MaterialDesign/assets/4035919/30a1cbe8-00a0-435d-a1ea-6db25f4cf41d)

2 side full height hopper window:
![PXL_20230924_133040425 MV](https://github.com/Templarian/MaterialDesign/assets/4035919/faa78fb6-9d4f-47c7-a0e3-ec6b02bbc94d)

1 side full height window:
![PXL_20230924_133457661](https://github.com/Templarian/MaterialDesign/assets/4035919/a953502d-ff90-4035-952e-3ea65d749c99)

2 side middle height window:
![PXL_20230924_133733919 MV](https://github.com/Templarian/MaterialDesign/assets/4035919/3f91eb2f-210f-461e-bdbe-6de967a074a1)

1 side middle height
![PXL_20230924_133627771 MV](https://github.com/Templarian/MaterialDesign/assets/4035919/2910dce1-d04f-4490-aa18-4e1666981f91)
ght window:

**Comment by mririgoyen** [comment] 2023-09-27 20:58
Duplicate of #7064, #6682, and more. We cannot add these styles because they break Material Guidelines, specifically prohibiting icons that show perspective.

**Closed by mririgoyen** 2023-09-27 20:58 UTC
Labels: Icon Request
