### ISSUE TITLE
factory-smoke / factory-on

### ISSUE THREAD

**Issue by metbril** [Templarian/MaterialDesign#1941] opened 2017-03-19 09:05 UTC
I would like to suggest an alternative icon for the current factory icon. This would be the current icon, with smoke coming from the chimney. I intend to use this in Home Assistant for a pollution or air quality indicator.

Suggested filename: `factory-smoke` or `factory-on`.

## Current icon:
https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/factory.svg

## Example:

![](https://image.flaticon.com/icons/svg/360/360350.svg)

**Comment by PeterShaggyNoble** [comment] 2018-03-05 16:55
Possible duplicate of #1513?

**Comment by metbril** [comment] 2018-03-09 05:34
Not sure if it’s a duplicate but they are family. My use case is pollution.

**Comment by CoDEmanX** [comment] 2018-03-14 22:11
In that case, it should depict a chimney / cooling tower + cloud I guess?

**Comment by MrGrigri** [comment] 2018-11-08 18:38
Closing because the `Consider Closing` label was added more than 10 days ago.

**Closed by MrGrigri** 2018-11-08 18:38 UTC
Labels: Consider Closing :door:, Home Assistant :house:, Icon Request :pencil2:

**Comment by PeterShaggyNoble** [comment] 2018-11-19 11:19
The icon requested in #1513 has since been added as `smog`.
