### ISSUE TITLE
placeholder icon / empty icon / blank icon / space icon

### ISSUE THREAD

**Issue by nuriakman** [Templarian/MaterialDesign#5818] opened 2021-01-25 18:51 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to set space for each icons on page. Since related icon comes in their space I want to use this placeholder (no icon).

This icon just holds space. NOTHING on it. just transparent/blank area. 

Think this icon like SPACE BAR CHARACTER. Nothing on it, just occupies space.

**Comment by goyney** [comment] 2021-01-25 18:57
Duplicate of #5702 #5130 #2858 #1167 #501 #352...

**Closed by goyney** 2021-01-25 18:57 UTC
Labels: Icon Request
