### ISSUE TITLE
Unicorn

### ISSUE THREAD

**Issue by johbom** [Templarian/MaterialDesign#4625] opened 2019-11-21 12:15 UTC
My daughter really needs a unicorn for her playlist. My son loves the pirate! I think it would be Nice with a unicorn in ”profile” 

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment] 2019-11-21 13:11
Duplicate of #2739. Please search, as you indicated you did in checkbox #1.

**Closed by goyney** 2019-11-21 13:11 UTC
Labels: Icon Request
