### ISSUE TITLE
Door & Window half open (ajar, cracked)

### ISSUE THREAD

**Issue by jhein05** [Templarian/MaterialDesign#6184] opened 2021-09-09 03:24 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

European windows mostly have three states: Open, closed and "cracked open" (slightly tilted inwards) to let some air in, while they still prevent a person to climb in. US sliding windows and sliding doors in general sometimes can also be opened a "little bit" and locked in that position, so that you can't push them open further.

I saw the discussions about garage-ajar and I do agree, that for a garage door, half-open is not a normal state to be in. For (slinding) doors and especially windows it is a normal state, so that the door-alert icon is not really usable for those cases.

### Give us an example of what this icon might look like.

Like the existing icons, but half open. I do realize that that might be a bit challenging :)

**Comment by goyney** [comment] 2021-09-09 14:29
Duplicate of https://github.com/Templarian/MaterialDesign/issues/5923, https://github.com/Templarian/MaterialDesign/issues/4770.

In short, we cannot do anything with perspective, so anything tilt in out or open isn't possible.

In regards to a middle state between `window-open` and `window-closed`, we're literally talking about a difference of 5dp, which is not a lot of room to make something unique and discernible at native resolution.

I'll lean back on what I often say... that icons are meant to be contextual, not absolute. In some cases, it's easy to be literal with an icon and in others it is not. This is a "not" case, so unless someone has some new unique idea to make this happen, it's just not.

Thank you for your suggestion, but for now we're going to close and reject this request again.

**Closed by goyney** 2021-09-09 14:29 UTC
Labels: Icon Request

**Comment by jhein05** [comment] 2021-09-09 16:09
Understandable. In all fairness, I did search for similar issues, but only using the words ajar and cracked. Tilt(ed) didn't cross my mind until I started writing and thought about EU windows. Sorry for the unnecessary extra work.
