### ISSUE TITLE
Rock climbing icon

### ISSUE THREAD

**Issue by alexeigs** [Templarian/MaterialDesign#4829] opened 2020-02-03 10:53 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

An icon for "climbing" or "rock climbing". It's a widely spread activity and even an olympic sport.

## Examples

Emoji: https://emojipedia.org/person-climbing/
Icon: https://www.shutterstock.com/image-vector/climbing-bright-yellow-material-minimal-icon-794208268

**Comment by goyney** [comment] 2020-02-03 14:37
Duplicate of https://github.com/Templarian/MaterialDesign/issues/3800.

**Closed by goyney** 2020-02-03 14:37 UTC
Labels: Icon Request

**Comment by alexeigs** [comment] 2020-02-03 15:41
@goyney Just wondering, how is this a duplicate of something like "sports equipment"? Or do you label this for internal organisation purposes?

**Comment by goyney** [comment] 2020-02-03 21:05
Sorry, we're inundated with all the breaking changes happening in 5.0 right now. That issue has a Google created icon for rock climbing that has yet to be added.

![image](https://user-images.githubusercontent.com/1015040/73690680-e6d95000-469e-11ea-8afa-b6129d96d77e.png)

So, your request will be address there. Hope that clarifies!
