### ISSUE TITLE
account-lock

### ISSUE THREAD

**Issue by msayanece** [Templarian/MaterialDesign#2356] opened 2017-08-28 11:00 UTC

**Comment by msayanece** [comment] 2017-08-29 05:21
should be like this...

![](https://image.freepik.com/free-icon/data-privacy_318-32777.jpg)

**Comment by MrGrigri** [comment] 2017-08-29 14:08
Would `account-edit` work?

![account-edit](https://materialdesignicons.com/icon/account-edit)

**Comment by JamesCoyle** [comment] 2017-08-29 14:13
Thank you for adding examples to these. We also have one with a key: 
[![](https://materialdesignicons.com/icon/account-key)](https://materialdesignicons.com/icon/account-key)

**Comment by MrGrigri** [comment] 2017-08-31 02:52
Account with a shield is a duplicate of #1742

**Comment by msayanece** [comment] 2017-08-31 04:45
Thank you James, I have already checked this icon but man with a key is not what I want.  As you can see, the sample has three things,
1. A lock
2. one person
3. a file surrounding the person

These three things I require as a single icon as I am searching for a Privacy and Policy icon

**Comment by msayanece** [comment] 2017-08-31 04:50
Thank you MrGrigri. I will check your icon with my team and let you know, if this icon can be a replacement of the required one.

**Comment by msayanece** [comment] 2017-08-31 04:55
Sorry MrGrigri, your icon becomes distorted whenever I want to convert this to vector drawables.

**Comment by goyney** [comment] 2019-08-15 01:36
Couple options:
![image](https://user-images.githubusercontent.com/1015040/63067110-6ac63280-bedb-11e9-8e11-85785c94cdb3.png)
![image](https://user-images.githubusercontent.com/1015040/63067116-70bc1380-bedb-11e9-9592-eaa8983181a3.png)
![image](https://user-images.githubusercontent.com/1015040/63067129-787bb800-bedb-11e9-838a-185d0158b85a.png)
![image](https://user-images.githubusercontent.com/1015040/63067136-7fa2c600-bedb-11e9-8c31-5ec636eb4cd2.png)

[account-lock.zip](https://github.com/Templarian/MaterialDesign/files/3503976/account-lock.zip)

**Comment by msayanece** [comment] 2019-08-16 09:26
Thanks for the icons @goyney

**Comment by goyney** [comment] 2019-08-16 09:35
We will close the issue once the icons have been added.

**Comment by CoDEmanX** [comment] 2019-08-17 06:57
Modifier in the bottom right corner would be my preference. I don't see a difference in meaning based on the lock placement.

**Comment by goyney** [comment] 2019-08-18 18:24
Most of our `account` modifiers are on the side, not in the bottom corner. Want a few more contributors to weigh in before making the final decision on this.

**Comment by JamesCoyle** [comment] 2019-08-18 18:25
I prefer bottom right. Having it to the side offers no benefit IMO.

**Comment by goyney** [comment] 2019-08-20 01:35
[![account-lock](https://materialdesignicons.com/icon/account-lock)](https://materialdesignicons.com/icon/account-lock)[![account-lock-outline](https://materialdesignicons.com/icon/account-lock-outline)](https://materialdesignicons.com/icon/account-lock-outline)

**Closed by goyney** 2019-08-20 01:35 UTC
Labels: Contribution, Icon Request
