### ISSUE TITLE
Bird icon

### ISSUE THREAD

**Issue by shuetrim** [Templarian/MaterialDesign#1482] opened 2016-09-01 21:44 UTC
It would be great to have a "generic" bird icon.

**Comment by alexefremo** [comment] 2016-09-02 10:41
The easiest one. If you think of more complex - i'll make another

![ic_bird_black_24px](https://cloud.githubusercontent.com/assets/3408199/18201449/9f351936-7123-11e6-89bf-a2d86af8f8fc.png)
![ic_bird_black_48px](https://cloud.githubusercontent.com/assets/3408199/18201448/9f3271c2-7123-11e6-90c6-2d84706ae08b.png)

**Comment by GreenTurtwig** [comment] 2016-09-02 11:43
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/895 :-P

**Comment by shuetrim** [comment] 2016-09-02 22:23
Seriously - that is the first design I thought of (but do not have the tech to create).  The only limitation is that it looks a little light weight when used as an android icon, compared to the "volume" of other icons used in a similar context.  That said, I will be using it or a successor in tab bars for [Gaia Guide](http://gaiaguide.info/) bird mobile apps.

**Closed** 2016-10-20 05:58 UTC
Labels: Duplicate
