### ISSUE TITLE
threema

### ISSUE THREAD

**Issue by PerthTotty** [Templarian/MaterialDesign#3305] opened 2018-07-05 12:19 UTC
threema IM

![threema](https://user-images.githubusercontent.com/40835272/42322852-471521e6-805e-11e8-99e9-6496ee151c0d.png)
[threema.zip](https://github.com/Templarian/MaterialDesign/files/2166503/threema.zip)

**Comment by GreenTurtwig** [comment] 2018-07-05 12:46
Duplicate of https://github.com/Templarian/MaterialDesign/issues/3224
Please do a search before creating an issue. 🦑

**Closed by GreenTurtwig** 2018-07-05 12:46 UTC

**Comment by PerthTotty** [comment] 2018-07-05 12:51
Sorry

**Comment by GreenTurtwig** [comment] 2018-07-06 07:59
No worries. :-)
