### ISSUE TITLE
Ligatures support

### ISSUE THREAD

**Issue by un33k** [Templarian/MaterialDesign#1331] opened 2016-07-01 23:08 UTC
Trying to use the icons with angular-material2 the simple way which is `<md-icon>mdi-menu</md-icon>` and it won't work.  However, `<md-icon>menu</md-icon>` works with official Google material icons.  The error is about `ligatures support`.  Any insight into how to move forward from here?

**Comment by Templarian** [comment] 2016-07-01 23:15
Duplicate of #1013.

We will probably not be adding ligature support. If this is a required feature I would suggest staying with the official icon set provided by Google. I don't want to say it will never happen, but it is very low priority.

For now you can always use the class based approach documented in the getting started.

**Closed by Templarian** 2016-07-01 23:15 UTC

**Comment by un33k** [comment] 2016-07-01 23:16
Thx.
