### ISSUE TITLE
Recessed Lighting

### ISSUE THREAD

**Issue by etchings13** [Templarian/MaterialDesign#5303] opened 2020-07-09 08:27 UTC
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![recessed_lighting](https://user-images.githubusercontent.com/1736287/87016139-8c7f7680-c18b-11ea-88d8-3cc7920dc68c.png)

## Zip Download

[recessed_lighting.zip](https://github.com/Templarian/MaterialDesign/files/4895452/recessed_lighting.zip)

**Comment by goyney** [comment] 2020-07-14 03:11
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/1826. Also note that we cannot add icons that show perspective, so the proposed contribution cannot be considered.

**Closed by goyney** 2020-07-14 03:11 UTC
Labels: Contribution, Icon Request
