### ISSUE TITLE
recessed-lights

### ISSUE THREAD

**Issue by tom-greene** [Templarian/MaterialDesign#4146] opened 2019-05-16 14:39 UTC
I found an icon I liked by searching and created an SVG for it. Hoping it can be used by the default icon set. 
[recessed-light.svg.gz](https://github.com/Templarian/MaterialDesign/files/3187580/recessed-light.svg.gz)

**Comment by goyney** [comment] 2019-05-16 14:41
Duplicate of #1826. Could you please post your suggested icon there?

Also, you can use http://dev.materialdesignicons.com/contribute/github to generate a preview of it for your post.

**Closed by goyney** 2019-05-16 14:41 UTC
