### ISSUE TITLE
Clenched Fist

### ISSUE THREAD

**Issue by mikechoch** [Templarian/MaterialDesign#3102] opened 2018-04-22 22:18 UTC
Here is an example of the clenched fist I made

<img width="256" alt="clenched_fist" src="https://user-images.githubusercontent.com/24537305/39100491-7e83adee-4659-11e8-8ea9-208cdd31b346.png">

[clenched_fist.zip](https://github.com/Templarian/MaterialDesign/files/1936165/clenched_fist.zip)

**Comment by PeterShaggyNoble** [comment] 2018-04-23 08:09
Thanks for the request. However this is a duplicate of #2717, please give that issue a 👍 

Also, please remember to search existing icons and issues before posting a request.

**Closed by PeterShaggyNoble** 2018-04-23 08:09 UTC
Labels: Icon Request :pencil2:
