### ISSUE TITLE
water-current

### ISSUE THREAD

**Issue by adlaws** [Templarian/MaterialDesign#5896] opened 2021-03-19 09:47 UTC
Howdy guys,

Here's my suggestion/contribution for an icon to indicate a water current or flowing water.

May be used to indicate flow of water or liquid in a body of water (river, ocean, etc) or in other situations such as a pipe or drainage.

In my particular case the intention is to use it in an environmental settings dialog in the section for configuring the direction and speed of ocean and/or river currents (for setting up the world conditions in a simulated training environment).

It's a slight modification of the existing `waves` icon to try to be consistent with the existing look and feel. 

I've removed one of the waves to give a bit more visual space for the arrows indicating flow, and exaggerated the wave height slightly to try to follow the basic visual appearance of beach and water safety signs for strong currents and rip tides.

Reference images can be found with a Google image search for beach and water safety signs:

https://www.google.com/search?&tbm=isch&q=strong+current+sign

I have:

- [*] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [*] Searched open issues to make sure there isn't a request for this icon.
- [*] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1201371/111759669-cf781900-88d8-11eb-9027-f0183f990fb6.png)

## Zip Download

[water-current.zip](https://github.com/Templarian/MaterialDesign/files/6170083/water-current.zip)

**Comment by goyney** [comment] 2021-09-02 02:08
Duplicate of #2812.

**Closed by goyney** 2021-09-02 02:08 UTC
Labels: Icon Request, Contribution
