### ISSUE TITLE
battery-saving

### ISSUE THREAD

**Issue by WofWca** [Templarian/MaterialDesign#3843] opened 2019-01-22 07:04 UTC
Or `power-saving` or `battery-leaf`.

![image](https://user-images.githubusercontent.com/39462442/51516559-d15a0500-1e52-11e9-82a8-5e8a71be8268.png)

Or maybe
![image](https://user-images.githubusercontent.com/39462442/51517652-66aac880-1e56-11e9-857b-b0c32341c487.png)

Or maybe both.

Related (duplicate?): #1717

**Comment by goyney** [comment] 2019-01-28 14:47
This is definitely a duplicate of #1717. Closing in favor of that issue.

**Closed by goyney** 2019-01-28 14:47 UTC
Labels: Icon Request :pencil2:
