### ISSUE TITLE
Icon request : printer off

### ISSUE THREAD

**Issue by othomas** [Templarian/MaterialDesign#2710] opened 2017-12-29 22:34 UTC
Today we have the icon "printer". Would be useful to have an icon "printer off" that would represent the printer with a cross line to indicate there is no printer connected or configured.
Like we have the icons "camera" and "camera-off" , or "visibility" and "visibility-off" etc.

**Comment by PeterShaggyNoble** [comment] 2017-12-29 22:42
Duplicate of #2526.

**Closed by PeterShaggyNoble** 2017-12-29 22:42 UTC
