### ISSUE TITLE
Door with Welcome Mat

### ISSUE THREAD

**Issue by TaylorTWBrown** [Templarian/MaterialDesign#2087] opened 2017-05-14 12:15 UTC

**Comment by jtscott** [comment] 2017-05-27 15:15
Doors and window icons with open/closed variants would be awesome!

**Comment by PeterShaggyNoble** [comment] 2017-05-29 10:33
- Open & closed window icons already exist (see below).
- Door is a dupe of #1822.
- Levaing this open as "door with wlecome mat" for now.

[![window-closed](https://materialdesignicons.com/icon/window-closed)](https://materialdesignicons.com/icon/window-closed) [![window-open](https://materialdesignicons.com/icon/window-open)](https://materialdesignicons.com/icon/window-open)

**Comment by Flitskikker** [comment] 2017-06-02 14:49
A suggestion:

![screen shot 2017-06-02 at 16 45 04](https://cloud.githubusercontent.com/assets/3516155/26730968/e1c51506-47b2-11e7-96ea-abae8ad22660.png)

![screen shot 2017-06-02 at 16 43 25](https://cloud.githubusercontent.com/assets/3516155/26730973/e589058a-47b2-11e7-9311-2db91c868fc3.png)

[door-mat.svg.zip](https://github.com/Templarian/MaterialDesign/files/1048019/door-mat.svg.zip)

**Comment by JamesCoyle** [comment] 2017-06-14 01:37
We can't use anything that implies dimensionality. TBH I don't think this is ever going to be possible to do effectively and don't really see the use of such an icon.

**Comment by Templarian** [comment] 2017-07-31 01:55
Agreed it's a little too specific.

**Closed by Templarian** 2017-07-31 01:55 UTC
Labels: Consider Closing, Icon Request
