### ISSUE TITLE
Examination Icon

### ISSUE THREAD

**Issue by mshafeeqkn** [Templarian/MaterialDesign#2505] opened 2017-10-10 16:55 UTC
Please add an icon for examination. Like a paper and pen or some thing like that

**Comment by PeterShaggyNoble** [comment] 2017-10-10 17:35
Duplicate of #2151.

**Closed by PeterShaggyNoble** 2017-10-10 17:35 UTC

**Comment by MrGrigri** [comment] 2017-10-10 17:46
The `format-list-checks` icon could work as well.

![format-list-checks](https://materialdesignicons.com/icon/format-list-checks)
