### ISSUE TITLE
lightbulb-group

### ISSUE THREAD

**Issue by user897943** [Templarian/MaterialDesign#2801] opened 2018-02-11 20:25 UTC
to represent a group of lights for home automation

**Comment by PeterShaggyNoble** [comment] 2018-02-12 16:27
Possible duplicate of #2772?

**Comment by rxritalin** [comment] 2018-02-18 11:27
Im pretty sure what he is suggesting is a group of light bulb like as follows. 
I was actually going to submit this already, so Ill do so here. 

![image](https://user-images.githubusercontent.com/3268460/36351136-1bfa84d0-1473-11e8-8c8b-25b52512b2d9.png)
![image](https://user-images.githubusercontent.com/3268460/36351154-3e416cca-1473-11e8-94e8-1c62d5c0293b.png)


[Light Group.zip](https://github.com/Templarian/MaterialDesign/files/1734641/Light.Group.zip)

**Comment by user897943** [comment] 2018-02-26 23:38
rxritalin described exactly what I mean.

**Comment by Templarian** [comment] 2019-07-16 04:59
This needs a different design. Maybe with just two bulbs. `light-bulb-multiple`.

**Comment by goyney** [comment] 2020-01-16 02:15
These were added in another issue with several variants (e.g. `off`, `outline`, etc.)
[![lightbulb-group](https://materialdesignicons.com/icon/lightbulb-group)](https://materialdesignicons.com/icon/lightbulb-group)

**Closed by goyney** 2020-01-16 02:15 UTC
Labels: Home Assistant, Icon Request
