### ISSUE TITLE
Pipe Valve

### ISSUE THREAD

**Issue by pmontgo33** [Templarian/MaterialDesign#2743] opened 2018-01-15 15:09 UTC
Looking for something that looks like one of these:

https://media.rs-online.com/t_large/F4992789-01.jpg

http://cdn.balkanplumbing.com/wp-content/uploads/Valve-handle-directions-II.jpg

**Comment by GreenTurtwig** [comment] 2018-01-16 14:22
Duplicate of https://github.com/Templarian/MaterialDesign/issues/1192

**Closed by GreenTurtwig** 2018-01-16 14:22 UTC
Labels: Icon Request
