### ISSUE TITLE
Fan Speed 4 & 5 icons

### ISSUE THREAD

**Issue by jeeftor** [Templarian/MaterialDesign#6987] opened 2023-02-26 18:14 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

My fireplace has 5 fan modes.... I'd like to have 5 speeds available :) 

### Give us an example of what this icon might look like.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/6491743/221428520-390198e4-a988-43b7-9bec-f0158cab6dff.png">

**Comment by mririgoyen** [comment] 2023-02-26 19:02
Duplicate of #6780, #6832, #6833 and others.

**Closed** 2023-02-26 19:02 UTC
Labels: Icon Request, Duplicate
