### ISSUE TITLE
Discount tag

### ISSUE THREAD

**Issue by tonny-sofijan** [Templarian/MaterialDesign#2120] opened 2017-05-28 08:52 UTC
I want to suggest new discount tag 
[discount_tag.pdf](https://github.com/Templarian/MaterialDesign/files/1034035/discount_tag.pdf)

![image](https://cloud.githubusercontent.com/assets/1309249/26587789/a2ea3ebc-4553-11e7-9ba3-a618074968f6.png)

**Comment by GreenTurtwig** [comment] 2017-06-01 13:45
We already have `ticket-percent`:
[![ticket-percent](https://materialdesignicons.com/icon/ticket-percent)](https://materialdesignicons.com/icon/ticket-percent)

Although this could be used as an alternative.

**Comment by PeterShaggyNoble** [comment] 2017-10-08 16:47
We also have the `sale` icon which might be of use.

[![](https://materialdesignicons.com/icon/sale)](https://materialdesignicons.com/icon/sale)

*I feel we might already have had a request for the `tag` icon with a percentage sign but I can't search for it on my phone.*

**Comment by goyney** [comment] 2018-11-20 22:24
This is a duplicate of #1497.

@tonny-sofijan Does `sale` fulfill your use case?

**Comment by PeterShaggyNoble** [comment] 2019-01-02 15:08
Closing due to lack of feedback. @tonny-sofijan, if `sale` doesn't suit your needs then please leave a comment and reopen this issue.

**Closed by PeterShaggyNoble** 2019-01-02 15:08 UTC
Labels: Icon Request :pencil2:, Needs More Information :information_source:
