### ISSUE TITLE
Garage Partial Open

### ISSUE THREAD

**Issue by knissdesign** [Templarian/MaterialDesign#6676] opened 2022-06-28 04:19 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Looking for an icon to represent a garage door in a partial-open "vented" position. I think this could possibly be as simple as "garage-alert" / "garage-alert-variant" without the exclamation point? Or the same door with overlayed heat squiggles or fan? Or open to other suggestions!

### Give us an example of what this icon might look like.

![Screenshot 2022-06-27 211311](https://user-images.githubusercontent.com/47086750/176091437-f8b7fd31-20c3-4340-905a-5e21340cebbc.png)
![Screenshot 2022-06-27 211311_2](https://user-images.githubusercontent.com/47086750/176091438-7caa336c-48f5-44b9-83e4-418053b756ef.png)
![Screenshot 2022-06-27 211311_3](https://user-images.githubusercontent.com/47086750/176091440-a3e67027-ca80-4ee1-8d2f-2aec9b1e9099.png)

**Comment by goyney** [comment] 2022-06-28 06:19
Duplicate of #6627.

**Closed** 2022-06-28 06:19 UTC
Labels: Icon Request, Duplicate
