### ISSUE TITLE
Door Open and Close Icons

### ISSUE THREAD

**Issue by skalavala** [Templarian/MaterialDesign#2059] opened 2017-05-02 20:00 UTC
Wouldn't it be wonderful to have two beautiful icons that represent **Door Open** and **Door Close** statuses? I see that there is a "glassdoor" icon, but no icon that represents real doors. Thx!

**Comment by GreenTurtwig** [comment] 2017-05-03 09:03
Duplicate of: https://github.com/Templarian/MaterialDesign/issues/1822
And the `glassdoor` is the icon for the website Glassdoor. :cat:

**Closed by GreenTurtwig** 2017-05-03 09:03 UTC
