### ISSUE TITLE
Missing Icons from Google

### ISSUE THREAD

**Issue by macx** [Templarian/MaterialDesign#909] opened 2015-12-16 10:27 UTC
As far I can see, there a missing a couple of icons from [Google Material Design Icons](https://design.google.com/icons/#ic_subject).

- Most of the [recently added 96 icons](https://plus.google.com/+AddyOsmani/posts/8rwSQAPsb9r)
- [subject](https://design.google.com/icons/#ic_subject)
- [inbox](https://design.google.com/icons/#ic_inbox) vs. [move_to_inbox](https://design.google.com/icons/#ic_move_to_inbox) (mdi is delivering the wrong icon)

I will extend this list, if I find more.

**Comment by CoDEmanX** [comment] 2015-12-16 11:32
Duplicate of #420

**Closed by CoDEmanX** 2015-12-16 11:32 UTC
Labels: Duplicate
