### ISSUE TITLE
Add chart-finance

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2644] opened 2017-11-29 18:24 UTC
As per my comment on #2602 and the request to make new issue:

Here is the icon Google uses on Inbox by Gmail to represent emails related to finance:

![image](https://user-images.githubusercontent.com/18021678/33391810-30c95c74-d508-11e7-8d8a-b4b8f9b92f97.png)

As seen on Inbox:

![screenshot 2017-11-29 at 1 23 22 pm](https://user-images.githubusercontent.com/18021678/33391905-7d6d4cc0-d508-11e7-94d1-5f5e1935269a.png)

Kind of like `chart-bar` and `chart-line` combined, a little different than the `finance` icon shown in the [extended sandbox](https://petershaggynoble.github.io/MDI-Sandbox/extended/).

**Comment by Templarian** [comment] 2017-11-30 05:37
Duplicate of #966.

Sorry for the run around. Closing and merging this discussion with the above issue. 😹

**Closed by Templarian** 2017-11-30 05:37 UTC
