### ISSUE TITLE
seal

### ISSUE THREAD

**Issue by wizmo2** [Templarian/MaterialDesign#5203] opened 2020-05-31 18:29 UTC
I have:

- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Searched open issues to make sure there isn't a request for this icon.
- [ x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

A small series of marine mammals

## Preview
![image](https://user-images.githubusercontent.com/11602094/83359854-0af62680-a34b-11ea-86e6-87305f3eded0.png)

## Zip Download
[seal.zip](https://github.com/Templarian/MaterialDesign/files/4708169/seal.zip)

**Comment by Templarian** [comment] 2020-05-31 19:44
Duplicate of #1539

**Closed by Templarian** 2020-05-31 19:44 UTC
Labels: Contribution, Icon Request
