### ISSUE TITLE
Stamp Icon

### ISSUE THREAD

**Issue by Dantalion** [Templarian/MaterialDesign#2736] opened 2018-01-10 11:03 UTC
Awesome work with the icons!

I would suggest a stamp icon. It would be useful f.e. for Apps used for sending paid e-mail services, or Apps used for ordering, delivering stamps.

Best Regards

Dan

**Comment by PeterShaggyNoble** [comment] 2018-01-10 11:05
If you're referring to a postage stamp then this is a duplicate of #418. If you're referring to a seal then see #621.

**Closed by PeterShaggyNoble** 2018-01-10 11:05 UTC
