### ISSUE TITLE
PID controller

### ISSUE THREAD

**Issue by antonverburg** [Templarian/MaterialDesign#7105] opened 2023-05-12 14:59 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I created an PID controller integration for homeassitant. As this needs an icon, I designed this one. Note that this will also fix issue #5488.

### Share a preview of your contribution.

![afbeelding](https://github.com/Templarian/MaterialDesign/assets/47820045/7070a359-d41c-4049-8859-5be8acc59c20)

### Upload the icon source.

[pid_controller.zip](https://github.com/Templarian/MaterialDesign/files/11465420/pid_controller.zip)

**Comment by mririgoyen** [comment] 2023-05-13 03:03
This is a duplicate of #5488. Please follow that issue for updates.

**Closed by mririgoyen** 2023-05-13 03:03 UTC
Labels: Icon Request, Contribution
