### ISSUE TITLE
Railway icons

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#6480] opened 2022-02-26 21:15 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

These are very thematic and industry icons related to the transportation of goods around the world. They will always be useful on sites with a railway theme and transport.

### Share a preview of your contribution.

<details>
<summary>cistern</summary>

![image](https://user-images.githubusercontent.com/44722574/155858969-f43ff433-7787-44a6-a8e7-b26593a7e7ff.png)
![image](https://user-images.githubusercontent.com/44722574/155858974-8cf29752-6108-41a9-93a1-d07c35b7a4bb.png)
![image](https://user-images.githubusercontent.com/44722574/155859133-e2d8d1d5-5ced-4aab-9879-c4eb515d313f.png)

</details>

<details>
<summary>covered-wagon</summary>

![image](https://user-images.githubusercontent.com/44722574/155859014-30058969-5c26-48e3-b9e4-cf8fd541b0c0.png)
![image](https://user-images.githubusercontent.com/44722574/155859027-d3946472-b467-4d82-ad6e-4bc08f58f55b.png)
![image](https://user-images.githubusercontent.com/44722574/155859141-ff78f09f-287f-4e1f-b359-44bbb770f92f.png)

</details>

<details>
<summary>dumpcar</summary>

![image](https://user-images.githubusercontent.com/44722574/155859033-48b38237-ef16-4490-9749-d84adc8dfe36.png)
![image](https://user-images.githubusercontent.com/44722574/155859038-43004b06-159f-44a4-8007-44c251910ca5.png)
![image](https://user-images.githubusercontent.com/44722574/155859148-01672076-e29a-4f00-b0e3-85a6ac376a19.png)

</details>

<details>
<summary>gondola-car</summary>

![image](https://user-images.githubusercontent.com/44722574/155859048-c51b20cc-6efd-44cb-83c2-c1163c78a81f.png)
![image](https://user-images.githubusercontent.com/44722574/155859053-bfb6023e-e694-45a2-9f7c-7358e0ba7cb3.png)
![image](https://user-images.githubusercontent.com/44722574/155859172-e6e7ead7-eff3-4615-91af-56777a2ffcca.png)

</details>

<details>
<summary>hopper</summary>

![image](https://user-images.githubusercontent.com/44722574/155859059-4e5a38e4-ef57-4df9-97bb-9276be374cad.png)
![image](https://user-images.githubusercontent.com/44722574/155859062-56219c37-dbcf-413e-bd57-8021231219ff.png)
![image](https://user-images.githubusercontent.com/44722574/155859355-a6c312f8-1bca-4fd6-9855-c887f87b1b68.png)

</details>

<details>
<summary>platform</summary>

![image](https://user-images.githubusercontent.com/44722574/155859066-db0281e7-ddde-403f-aba5-2d3b12fbb0d4.png)
![image](https://user-images.githubusercontent.com/44722574/155859071-285b66df-6a1f-433e-b843-4181c702f9c0.png)
![image](https://user-images.githubusercontent.com/44722574/155859077-84128653-18a3-4e24-b788-3c54db676095.png)
![image](https://user-images.githubusercontent.com/44722574/155859243-10fd121c-c8eb-44ee-93fb-e6c6aebd5fc7.png)

</details>

### Upload the icon source.

[wagons.zip](https://github.com/Templarian/MaterialDesign/files/8147529/wagons.zip)

**Comment by goyney** [comment] 2022-02-27 01:38
Dupe of #5543.

**Closed** 2022-02-27 01:38 UTC
Labels: Icon Request, Contribution
