### ISSUE TITLE
Generic valve

### ISSUE THREAD

**Issue by whc2001** [Templarian/MaterialDesign#4029] opened 2019-03-14 00:33 UTC
I need to show the state of an electric valve in an air duct in Home Assistant. I've already searched in MDI and only found icon for water valve ( #3842 #3071 ). It could be something like this (sorry for the mspaint job, I really don't know how to draw icon):
![valve](https://user-images.githubusercontent.com/16266909/54323328-27376780-45cf-11e9-923b-9ab25dfb742a.png)

**Comment by goyney** [comment] 2019-03-14 00:48
Duplicate of #3842.

**Closed by goyney** 2019-03-14 00:48 UTC
