### ISSUE TITLE
Fluorescent Ceiling Fixture

### ISSUE THREAD

**Issue by arkansas-coder** [Templarian/MaterialDesign#4944] opened 2020-03-04 14:32 UTC
I have:

- [ X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
This would be used to identify ceiling fluorescent lights, ideally in two variants: one on; and one off.

## Examples
I've had a difficult time finding any examples. The closest one is the first item in row five:
[https://www.istockphoto.com/vector/lighting-fixtures-and-equipment-icons-gm1043644776-279355437]
This example may be overly complex:
[https://www.iconfinder.com/icons/4465481/fluorescent_lamp_light_lighting_neon_ultraviolet_uv_icon]

**Comment by goyney** [comment] 2020-03-05 20:15
Duplicate of #4450.

**Closed by goyney** 2020-03-05 20:15 UTC
Labels: Icon Request

**Comment by arkansas-coder** [comment] 2020-03-06 00:09
Hello,
This, 4944, is not a duplicate of 4450. 4450 is for a Fluorescent tube
light, i.e.,just the tube or bulb. #4944 is for a Fluorescent fixture that
hold two or more tubes. I was unable to find any good line art, but this is
a photo of what I have in mind.

[image: image.png]
or
[image: image.png]
Thanks for reviewing my request.

**Comment by goyney** [comment] 2020-03-06 00:12
We’re having trouble figuring out how to do to one bulb that works at native resolution. Two bulbs is most likely out of the picture. Any other fixture is simply a rectangle and we have several icons that could cover that use case, such as the rectangular wall sconces.

**Comment by arkansas-coder** [comment] 2020-03-06 14:40
Thanks Michael, It seems that ceiling-light-flat is the best one around.
