### ISSUE TITLE
Unicorn

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5315] opened 2020-07-10 23:57 UTC
I created this icon based on the horse icon in #5314. It also relates to #2739, #2803, and #4625.

## Preview

![unicorn](https://user-images.githubusercontent.com/1837101/87211747-3409bf80-c2d8-11ea-919f-f90e48463cf4.png)

## Zip Download

[unicorn.svg.zip](https://github.com/Templarian/MaterialDesign/files/4905958/unicorn.svg.zip)

**Comment by goyney** [comment] 2020-07-12 19:40
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/2739. Please search before posting new issues. If you have a contribution, post it on that issue.

**Closed by goyney** 2020-07-12 19:40 UTC
Labels: Contribution, Icon Request
