### ISSUE TITLE
globe-lamp

### ISSUE THREAD

**Issue by Chourrage** [Templarian/MaterialDesign#5698] opened 2020-12-14 15:44 UTC
I have:
- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

I have a ikea fado light(https://www.ikea.com/de/de/p/fado-tischleuchte-weiss-80096372/). It's basically just a glass sphere with a light bulb inside. I found the globe-light icon, which is a hanging light. The icon I want to request  is basically a globe lamp, which could look similar to the globe light, but without the cord for hanging it and rotated 180 degrees. So basically a circle which has a small base or straight cut off on the bottom.

I would want to use this icon for home automation in home assistant to better identify the lamp by the logo.

Here is the Logo that is on the side of the box:
![image](https://user-images.githubusercontent.com/56000193/102101376-d51e1880-3e2a-11eb-9f99-5425c56ebd4d.png)
Feel free to change it a little if you have a good idea on how to visualize the lamp.

Thanks in advance

**Comment by goyney** [comment] 2021-08-30 21:52
Duplicate of #5220.

**Closed by goyney** 2021-08-30 21:52 UTC
Labels: Icon Request
