### ISSUE TITLE
set-top-box device

### ISSUE THREAD

**Issue by garyt72** [Templarian/MaterialDesign#3135] opened 2018-04-29 18:30 UTC
Requesting one or more variants of set top box / Stereo / Receiver / DVR etc icons

**Comment by Templarian** [comment] 2018-04-29 18:34
Duplicate of #2941

Would these work? If not can you please post some more examples on the above issue. It's slated for the next release.

**Comment by garyt72** [comment] 2018-04-30 00:15
That would be good for receiver, but I was also thinking of something a little smaller / thinner like this:
![image](https://image.shutterstock.com/image-vector/set-top-box-modern-icon-260nw-613060469.jpg)
and maybe a BD or DVD player icon something like this:
![image](https://static.thenounproject.com/png/143857-200.png)

**Comment by Templarian** [comment] 2018-04-30 04:56
[![disk-player](https://materialdesignicons.com/icon/disk-player)](https://materialdesignicons.com/icon/disk-player)

Still need a set top. But what about above for a generic disk player?

**Comment by Templarian** [comment] 2018-05-01 03:24
[![set-top-box](https://materialdesignicons.com/icon/set-top-box)](https://materialdesignicons.com/icon/set-top-box) [![record-player](https://materialdesignicons.com/icon/record-player)](https://materialdesignicons.com/icon/record-player)

**Closed by Templarian** 2018-05-01 03:24 UTC
Labels: Icon Request :pencil2:

**Comment by garyt72** [comment] 2018-05-03 01:10
Nice!!  Thank you!

**Comment by CoDEmanX** [comment] 2018-05-04 05:06
The disk player can't actually fit the disk 😄

Nice work though. I wonder if the receiver contribution should avoid rounding for the feet.
