### ISSUE TITLE
BOM in scss/_functions.scss can cause scss to fail 

### ISSUE THREAD

**Issue by juliangilbey** [Templarian/MaterialDesign#5779] opened 2021-01-13 14:14 UTC
For some reason, the file `scss/_functions.scss` begins with a byte-order mark, which can cause scss to fail.  This can be removed using a command such as:
```
sed -i -e '1s/^\xEF\xBB\xBF//' scss/_functions.scss
```

**Comment by goyney** [comment] 2021-01-13 15:37
Duplicate of #5778.

**Closed by goyney** 2021-01-13 15:37 UTC
Labels: Bug
