### ISSUE TITLE
hand-money request icon 

### ISSUE THREAD

**Issue by olivbau** [Templarian/MaterialDesign#6055] opened 2021-07-06 19:22 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

#### hand-money
An icon to give/lend money
Like `hand-heart` but for money

## Examples

Used by Youtube to to warn the user that he is this is a videos with paid product placements, sponsorships, and endorsements
![image](https://user-images.githubusercontent.com/11538800/124654813-501a4f80-de9f-11eb-850c-da81231f01fe.png)

**Comment by goyney** [comment] 2021-09-04 00:33
Duplicate of #5678.

**Closed by goyney** 2021-09-04 00:33 UTC
Labels: Icon Request
