### ISSUE TITLE
Roller shutter semi-open, without annotation

### ISSUE THREAD

**Issue by Darzyn** [Templarian/MaterialDesign#6790] opened 2022-09-29 05:28 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would use it in Home Assistant to illustrate a button that leaves my shutters half way open.

### Give us an example of what this icon might look like.

I'd see it as the window-shutter-alert, without the exclamation mark.

**Comment by mririgoyen** [comment] 2022-09-29 12:50
Please search before posting a request, as you indicated you did by checking the box.

Duplicate of #6754, #6740, #6277, #5872, #5733.

We've repeatedly and publicly stated we are not interested in adding these variations.

**Closed by mririgoyen** 2022-09-29 12:50 UTC
Labels: Icon Request
