### ISSUE TITLE
when upgraded the font to 5.4.55, there are issues on Android 10.0-

### ISSUE THREAD

**Issue by KevinHu-au** [Templarian/MaterialDesign#5959] opened 2021-05-03 02:57 UTC
when upgraded the font to 5.4.55, there are issues on Android 10.0-. But if the app is freshly installed with 5.4.55, then it works fine.

![Android font issue](https://user-images.githubusercontent.com/8989917/116837776-1e6ed900-ac0f-11eb-8370-fd3f3130d0a6.jpg)

**Comment by goyney** [comment] 2021-05-03 03:02
We'll need much more information than that to determine potential root cause.

**Comment by goyney** [comment] 2021-07-06 14:20
Closing because the `Needs More Info` tag was added quite a while ago without any further information provided. If you still have a need for this, please feel free to comment back and we can reopen to continue discussion. Thank you for your suggestion.

**Closed by goyney** 2021-07-06 14:20 UTC
Labels: Bug, Needs More Info
