### ISSUE TITLE
Automatic lights icon

### ISSUE THREAD

**Issue by raphaabreu** [Templarian/MaterialDesign#5910] opened 2021-03-31 01:30 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I am looking for an icon that indicate that lights are operating automatically, much like the already existing fan-auto for fans and flash-auto for power switches.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment] 2021-08-24 21:43
Duplicate of #5133.

**Closed by goyney** 2021-08-24 21:43 UTC
Labels: Icon Request, Home Assistant
