### ISSUE TITLE
truck-(plus | remove | minus)

### ISSUE THREAD

**Issue by JKennedy24** [Templarian/MaterialDesign#4298] opened 2019-08-05 15:17 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A icon variation on the truck / delivery icon to represent "Add delivery"

similar to: https://materialdesignicons.com/icon/truck-fast

But with a + icon on it somewhere

## Examples

Something like this:
![image](https://user-images.githubusercontent.com/9284438/62475146-617eec80-b79c-11e9-856b-24f6f2126e31.png)

**Comment by goyney** [comment] 2019-08-05 15:19
Duplicate of https://github.com/Templarian/MaterialDesign/issues/4199.

**Comment by JKennedy24** [comment] 2019-08-05 15:20
@goyney this is actually a request for Add delivery, not timed delivery.

Sorry if it was confusing, I was just using the timed delivery icon as an example of where the "+" icon could go

**Comment by goyney** [comment] 2019-08-05 15:22
Should probably add `minus` and `remove` as well.

**Comment by MrGrigri** [comment] 2019-08-05 20:42
There are a few concerns I have with the possible designs of these icons. I have tried three different placements; lower-right, cutout, and lower-left. I believe the lower-left position works the best.

### Lower Right
---

#### Icons

![image](https://user-images.githubusercontent.com/4528551/62492943-16111200-b78d-11e9-8dbd-4a59f7c7a05a.png) ![image](https://user-images.githubusercontent.com/4528551/62492984-2aeda580-b78d-11e9-9b4e-5c8cd7c5a32a.png) ![image](https://user-images.githubusercontent.com/4528551/62493012-3c36b200-b78d-11e9-9d04-90a7c746da33.png)

#### Thoughts

I don't like the cutout at the front of the truck. An option would be to switch the direction of the truck and keep the standard placement of the modifier in the lower-right-hand corner. 

### Cutout
---

#### Icons

![image](https://user-images.githubusercontent.com/4528551/62493207-caab3380-b78d-11e9-9a3c-928e7ee31fd5.png) ![image](https://user-images.githubusercontent.com/4528551/62493250-e0205d80-b78d-11e9-992e-d9494652f55d.png) ![image](https://user-images.githubusercontent.com/4528551/62493415-42795e00-b78e-11e9-9997-3b0657de7dd1.png)

#### Thoughts

This follows the rest of the cutout implementation for `truck-check` and `truck-delivery`. However, my only concern is that the `truck-plus` also looks like a medical truck and doesn't convey adding a truck. This is my favorite option.

### Lower Left
---

#### Icons

![image](https://user-images.githubusercontent.com/4528551/62493694-f7ac1600-b78e-11e9-9a87-5641fb53c9cb.png) ![image](https://user-images.githubusercontent.com/4528551/62493736-13afb780-b78f-11e9-88b6-8cb57dc3f4df.png) ![image](https://user-images.githubusercontent.com/4528551/62493760-25915a80-b78f-11e9-88f9-f4cd955c8feb.png)


#### Thoughts

Idk how I feel about this one.

**Comment by goyney** [comment] 2019-08-05 20:48
They should be in the bed.

And actually, we already have `plus`.

[![ambulance](https://materialdesignicons.com/icon/ambulance)](https://materialdesignicons.com/icon/ambulance)

**Comment by MrGrigri** [comment] 2019-08-05 20:50
That should be `truck-plus` with an alias of `ambulance.

**Comment by MrGrigri** [comment] 2019-08-05 20:51
That should be `truck-plus` with an alias of `ambulance.

**Comment by goyney** [comment] 2019-08-05 20:55
> That should be `truck-plus` with an alias of `ambulance`.

@Templarian Thoughts on this statement?

**Comment by MrGrigri** [comment] 2019-08-05 20:56
I should clarify. It should be that if we add these.

**Comment by MrGrigri** [comment] 2019-08-05 21:11
The other option is the cutout in the upper-left-hand corner. I like these better than the others, and we could maintain `ambulance` and alias that one with `truck`.

![image](https://user-images.githubusercontent.com/4528551/62495394-f8df4200-b792-11e9-80dc-0aa516fb835d.png) ![image](https://user-images.githubusercontent.com/4528551/62495419-0d233f00-b793-11e9-81ff-f958c8f72cc4.png) ![image](https://user-images.githubusercontent.com/4528551/62495445-21673c00-b793-11e9-9c43-6c7827d49f5b.png)

---

#### Files

[truck-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/3469441/truck-modifiers.zip)

**Comment by Templarian** [comment] 2019-08-06 00:25
Not a fan of any of these tbh. Have we tried doing a solid circle (-) with a 1px cut out. Let me try an idea in a few.

**Comment by Templarian** [comment] 2019-08-06 00:30
![image](https://user-images.githubusercontent.com/338885/62502897-6dc47300-b7b7-11e9-98f3-a918f5e2e830.png)

Ehh... still not a fan.

**Comment by JKennedy24** [comment] 2019-08-06 07:30
> They should be in the bed.
> 
> And actually, we already have `plus`.
> 
> [![ambulance](https://camo.githubusercontent.com/175ff579f8f2418f189cc4580ee9ea8c18411586/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f616d62756c616e6365)](https://materialdesignicons.com/icon/ambulance)

This looks too much like an ambulance. which is why I havent used it

> ![image](https://user-images.githubusercontent.com/338885/62502897-6dc47300-b7b7-11e9-98f3-a918f5e2e830.png)
> 
> Ehh... still not a fan.

Maybe a variation on this but the + symbol smaller more like?
![image](https://user-images.githubusercontent.com/9284438/62519950-71daaa00-b824-11e9-8eea-ff300435e950.png)

**Comment by goyney** [comment] 2019-08-06 14:29
> Maybe a variation on this but the + symbol smaller more like?

The plus cannot be any smaller than the proposed options.

**Comment by JamesCoyle** [comment] 2019-08-08 23:12
I like the ones like `ambulance` personally.

**Comment by Ch-Lo** [comment] 2019-08-15 07:34
Wouldn't the modifiers become easier to apply, if the truck **points to the left** (for all truck icons)? Then we can have the modifiers in the bottom right corner and the truck continues to look recognizable. I haven't seen this variant here, so maybe someone could create them?

**Comment by Templarian** [comment] 2019-08-19 23:04
@Ch-Lo In left to right languages icons always face to the right, so that isn't possible.

**Comment by CoDEmanX** [comment] 2019-08-19 23:15
We do have left-facing icons though:

![grafik](https://user-images.githubusercontent.com/1309249/63305415-ffb79a00-c2e6-11e9-9ae4-20481221cbb6.png)
![grafik](https://user-images.githubusercontent.com/1309249/63305432-0c3bf280-c2e7-11e9-90e2-cc9d7179787f.png)

The electric toothbrush should be okay, because most people are right-handed. But we might wanna flip the tram for instance.

https://material.io/design/usability/bidirectionality.html#mirroring-elements

**Comment by JKennedy24** [comment] 2019-11-08 10:02
> The other option is the cutout in the upper-left-hand corner. I like these better than the others, and we could maintain `ambulance` and alias that one with `truck`.
> 
> ![image](https://user-images.githubusercontent.com/4528551/62495394-f8df4200-b792-11e9-80dc-0aa516fb835d.png) ![image](https://user-images.githubusercontent.com/4528551/62495419-0d233f00-b793-11e9-81ff-f958c8f72cc4.png) ![image](https://user-images.githubusercontent.com/4528551/62495445-21673c00-b793-11e9-9c43-6c7827d49f5b.png)
> 
> #### Files
> [truck-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/3469441/truck-modifiers.zip)

I've gone for these ones in my application. 

In regards to left-right and right-left icons, I dont think it matters too much as long as there is consistency.

Ultimately if the developer wanted the icon to be left-right they can always flip it

**Comment by goyney** [comment] 2020-01-15 13:43
We understand you've come to a solution for your request, but there is still value to be added to the library in this issue. Reopening.

**Comment by goyney** [comment] 2021-09-03 00:54
At this point, I think we should just add the variations as cut out in the back of the truck. They're really the best option. We can keep `ambulance` and create a duplicate named `truck-plus` to prevent confusion on that front. The rest is going to be up to how someone uses the icon contextually. It's been 2 years without us having a minus or remove variation.

Unless I hear dissent in the next few days, that's my plan of attack.

**Comment by goyney** [comment] 2021-10-14 04:05
[![truck-plus](https://materialdesignicons.com/icon/truck-plus)](https://materialdesignicons.com/icon/truck-plus)[![truck-minus](https://materialdesignicons.com/icon/truck-minus)](https://materialdesignicons.com/icon/truck-minus)[![truck-remove](https://materialdesignicons.com/icon/truck-remove)](https://materialdesignicons.com/icon/truck-remove)

**Closed by goyney** 2021-10-14 04:05 UTC
Labels: Icon Request
