### ISSUE TITLE
Air quality icon 

### ISSUE THREAD

**Issue by fokcuk** [Templarian/MaterialDesign#6449] opened 2022-02-05 03:39 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have looked at similar requests but none were actually covering icons that people request. I am using Home Assistant and it does not support a combination of multiple alpha-numeric icons. 

Have sensors for monitoring air quality. Specifically was looking for either a generic icon for air quality and/or icons for PM2.5 and PM10 readings

### Give us an example of what this icon might look like.

PM25
PM10
AQI
wind + either of these markings

**Comment by goyney** [comment] 2022-02-06 20:52
Dupe of https://github.com/Templarian/MaterialDesign/issues/4204.

**Closed by goyney** 2022-02-06 20:52 UTC
Labels: Icon Request, Home Assistant
