### ISSUE TITLE
Racing/Bike Helmet

### ISSUE THREAD

**Issue by TheSagarPatil** [Templarian/MaterialDesign#1721] opened 2016-12-28 08:31 UTC
Hi, Please create these icons

Driver icon (i.e. a helmet),
A car icon
a stopwatch icon
letter icons like ABCD etc. and a fuel station icon

Thanks in advanced :)

**Comment by JamesCoyle** [comment] 2016-12-28 08:36
[![](https://materialdesignicons.com/icon/gas-station)](https://materialdesignicons.com/icon/gas-station)[![](https://materialdesignicons.com/icon/car)](https://materialdesignicons.com/icon/car)[![](https://materialdesignicons.com/icon/timer)](https://materialdesignicons.com/icon/timer)

Letter icons have been discussed but are not likely to happen any time soon.

**Comment by MrGrigri** [comment] 2016-12-29 17:39
The icon request for letters is a duplicate of [#911](https://github.com/Templarian/MaterialDesign/issues/911).

**Comment by MrGrigri** [comment] 2016-12-29 22:45
Here is my attempt at a racing helmet.

![helmet](https://cloud.githubusercontent.com/assets/4528551/21556461/bfb458ae-cddd-11e6-9be7-5e5010bc373e.png)

[helmet.zip](https://github.com/Templarian/MaterialDesign/files/677962/helmet.zip)

**Comment by goyney** [comment] 2019-01-10 18:01
![image](https://user-images.githubusercontent.com/1015040/50987528-deccd200-14d7-11e9-9499-3026d35534f7.png)
[sports-motorsports.svg.zip](https://github.com/Templarian/MaterialDesign/files/2746545/sports-motorsports.svg.zip)

**Comment by Templarian** [comment] 2019-01-22 05:04
[![racing-helmet](https://materialdesignicons.com/icon/racing-helmet)](https://materialdesignicons.com/icon/racing-helmet)

**Closed by Templarian** 2019-01-22 05:04 UTC
Labels: Contribution :heavy_check_mark:, Icon Request :pencil2:, Stock Google Icon :squirrel:

**Comment by PeterShaggyNoble** [comment] 2019-01-22 17:58
Should this be assigned to Google?

**Comment by MrGrigri** [comment] 2019-01-22 17:59
Yes, it should be.

**Comment by Templarian** [comment] 2019-01-22 18:02
Ooops, completely missed that this was from the extended set. Will reassign.

**Comment by Templarian** [comment] 2019-01-22 18:04
Fixed. Thanks for double checking. 👍
