### ISSUE TITLE
Request: Cogs

### ISSUE THREAD

**Issue by feralheart** [Templarian/MaterialDesign#2889] opened 2018-03-08 08:30 UTC
Need an icon with more cogs, like this:

![Cogs](https://image.freepik.com/free-icon/cogs-one-big-and-two-small_318-41835.jpg)

**Comment by PeterShaggyNoble** [comment] 2018-03-08 08:32
Thanks for the request but this is a duplicate of #1262.

**Closed by PeterShaggyNoble** 2018-03-08 08:32 UTC

**Comment by feralheart** [comment] 2018-03-09 10:08
@PeterShaggyNoble I see. And when will be available in this package, too?

**Comment by Templarian** [comment] 2018-03-12 18:55
@feralheart Marked that other issue as high priority so it doesn't get ignored.
