### ISSUE TITLE
https://materialdesignicons.com/ tango down, cdn also

### ISSUE THREAD

**Issue by morriq** [Templarian/MaterialDesign#5720] opened 2020-12-21 11:58 UTC
hello, just fyi.

do you work on resolving this issue? I must know if I should change it in our products before christmas eve.

**Comment by Simran-B** [comment] 2020-12-21 13:02
Duplicate of https://github.com/Templarian/MaterialDesign/issues/5692

**Closed by Simran-B** 2020-12-21 13:02 UTC
Labels: Bug
