### ISSUE TITLE
Icon suggestion: Door, Window

### ISSUE THREAD

**Issue by redskinwashingtons** [Templarian/MaterialDesign#2032] opened 2017-04-19 18:52 UTC

**Comment by PeterShaggyNoble** [comment] 2017-04-20 08:39
Door is a dupe of #1822 and 2 window icons already exist:

[![window-closed](https://materialdesignicons.com/icon/window-closed)](https://materialdesignicons.com/icon/window-closed) [![window-open](https://materialdesignicons.com/icon/window-open)](https://materialdesignicons.com/icon/window-open)

**Closed by PeterShaggyNoble** 2017-04-20 08:39 UTC
