### ISSUE TITLE
open and closed venetian blind icons (tilt)

### ISSUE THREAD

**Issue by rchiileea** [Templarian/MaterialDesign#6304] opened 2021-11-05 08:18 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Searched for a day looking for the right icons to use for my smart home for Venetian blinds (tilt) for open and close and could not find them so I decided to create my own and use images as icons, then thought why not just make them available for all 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/87599807/140479154-c355780d-81d5-46bd-9aaf-fe9a484bd439.png)
![image](https://user-images.githubusercontent.com/87599807/140479991-eacba007-faef-468d-9167-5fc575294f54.png)

### Upload the icon source.

[tiltblind.zip](https://github.com/Templarian/MaterialDesign/files/7481628/tiltblind.zip)

**Comment by goyney** [comment] 2021-11-05 13:07
Duplicate of #4419. Please search before posting a new issue.

**Closed** 2021-11-05 13:07 UTC
Labels: Icon Request, Contribution, Duplicate

**Comment by rchiileea** [comment] 2021-11-05 13:12
is there a issue with this one too? or just because someone has done something like it?
