### ISSUE TITLE
day and week icons

### ISSUE THREAD

**Issue by secmin** [Templarian/MaterialDesign#4917] opened 2020-02-24 09:32 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

It can be used for timelines on websites.

## Examples

Include any example images so we know what the icon should look like.

day:
![FotoJet1](https://user-images.githubusercontent.com/56533444/75141106-a025c580-5733-11ea-9669-188c2489475e.png)![FotoJet3](https://user-images.githubusercontent.com/56533444/75141124-a9169700-5733-11ea-8422-6338bd70aa46.png)

week:
![FotoJet (1)](https://user-images.githubusercontent.com/56533444/75141092-94d29a00-5733-11ea-9ab0-981e23b30d75.png)![FotoJet2](https://user-images.githubusercontent.com/56533444/75141119-a6b43d00-5733-11ea-92bd-e574a1782b44.png)

**Comment by goyney** [comment] 2020-02-24 16:00
Looks like a duplicate of https://github.com/Templarian/MaterialDesign/issues/1272.

**Comment by secmin** [comment] 2020-02-25 05:54
I saw # 1272.
When I search this icon, the icon does not appear. You will see a different icon called store -24 hour. How can I search and find an icon like # 1272?
And # 1272 stands for day or every day, not week. If the above icons are very similar and cannot be adopted, how about this icon?
![FotoJet1](https://user-images.githubusercontent.com/56533444/75218871-a6bd4700-57de-11ea-8174-09e51ca8645c.png)![FotoJet](https://user-images.githubusercontent.com/56533444/75218875-a8870a80-57de-11ea-8f03-873674bcee90.png)

**Comment by Templarian** [comment] 2020-02-25 06:17
This request is sort of a duplicate. The other one looks more like 24/7.

This one is looking for 2 different icons. One to represent 24 and another for 7 days / a week.

**Comment by goyney** [comment] 2021-09-03 01:12
Plenty of options here:

[![hours-24](https://materialdesignicons.com/icon/hours-24)](https://materialdesignicons.com/icon/hours-24)
[![calendar-today](https://materialdesignicons.com/icon/calendar-today)](https://materialdesignicons.com/icon/calendar-today)
[![calendar-week](https://materialdesignicons.com/icon/calendar-week)](https://materialdesignicons.com/icon/calendar-week)

**Closed** 2021-09-14 01:04 UTC
Labels: Icon Request, Consider Closing
