### ISSUE TITLE
No Line App Icon

### ISSUE THREAD

**Issue by JPMulder** [Templarian/MaterialDesign#4095] opened 2019-04-06 12:15 UTC
Hi
I think with 600 million users I think this icon should be available.
https://expandedramblings.com/index.php/line-statistics/
much appreciated

**Comment by Templarian** [comment] 2019-04-06 16:51
Thought we had an issue for this opened at one point.

**Comment by Templarian** [comment] 2019-04-06 17:32
Duplicate of #1481.

**Closed by Templarian** 2019-04-06 17:32 UTC
Labels: Duplicate/Already Included :bookmark_tabs:

**Comment by JPMulder** [comment] 2019-04-07 07:55
In the mean time I've created a webfont with an svg here https://glyphter.com/ for those who want to create the line app icon urgently
