### ISSUE TITLE
dog icon for material design icons

### ISSUE THREAD

**Issue by nikfrank** [Templarian/MaterialDesign#835] opened 2015-11-14 17:38 UTC
there's:

cat
pig
alien
ghost
fish
bird
php

why no dog?

**Comment by CoDEmanX** [comment] 2015-11-14 18:18
Not sure if calling aliens animals is discrimination according to the shadows proclamation, but I can't find an alien icon?! Also, php is for sure no animal, neither is the twitter logo IMO. We do have an owl however.

Valid request nonetheless.

**Comment by Templarian** [comment] 2015-11-14 22:13
I agree.

A dog is an animal.

**Comment by CoDEmanX** [comment] 2015-11-19 00:28
Actually a duplicate of #736

**Closed by CoDEmanX** 2015-11-19 00:28 UTC
Labels: Duplicate, Icon Request
