### ISSUE TITLE
RAM, GPU and Screen,  icons

### ISSUE THREAD

**Issue by dovahkiin98** [Templarian/MaterialDesign#2551] opened 2017-10-23 10:09 UTC
I would like to request 2 new icons, RAM, GPU and Screen Icons

**Comment by GreenTurtwig** [comment] 2017-10-23 10:16
We have icons for memory and monitors already:
[![](https://materialdesignicons.com/icon/chip)](https://materialdesignicons.com/icon/chip)[![](https://materialdesignicons.com/icon/monitor)](https://materialdesignicons.com/icon/monitor)

A GPU has been contributed over here: https://github.com/Templarian/MaterialDesign/issues/1034

Great username by the way. :-P

**Comment by PeterShaggyNoble** [comment] 2017-10-23 10:35
There's also the `memory` icon, which might be of use to you:

[![](https://materialdesignicons.com/icon/memory)](https://materialdesignicons.com/icon/memory)

**Comment by dovahkiin98** [comment] 2017-10-23 14:37
There are monitors but none is a screen of a mobile device, and the memory
icon looks very much like the chip icon

**Comment by GreenTurtwig** [comment] 2017-10-23 14:40
What do you mean by "mobile device"? We have icons for phones, tablets and laptops, all of which have displays.

**Comment by MrGrigri** [comment] 2017-10-23 16:46
![cellphone](https://materialdesignicons.com/icon/cellphone) ![cellphone-android](https://materialdesignicons.com/icon/cellphone-android) ![cellphone-iphone](https://materialdesignicons.com/icon/cellphone-iphone) ![cellphone-basic](https://materialdesignicons.com/icon/cellphone-basic)

**Comment by JamesCoyle** [comment] 2017-10-26 15:33
Duplicate of #1034

**Closed by JamesCoyle** 2017-10-26 15:33 UTC
Labels: Consider Closing, Duplicate
