### ISSUE TITLE
Ability to export only a specific size/color variant of an icon

### ISSUE THREAD

**Issue by nwalters512** [Templarian/MaterialDesign#408] opened 2015-06-03 19:05 UTC
We currently have the option to download all color/size variants in a single bundle, which is very useful. However, if you look at what the [official Google Icons site](https://www.google.com/design/icons/) offers, you can select a color and a dp size and download only the different density variants of that specific icon. Because the folder structure mirrors that used by android studio (```drawable-SIZE```) and each folder contains only a single icon, it is easy to copy/paste the group of folders into the ````res/``` directory, instead of having to go through each resolution bucket and copy over the single icon that I need.

**Comment by Templarian** [comment] 2015-06-03 19:08
I'm going to mark this as a duplicate of #371 since it will be solved when that issue is fixed.

Thanks, I'll update 371 when the changes are in.

**Closed by Templarian** 2015-06-03 19:08 UTC
Labels: Site Feature

**Comment by nwalters512** [comment] 2015-06-03 19:13
Beautiful, I should've looked for an existing issue, sorry about that. I noticed that 371 doesn't mention anything about size, don't forget about that!

**Comment by Templarian** [comment] 2015-06-03 19:15
I've added 2 tasks the 2nd task addresses this. :smile:

This is a pretty highly needed option (I can see it in the download stats).
