### ISSUE TITLE
Request: London underground symbol

### ISSUE THREAD

**Issue by robmarkcole** [Templarian/MaterialDesign#2021] opened 2017-04-17 09:00 UTC
Perhaps one of the most iconic brands?

**Comment by brainscript** [comment] 2017-04-17 10:01
This could be a duplicate of #1996.
They're not the same thing, but look almost exactly the same without the colors and the text.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Underground.svg/1200px-Underground.svg.png" width="120">

_London Underground_

<img src="https://tfl.gov.uk/cdn/static/assets/icons/favicon-160x160.png" width="120">

_Transport for London_

**Comment by PeterShaggyNoble** [comment] 2017-04-17 10:28
Closing this one as a duplicate of and for the same reasons as #1996. See @templarian's comment there about the possibility of this being revisited.

**Closed by PeterShaggyNoble** 2017-04-17 10:28 UTC
