### ISSUE TITLE
Lamp Post Icon

### ISSUE THREAD

**Issue by TravisRoy** [Templarian/MaterialDesign#6063] opened 2021-07-12 19:38 UTC
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For Home automation to put an icon for a lamp post.

## Examples
![images](https://user-images.githubusercontent.com/30446459/125345940-2477e900-e327-11eb-8be6-e00469060ed1.jpg)
![images-1](https://user-images.githubusercontent.com/30446459/125345950-2641ac80-e327-11eb-898e-c4e4d4fd7a6c.jpg)
![105798-200](https://user-images.githubusercontent.com/30446459/125345954-293c9d00-e327-11eb-9c5e-7842eca8218c.png)
![download](https://user-images.githubusercontent.com/30446459/125345959-2a6dca00-e327-11eb-93dd-7c476672fcd5.png)

**Comment by goyney** [comment] 2021-08-30 22:01
Duplicate of #5412.

**Closed by goyney** 2021-08-30 22:01 UTC
Labels: Icon Request
