### ISSUE TITLE
spreadsheet missing from MaterialDesign-Webfont

### ISSUE THREAD

**Issue by arnaudvalle** [Templarian/MaterialDesign#3271] opened 2018-06-21 13:46 UTC
Hello there 👋 

Looks like the `spreadsheet` icon is in the [repo](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/spreadsheet.svg) but is not in the [Webfont](https://github.com/Templarian/MaterialDesign-Webfont/blob/master/scss/_variables.scss#L784).

Any chance of fixing it?

Many thanks,

**Comment by goyney** [comment] 2018-06-21 13:59
Duplicate of: https://github.com/Templarian/MaterialDesign/issues/1966

**Closed by goyney** 2018-06-21 13:59 UTC

**Comment by PeterShaggyNoble** [comment] 2018-06-25 10:37
Note that this is development repo, not the production repo - you can find that [here](https://github.com/Templarian/MaterialDesign-SVG).

**Comment by arnaudvalle** [comment] 2018-07-05 07:47
Ok thanks for the clarification 👍
