### ISSUE TITLE
Create an icon for Lifesaver

### ISSUE THREAD

**Issue by JavierChacon** [Templarian/MaterialDesign#2359] opened 2017-08-28 19:36 UTC
https://www.google.cl/search?biw=1366&bih=654&tbm=isch&sa=1&q=lifesaver&oq=lifesaver&gs_l=psy-ab.3..0i67k1j0j0i67k1j0.6237.10012.0.10148.10.10.0.0.0.0.425.1014.2-2j0j1.3.0....0...1.1.64.psy-ab..7.3.1013.tzASg1JNXxQ

**Comment by JamesCoyle** [comment] 2017-08-28 20:14
Duplicate of #873. @Templarian You really should get those icons added at some point...

**Closed by JamesCoyle** 2017-08-28 20:14 UTC
Labels: Duplicate
