### ISSUE TITLE
Google+ Logo

### ISSUE THREAD

**Issue by pme-odoo** [Templarian/MaterialDesign#667] opened 2015-09-08 10:44 UTC
I know there are so many G+ logos are available but recently google launches new logo of G+.

Old Logo: https://goo.gl/uippfJ

New Logo: https://goo.gl/FmSU40

**Comment by CoDEmanX** [comment] 2015-09-08 11:28
Duplicate of #661

**Closed by CoDEmanX** 2015-09-08 11:28 UTC
