### ISSUE TITLE
Window Shutter Positions

### ISSUE THREAD

**Issue by TheNr1Guest** [Templarian/MaterialDesign#6754] opened 2022-08-18 09:40 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would like to see a couple of variants of the `window-shutter` icon added to indicate the level at which a shutter is open.

This icon is used in Home Assistant but I find it annoying that if I open the shutter only by a fraction, the icon indicates fully open.

So with that in mind I would like to see 5 new icons:

- `window-shutter-position-100`
- `window-shutter-position-75`
- `window-shutter-position-50`
- `window-shutter-position-25`
- `window-shutter-position-0`

This would allow users / integrations to better reflect shutter positions.

Thanks!

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/8267168/185363459-3fb15f6e-380c-445c-82fb-904a09d91f4a.png)

**Comment by mririgoyen** [comment] 2022-08-18 12:29
Please SEARCH.

Duplicate of #5733 #5872 #6277 #6740.

**Closed by mririgoyen** 2022-08-18 12:29 UTC
Labels: Icon Request

**Comment by TheNr1Guest** [comment] 2022-08-18 13:40
@mririgoyen Sorry, will do next time.

But since the issues you mentioned are all closed, I can't help myself but give my two cents here. I read you have three main arguments for opposing positional icon variants:

A: It's niche
B: It would allow for other icons to request similar icons, like doors for example
C: Icon's should be used contextual

My counter arguments would be:

A: I think when we go through the whole library, other icons will fit this label too. There is even a window-shutter-auto icon to indicate a window shutter automation. In my eyes, that's very niche. But I can see that this is subjective. Home automation is becoming more prevalent so I think it will be handy, if not now, maybe in the future.

B: I would say that for every device where we have the possibility of fine grained positions we allow these type of icons. So doors do not meet this criteria. I do not open my door at 69%. But this is not true for shutters where I do want to adjust them according to how much sun light I want to have exposed in my room.

C: If I open my shutter for 1%, the icon I see will be the window-shutter-open one indicating that it's open. While this is technically true. I feel that, in the context of home automation, users will still like to see if it's partially opened or fully. Similar to lights, in Home Assistant the light icon changes color based on the actual color of the light similar to the icon being dimmer if the light is dimmed. So I think a shutter position would fit perfectly. (I am aware this is more from a Home Assistant perspective and might not apply to this library.)
