### ISSUE TITLE
Clap outline and filled

### ISSUE THREAD

**Issue by QuesstTechnologies** [Templarian/MaterialDesign#5011] opened 2020-04-03 12:58 UTC
I have:

- [**yes**] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [**yes**] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [**yes**] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
**Endorsement of content**

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/52661976/78363100-e0465680-75c3-11ea-9d6f-a63362639104.png)

**Comment by goyney** [comment] 2020-04-03 13:33
Duplicate of #3821. Please search before you check the box that says you searched.

**Closed by goyney** 2020-04-03 13:33 UTC
Labels: Icon Request
