### ISSUE TITLE
cow-off

### ISSUE THREAD

**Issue by leijae** [Templarian/MaterialDesign#6193] opened 2021-09-10 19:21 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Food allergy options

### Give us an example of what this icon might look like.

Cow icon with a diagnal line over the top of it starting in the top-left and ending in the bottom-right

~a sea shell icon with a diagnal line over the top of it starting in the top-left and ending in the bottom-right~

**Comment by goyney** [comment] 2021-09-10 19:27
The shell request is a duplicate of #3780.

Modifying this issue to track `cow-off`.

**Comment by goyney** [comment] 2021-09-10 20:17
![image](https://user-images.githubusercontent.com/1015040/132912575-22103c20-0065-4c6c-b5e0-14167201d04d.png)

[cow-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/7146202/cow-off.svg.zip)

**Comment by goyney** [comment] 2021-09-13 21:21
Added.

**Closed by goyney** 2021-09-13 21:21 UTC
Labels: Icon Request, Contribution

**Comment by leijae** [comment] 2021-09-14 03:07
Thank you! Very much appreciated.
