### ISSUE TITLE
Icon suggestion for "terms and agreements"

### ISSUE THREAD

**Issue by odil-akhmedov** [Templarian/MaterialDesign#1307] opened 2016-06-23 15:25 UTC
Hi there,
In our project we are struggling to find an appropriate icon for our "terms and agreements" page. I guess the best way to describe would be an icon with the handshake?

Regards,
Odil Akhmedov

**Comment by Templarian** [comment] 2016-06-23 15:48
Duplicate of #330.

**Closed by Templarian** 2016-06-23 15:48 UTC
Labels: Duplicate
