### ISSUE TITLE
Nest Mini, Nest Hub, Echo dot...

### ISSUE THREAD

**Issue by MiguelAngelLV** [Templarian/MaterialDesign#5279] opened 2020-06-28 18:08 UTC
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have a few assistants speaker, a Google Home, Nest Mini, Nest Hub... For now, I use Google Home icon, but, it is not very usefull for Nest Hub for example.

I think that, a fews alternatives of mains models of Nests and Echo assistants can be wellcome to home automation users.

**Comment by Templarian** [comment] 2020-06-28 18:29
Duplicate of #4521

**Closed by Templarian** 2020-06-28 18:29 UTC
Labels: Icon Request, Rejected

**Comment by Templarian** [comment] 2020-06-28 18:30
The `google-home` is probably being removed from `6.0` release as we're going to be removing the remaining brand specific icons. They change designs/styles too often to represent with an icon.
