### ISSUE TITLE
krul-circle-outline

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6649] opened 2022-06-15 09:34 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

In the Netherlands we make use of this symbol. It's a symbol to state 'this' is approved. We created three versions. A stand alone version. A solid circle version and this circle outline version.

### Share a preview of your contribution.

![preview-krul-circle-outline](https://user-images.githubusercontent.com/107536590/173795462-dc300974-cd9f-42b5-80f2-06601991b188.png)

### Upload the icon source.

[krul-circle-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/8907980/krul-circle-outline.svg.zip)

**Comment by goyney** [comment] 2022-06-15 10:26
Dupe of #6647.

**Closed by goyney** 2022-06-15 10:26 UTC
Labels: Icon Request, Contribution
