### ISSUE TITLE
Rooster

### ISSUE THREAD

**Issue by GUOLDEV** [Templarian/MaterialDesign#6379] opened 2021-12-24 00:46 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Rooster

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/22019245/147302547-6349267d-31b2-4a58-9ced-54e49a303108.png)

### Upload the icon source.

[mdi-rooster.svg.zip](https://github.com/Templarian/MaterialDesign/files/7771964/mdi-rooster.svg.zip)

**Comment by goyney** [comment] 2021-12-24 01:36
Duplicate of #3455.

**Closed by goyney** 2021-12-24 01:36 UTC
Labels: Icon Request, Contribution

**Comment by GUOLDEV** [comment] 2021-12-24 01:52
> Duplicate of #3455.

Hey mate 👋 there's no rooster in the list. Not sure why it is closed 🤯

**Comment by goyney** [comment] 2021-12-24 01:55
We have an open issue for a chicken. Hen, rooster... from an icon perspective, they're the same thing. We cannot provide enough discernible details at native resolution to make them unique. So, if you have a contribution to add of a chicken, please do so on the already open issue.

In terms of the two icons your proposed, neither of them are Material and can be added in their current form.
