### ISSUE TITLE
Tax

### ISSUE THREAD

**Issue by FranckSix** [Templarian/MaterialDesign#6299] opened 2021-11-03 18:44 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

tax levy

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/8504152/140173036-a918077b-334b-415a-b34d-f39d9131810f.png)

### Upload the icon source.

[tax.zip](https://github.com/Templarian/MaterialDesign/files/7470026/tax.zip)

**Comment by goyney** [comment] 2021-11-03 18:58
I'm not sure I understand what this is supposed to depict. But regardless, please review the [Material Design Icon guidelines](Material guidelines) and make sure you are following them.

**Comment by FranckSix** [comment] 2021-11-03 19:26
> I'm not sure I understand what this is supposed to depict. But regardless, please review the [Material Design Icon guidelines](https://material.io/design/iconography/system-icons.html) and make sure you are following them.

I want to illustrate the tax levy. In the system I'm working on, the user needs to set the taxes for their region. My need is therefore an icon that allows access to this functionality.

**Comment by goyney** [comment] 2021-11-03 19:43
I mean, I understand what you're requesting by the title of the issue. However, the idea proposed is very abstract and I do not think it works as a general icon for this library in its current form.

Additionally, this is a duplicate of #3666 and #1169. Therefore, we're going to close it.

Lastly, I linked to the guidelines because you've broken many rules (on this request and others you've submitted). Please take a look over those before submitting other requests.

**Closed by goyney** 2021-11-03 19:43 UTC
Labels: Icon Request, Contribution, Consider Closing
