### ISSUE TITLE
irrigazione

### ISSUE THREAD

**Issue by roberto109** [Templarian/MaterialDesign#5222] opened 2020-06-08 05:49 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment] 2020-06-08 06:05
@roberto109 The template isn't optional. Can you please fill it in. 👍

**Comment by Templarian** [comment] 2020-06-08 06:07
This might be a duplicate of #2509

**Comment by Templarian** [comment] 2020-06-09 16:22
Closing this out. Reopen if `sprinkler` or `sprinkler-variant` won't work. Please include examples, so we have something to go off of.

**Closed by Templarian** 2020-06-09 16:22 UTC
Labels: Icon Request, Needs More Info
