### ISSUE TITLE
Icon-request: Patreon

### ISSUE THREAD

**Issue by Albiwalbi** [Templarian/MaterialDesign#2823] opened 2018-02-18 12:01 UTC
Maybe add an icon for Patreon?

**Comment by PeterShaggyNoble** [comment] 2018-02-18 12:03
This is a duplicate of #1294.

**Closed by PeterShaggyNoble** 2018-02-18 12:03 UTC

**Comment by Albiwalbi** [comment] 2018-02-18 17:17
Yeah, came across that one, but it's the old logo, I was looking for an updated version :)

**Comment by Templarian** [comment] 2018-02-18 17:33
[![patreon](https://materialdesignicons.com/icon/patreon)](https://materialdesignicons.com/icon/patreon)
