### ISSUE TITLE
storage / warehouse states 

### ISSUE THREAD

**Issue by burndragon** [Templarian/MaterialDesign#3472] opened 2018-09-12 16:06 UTC
I have created a few different states of a storage or whare house filling up.

![storage-full-outline](https://user-images.githubusercontent.com/43213826/45438056-bc3ac180-b67b-11e8-816d-0a79ec8326c1.png)
![storage-full](https://user-images.githubusercontent.com/43213826/45438057-bc3ac180-b67b-11e8-8d16-dcece217c203.png)
[storage-outline.zip](https://github.com/Templarian/MaterialDesign/files/2375977/storage-outline.zip)
[storage.zip](https://github.com/Templarian/MaterialDesign/files/2375978/storage.zip)

**Comment by CoDEmanX** [comment] 2018-09-15 23:06
Your contributions don't meet our requirements in the current form:

- The shapes should be better grid-aligned
- no rounded terminals as per MD guidelines
- each icon has to be a single path (fill only)

![grafik](https://user-images.githubusercontent.com/1309249/45591191-ceeb1a00-b94b-11e8-94f8-7f5e495c2ce8.png)

**Comment by SarinManS** [comment] 2018-09-17 06:08
This should meet the material guidelines
![image](https://user-images.githubusercontent.com/26505215/45607965-a52b1380-ba6f-11e8-8fec-31bda857cd57.png)

However I don't think decreasing the number of squares in the middle is a good way to denote the current load of the storage. This might work better in my view...
![image](https://user-images.githubusercontent.com/26505215/45607977-b542f300-ba6f-11e8-9bf6-4b739195d126.png)
![image](https://user-images.githubusercontent.com/26505215/45607985-bf64f180-ba6f-11e8-84eb-bcd2e4041f73.png)
![image](https://user-images.githubusercontent.com/26505215/45607988-c7249600-ba6f-11e8-9f04-ec244c13e0ae.png)
![image](https://user-images.githubusercontent.com/26505215/45607999-d4418500-ba6f-11e8-9191-1c53c6cec4d2.png)
![image](https://user-images.githubusercontent.com/26505215/45608006-ddcaed00-ba6f-11e8-8396-90fc3b8f0913.png)

Not sure about the number of levels... I guess we can just have three levels ( empty - half - full)

Everything here
[storage.zip](https://github.com/Templarian/MaterialDesign/files/2387474/storage.zip)

**Comment by goyney** [comment] 2018-11-20 16:31
I don't feel like adding a progress bar to a warehouse icon serves a general use case and is too niche to be added to the library. The single `storage` icon would be all I think we should add.

**Comment by goyney** [comment] 2018-11-20 16:45
This is also a duplicate of #3076.

**Closed** 2018-11-20 17:04 UTC
Labels: Contribution :heavy_check_mark:, Duplicate/Already Included :bookmark_tabs:, Icon Request :pencil2:
