### ISSUE TITLE
Submit some icons

### ISSUE THREAD

**Issue by jonohunt** [Templarian/MaterialDesign#2222] opened 2017-07-04 13:37 UTC
Here's some icons I'd like to submit

![mdi icons](http://d.pr/i/Q0kaeF+)

[Download](http://d.pr/f/9SWR3a)

**Comment by dintendocoltd** [comment] 2017-07-04 14:32
I can't speak for anyone here, but it seems to me that the icons do not fit the material design guidelines.

The icons such as the fireplace, wall-light, record are hard to identify without the specific labels. While the the Sky Q Box is too specific (and could be a generic DVR box icon instead). Also, icons such as the Lava Lamp and TV already exist.

However, that being said, I do appreciate your other icons you have created which you have on your website (as shown on your GitHub account).

**Comment by MrGrigri** [comment] 2017-07-05 16:15
Thanks for your submissions. There are just a few things that I would like to point out with each icon. 

1. Your first icon for a lamp will be added to the checklist on #1712. Feel free to add your contribution there.
2. The fireplace mantle is very tricky because it could look like a table, building, or mantle (-ish). 
3. Google Home is a duplicate of #1811.
4. The lava lamp was just added with #2075.
5. The record button looks like the radio button and we already have the record icon from Google [here](https://materialdesignicons.com/icon/record)
6. The Sky Q icon is too specific and more than likely will not be added. 
7. The wall light was just designed on issue #1712.
8. And lastly, the television icon is already a part of the icon pack [television](https://materialdesignicons.com/icon/television)

**Comment by Templarian** [comment] 2017-07-07 03:48
Fireplace would probably need "fire" to be recognizable at the smaller size. The shape is too easily to mistake.

We're trying to consolidate icons into single icon per requests. I'm going to close this issue out. Please open an issue for `fireplace` (useful for Home Assistant users).

**Closed by Templarian** 2017-07-07 03:48 UTC
Labels: Consider Closing, Needs More Information

**Comment by disrupted** [comment] 2018-02-17 23:09
@MrGrigri I don't really understand the explanation for icon 8. The television icon we have doesn't look like an actual television as it is clearly not widescreen 16:9 aspect ratio. The one submitted by @jonohunt addresses this issue, it's much better suited for modern applications. Just look at the `youtube-tv`icon as a comparison.
