### ISSUE TITLE
Icon Request - Chef Hat

### ISSUE THREAD

**Issue by vlonjatg** [Templarian/MaterialDesign#1629] opened 2016-11-10 23:09 UTC
Something like this would be nice: ![chef hat-50](https://cloud.githubusercontent.com/assets/11259634/20198093/15dea86c-a7a3-11e6-8e89-b283b1efaddb.png)

**Comment by Templarian** [comment] 2016-11-10 23:41
Duplicate of #659.

**Closed by Templarian** 2016-11-10 23:41 UTC
