### ISSUE TITLE
Add an icon for email sent.

### ISSUE THREAD

**Issue by harsimranmaan** [Templarian/MaterialDesign#5794] opened 2021-01-17 02:22 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Would be used to notify users in an app when an email has been sent.

## Examples

Similar to work by @martareg [here](https://github.com/bigpanther/shipanther/issues/249#issuecomment-761530930)

**Comment by goyney** [comment] 2021-01-18 14:51
Duplicate of #5606.

**Closed by goyney** 2021-01-18 14:51 UTC
Labels: Icon Request
