### ISSUE TITLE
cash-gbp / cash-pound & variants

### ISSUE THREAD

**Issue by Matthew-E-Gould** [Templarian/MaterialDesign#5660] opened 2020-11-24 10:52 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

similar to cash-usd variants but for countries that use the pound instead of dolla

## Examples

like cash-usd & cash-usd-outline but with a £ instead of $

## Name & Alias Suggestions

cash-gbp
cash-pound
cash-queen-dollar
cash-king-dollar
cash-£

**Comment by goyney** [comment] 2020-11-24 14:29
Unfortunately, we're not adding new icon variants with other currency markers. It becomes a slippery slope pretty quickly. We've discussed removing the USD `$` ones in the past. Perhaps that conversation is worth having again. (Not the individual currency markers, the icons, such as `cash-usd` that incorporate the currency marker within an existing icon.)

@Templarian thoughts?

**Comment by Templarian** [comment] 2020-11-24 16:54
The problem is not all currency symbols are recognizable inside of the small cash rectangle. 🤷‍♂️ This could end up with everyone wanting similar icons and it would get a bit messy.

**Comment by goyney** [comment] 2020-11-24 17:16
We've discussed this internally and won't be adding these. In fact, we have now deprecated the `usd` variants and they will be removed in 6.0.

https://github.com/Templarian/MaterialDesign/issues/5661

**Closed by goyney** 2020-11-24 17:16 UTC
Labels: Icon Request

**Comment by Matthew-E-Gould** [comment] 2020-12-09 14:30
understandable
