### ISSUE TITLE
space_bar

### ISSUE THREAD

**Issue by timvolta** [Templarian/MaterialDesign#4109] opened 2019-04-14 11:53 UTC
please consider adding a icon:  space_bar.
Same as:
 https://material.io/tools/icons/?search=space_bar&style=baseline
![ic_space_bar_black_24dp](https://user-images.githubusercontent.com/38859868/56092417-46f1d200-5e92-11e9-8aa4-8027fe7300d9.png)

with grey600

Thanks in advance!

**Comment by PeterShaggyNoble** [comment] 2019-04-14 12:12
Duplicate of #4017

**Closed by PeterShaggyNoble** 2019-04-14 12:12 UTC
