### ISSUE TITLE
Icon for Google Home Mini

### ISSUE THREAD

**Issue by stanvx** [Templarian/MaterialDesign#2898] opened 2018-03-10 02:06 UTC
Would like a Google Home Mini icon, just like the existing [Google Home icon](https://materialdesignicons.com/api/download/icon/png/EEB46F1F-4996-4B65-A1C6-70DC4D38C34E/48).

**Comment by PeterShaggyNoble** [comment] 2018-03-10 09:55
Duplicate of #2731.

**Closed by PeterShaggyNoble** 2018-03-10 09:55 UTC
