### ISSUE TITLE
Website performance

### ISSUE THREAD

**Issue by Badestrand** [Templarian/MaterialDesign#5160] opened 2020-05-17 03:31 UTC
Hi!

First, thank you for the great icon pack, I love it and use it a lot!

My issue is, I can barely use the website (http://materialdesignicons.com/) though. It feels like it eats all my laptop's performance which I have never experienced on any other website. I have a 2017 MacBook Air so not too shabby. But clicking anything or even hovering over an icon always takes a couple of seconds, sometimes I need to a minute or two (!) until the website is responsive again. I am sure this is not normal behaviour but some kind of bug? Maybe specific to MacOS or Google Chrome? Happy to supply more info if needed.

I am using the latest Google Chrome, Version 81.0.4044.138 on MacOS Mojave with 8GB RAM.

**Comment by Templarian** [comment] 2020-05-17 03:34
Duplicate of #5158

**Comment by Badestrand** [comment] 2020-05-17 03:35
Sorry, looked for a ticket like that but couldn't find any!

**Closed** 2020-05-17 03:35 UTC
Labels: Duplicate, Question

**Comment by Badestrand** [comment] 2020-05-17 03:37
Maybe you could leave #5158 open so people see it when they browse issues? That would have helped me at least to see that this is a known issue.

**Comment by Templarian** [comment] 2020-05-17 03:46
👍 #5161
