### ISSUE TITLE
Octopus

### ISSUE THREAD

**Issue by lhoggatt17** [Templarian/MaterialDesign#6284] opened 2021-10-29 15:54 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To represent an octoprint instance.

### Give us an example of what this icon might look like.

Something like a basic version of the detailed octopus on the top right: [https://octoprint.org/](https://octoprint.org/)

**Comment by goyney** [comment] 2021-11-01 22:16
Duplicate of #5609.

**Closed by goyney** 2021-11-01 22:16 UTC
Labels: Icon Request
