### ISSUE TITLE
Many (if not all) icons have missing paths

### ISSUE THREAD

**Issue by LennyObez** [Templarian/MaterialDesign#1766] opened 2017-01-14 23:03 UTC
Hey there,

When I open one of the icon in SVG on Illustrator CC, I can check path with this simple shortcut: CTRL + Y / CMD + Y and many of the icons have missing paths.

**Comment by Templarian** [comment] 2017-01-15 03:00
By missing paths you mean not closed? The SVG files are often optimized for fill only, so all unnecessary data is removed. It may seem subtle, but it cuts down on the overall size.

Is this an issue for some reason?

**Comment by Templarian** [comment] 2017-01-19 18:05
Closing this issue out as I'm still not clear what the issue is. Let me know with more details and I'll reopen.

**Closed by Templarian** 2017-01-19 18:05 UTC
Labels: Question
