### ISSUE TITLE
Icon Suggest: Partly cloud and light rains icons

### ISSUE THREAD

**Issue by hoshri** [Templarian/MaterialDesign#2047] opened 2017-04-25 19:30 UTC
The weather icons are great, there are some missing icons for partly cloud and light rain. In most weather apps has the following icons:
Partly Cloud day - Cloud + sun
Party Cloud night - Cloud + moon
Light Rain day - Cloud with drops + sun
Light Rain night - Cloud with drops + moon

**Comment by kumvert** [comment] 2017-04-26 13:50
`weather-partlycloudy` could be used for "Partly Cloudy Day" and an icon already exists for Light Rain `weather-rainy` which may be used for both day and night. I think the only icon that is missing is "Partly Cloudy Night". Can you verify that this information is correct? Or did you need more specific icons?

**Comment by MrGrigri** [comment] 2017-05-05 20:21
Duplicate of #541

**Closed** 2017-05-05 20:22 UTC
Labels: Icon Request

**Comment by hoshri** [comment] 2017-05-16 10:22
I probably missed the weather-partlycloudy, thanks. So in this case only partly cloud night is missing. With regards to the light rain - in daily forecasts when you have only part of the time rain and also sun it is common to use an icon of rain + sun (and moon at night)
Here is an example of icons. Other weather services has similar icons as well.
https://openweathermap.org/weather-conditions
