### ISSUE TITLE
materialdesignicons.com website slow to load

### ISSUE THREAD

**Issue by SimonFricker** [Templarian/MaterialDesign#5158] opened 2020-05-15 11:41 UTC
The MaterialDesignIcons project has grown so much, there are so many icons! 

This is fantastic however when a user navigates to materialdesignicons.com the site attempts to load and render all icons. This causes a lot of lag for the site. 

Please consider dynamically loading the content as the user scrolls or to only allow for search.

**Comment by jinjie** [comment] 2020-05-15 13:25
It's dead slow recently! As a workaround, I use this to search for icons

`curl https://raw.githubusercontent.com/Templarian/MaterialDesign/master/meta.json | grep $ICON_NAME`

**Comment by goyney** [comment] 2020-05-15 13:30
Come on people, it's like you're not even trying anymore. We're painfully aware and @Templarian is working very hard on a new site. Patience.

Duplicate of #5120, #5033, #4921, #4894, #3322, etc.

**Closed by goyney** 2020-05-15 13:30 UTC
Labels: Bug

**Comment by goyney** [comment] 2020-05-15 13:31
> It's dead slow recently! As a workaround, I use this to search for icons
> 
> `curl https://raw.githubusercontent.com/Templarian/MaterialDesign/master/meta.json | grep $ICON_NAME`

Your workaround should be use one of the official Chrome or Firefox extensions: https://chrome.google.com/webstore/detail/materialdesignicons-picke/edjaedpifkihpjkcgknfokmibkoafhme

**Comment by jinjie** [comment] 2020-05-15 13:33
> > It's dead slow recently! As a workaround, I use this to search for icons
> > `curl https://raw.githubusercontent.com/Templarian/MaterialDesign/master/meta.json | grep $ICON_NAME`
> 
> Your workaround should be using one of the official Chrome or Firefox extensions: https://chrome.google.com/webstore/detail/materialdesignicons-picke/edjaedpifkihpjkcgknfokmibkoafhme

Cool! I didn't even know this exists! Thanks man.

**Comment by Templarian** [comment] 2020-05-15 15:53
@SimonFricker / @jinjie Due to the amount of features on the current site and our stats show they get used tens of thousands of times a day, so re-releasing without those features while faster would not benefit a lot of those users.

The new site will load in ~3sec on first load and ~1sec on the next loading. We can't wait to show more. It will also work butter smooth on mobile (even if we add 10k or 20k icons).

**Comment by VityaSchel** [comment] 2021-11-16 16:31
> @SimonFricker / @jinjie Due to the amount of features on the current site and our stats show they get used tens of thousands of times a day, so re-releasing without those features while faster would not benefit a lot of those users.
> 
> The new site will load in ~3sec on first load and ~1sec on the next loading. We can't wait to show more. It will also work butter smooth on mobile (even if we add 10k or 20k icons).

Any news on this? Site still takes minutes to load 🥲

**Comment by goyney** [comment] 2021-11-16 17:28
Yeah, status updates are in the pinned thread, which one was posted 3 days ago.

https://github.com/Templarian/MaterialDesign/issues/5161
