### ISSUE TITLE
Curtains

### ISSUE THREAD

**Issue by IanAdd** [Templarian/MaterialDesign#4568] opened 2019-11-03 22:17 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Similar to window-open-variant.
Ideal would be two - curtain open and curtain closed. 

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment] 2019-11-03 22:20
Try not to delete the template when submitting issues. ✔️ (edited back)

**Comment by MrGrigri** [comment] 2019-11-04 16:28
Duplicate of #2523

**Closed by MrGrigri** 2019-11-04 16:28 UTC
Labels: Duplicate, Home Assistant, Icon Request
