### ISSUE TITLE
Safe?

### ISSUE THREAD

**Issue by wardl895** [Templarian/MaterialDesign#2959] opened 2018-03-26 15:59 UTC
Hi there, im looking for a "safe" icon, e.g. storage of various items keys, money etc.

I did look but could not find one? Any idea's?

I did notice there are icons like cannabis etc so found it made sense to suggest such an icon such as a Safe

Regards,
   Richard.

**Comment by PeterShaggyNoble** [comment] 2018-03-26 16:00
This is a duplicate of #1897.

**Closed by PeterShaggyNoble** 2018-03-26 16:00 UTC

**Comment by wardl895** [comment] 2018-03-26 16:44
Ohh i cant seem to find it in the search MDI website? and looking at that "Thread?" it was october last year ?
Regards,
   Richard.

**Comment by PeterShaggyNoble** [comment] 2018-03-26 16:54
It hasn't been added yet.
