### ISSUE TITLE
api,support  #170

### ISSUE THREAD

**Issue by jayakrishnancn** [Templarian/MaterialDesign#1008] opened 2016-01-30 06:53 UTC
api support #280

**Comment by Templarian** [comment] 2016-01-30 07:01
Do you have an example?

**Comment by jayakrishnancn** [comment] 2016-01-30 07:37
![api_img](https://cloud.githubusercontent.com/assets/12905670/12694388/5356f5b4-c752-11e5-8458-17957f737a46.png)
 something like this may be

**Comment by PeterShaggyNoble** [comment] 2018-03-02 11:51
Closing as a duplicate of #574

**Closed by PeterShaggyNoble** 2018-03-02 11:51 UTC
Labels: Icon Request :pencil2:
