### ISSUE TITLE
Extension of the Window-Shutter icon

### ISSUE THREAD

**Issue by ElectricalSt0rm** [Templarian/MaterialDesign#7129] opened 2023-06-10 17:48 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

If I want my shutter halfway down I would like to press a button with a WindowShutter icon with 2 blades.
If I want my shutter 3/4 closed I would like to press a button with a WindowShutter icon with 3 blades.
etc...

### Give us an example of what this icon might look like.

The classic Window Shutter icon but one with no blades (or half a blade), one with 2 blades and one with 3 blades.
There is one with 2 blades but it has an exclamation mark.

**Comment by mririgoyen** [comment] 2023-06-10 18:09
Duplicate of #5733 #5872 #6277 #6740, #6754.

**Closed** 2023-06-10 18:09 UTC
Labels: Icon Request, Duplicate
