### ISSUE TITLE
Truck outlined

### ISSUE THREAD

**Issue by dionysiosarvanitis** [Templarian/MaterialDesign#4616] opened 2019-11-18 12:18 UTC
https://material.io/resources/icons/?icon=local_shipping&style=outline

**Comment by JamesCoyle** [comment] 2019-11-18 12:47
Duplicate of #4579

**Closed by JamesCoyle** 2019-11-18 12:47 UTC
Labels: Icon Request

**Comment by Templarian** [comment] 2019-11-24 04:23
@dionysiosarvanitis Just a heads up this was added and will be in 4.7 release.
