### ISSUE TITLE
callcenter worker 

### ISSUE THREAD

**Issue by Epiqa** [Templarian/MaterialDesign#2966] opened 2018-03-26 18:28 UTC
Hi, is possible to do a worker with a phone like this:

![whatsapp image 2018-03-26 at 3 24 17 pm](https://user-images.githubusercontent.com/30297288/37925203-6009b034-310a-11e8-9c71-0e0ac5ebffa2.jpeg)

Thanks!

**Comment by PeterShaggyNoble** [comment] 2018-03-26 19:58
This is a duplicate of #2474.

**Closed by PeterShaggyNoble** 2018-03-26 19:58 UTC
