### ISSUE TITLE
Horse & Horse Rider

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5314] opened 2020-07-10 23:52 UTC
Sorry to revisit the horse icon, but I've created a couple options that may work. This issue relates to #174, #3550, #4459, and #5021. Not sure if _horse-rider_ is a good icon name for the second icon. _horse-variant_ may be better.

## Preview

![horse](https://user-images.githubusercontent.com/1837101/87211128-46cec500-c2d5-11ea-9417-a0891f3d5800.png)
![horse-rider](https://user-images.githubusercontent.com/1837101/87211127-45050180-c2d5-11ea-8101-25401abc46d7.png)

## Zip Download

[horse-icons.zip](https://github.com/Templarian/MaterialDesign/files/4905928/horse-icons.zip)

**Comment by goyney** [comment] 2020-07-12 19:41
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/174. Please search before posting new issues. If you have a contribution, post it on the original issue.

**Closed by goyney** 2020-07-12 19:41 UTC
Labels: Contribution, Icon Request
