### ISSUE TITLE
vespa scooter

### ISSUE THREAD

**Issue by mohamadsalari** [Templarian/MaterialDesign#4265] opened 2019-07-23 19:37 UTC
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
![vespa_delivery](https://user-images.githubusercontent.com/53234803/61741620-8b044500-ada6-11e9-9f18-4be44d15ce49.png)
[vespa_delivery.zip](https://github.com/Templarian/MaterialDesign/files/3423788/vespa_delivery.zip)

**Comment by GreenTurtwig** [comment] 2019-07-23 19:58
Duplicate of https://github.com/Templarian/MaterialDesign/issues/2634

**Closed by GreenTurtwig** 2019-07-23 19:58 UTC
Labels: Contribution, Icon Request
