### ISSUE TITLE
Tunnel Icon

### ISSUE THREAD

**Issue by GovernmentPlates** [Templarian/MaterialDesign#1895] opened 2017-02-25 14:30 UTC
Would it be possible to get an icon that represents a tunnel? Maybe something similar to the one below?

![256px-pictograms-nps-misc-tunnel-2 svg](https://cloud.githubusercontent.com/assets/7736654/23331887/164a1d52-fb6f-11e6-963b-f209640339a5.png)

**Comment by GreenTurtwig** [comment] 2017-02-25 15:31
Best I could come up with, the fact it's *sort of* 3D isn't the best...
[tunnel.zip](https://github.com/Templarian/MaterialDesign/files/801288/tunnel.zip)
![tunnel](https://cloud.githubusercontent.com/assets/15905797/23332309/6bf505aa-fb6f-11e6-955c-d2cfef88732f.png)
![screenshot_2017-02-25_15-30-02](https://cloud.githubusercontent.com/assets/15905797/23332310/6d971d58-fb6f-11e6-95d0-a3bce96adc24.png)

**Comment by dintendocoltd** [comment] 2017-02-25 15:35
Looking good 👍

**Comment by JamesCoyle** [comment] 2017-02-26 19:18
What about a stone arch instead?

**Comment by dintendocoltd** [comment] 2017-07-03 11:22
@JamesCoyle I prefer the first one by @GreenTurtwig 

Maybe the stone arch tunnel variant could be named something like `tunnel-variant`?

**Comment by JamesCoyle** [comment] 2017-07-03 11:47
The issue is that material icons cannot incorporate dimensionality.

I'd go something like this but it would need adjusting to reduce the detail:
![image](https://user-images.githubusercontent.com/10384436/27791399-ba212f06-5fec-11e7-8eab-efc8a30b19aa.png)

Maybe along the lines of this: 
![image](https://user-images.githubusercontent.com/10384436/27791582-aef03e6e-5fed-11e7-984a-898c2fa500be.png)

**Comment by PeterShaggyNoble** [comment] 2018-09-14 08:29
@dintendocoltd, we'll close this once the icon has been added or we've decided it can't satisfactorily be represented while adhering to MD guidlines.

**Comment by goyney** [comment] 2018-11-25 05:40
Removing the Contribution label since no SVG files are present in this thread.

**Comment by Xenomorph99** [comment] 2020-11-05 03:52
Here's two designs based on @JamesCoyle recommendation. It kind of works, but feels like it's not quite there yet.

![tunnel-a](https://user-images.githubusercontent.com/1837101/98195603-653d7980-1edf-11eb-8069-eb020726a0f8.png)
![tunnel-b](https://user-images.githubusercontent.com/1837101/98195604-65d61000-1edf-11eb-8765-b9bd75de821a.png)
![tunnel-outline-a](https://user-images.githubusercontent.com/1837101/98195605-65d61000-1edf-11eb-87be-851c030c72a8.png)
![tunnel-outline-b](https://user-images.githubusercontent.com/1837101/98195606-666ea680-1edf-11eb-8f38-6a8a18b38587.png)
[tunnel.zip](https://github.com/Templarian/MaterialDesign/files/5491875/tunnel.zip)

**Comment by jhil** [comment] 2020-12-19 00:56
Need this one for a personal project, so I worked on some very simple options. I think they each serve a helpful purpose!

![image](https://user-images.githubusercontent.com/2228347/102676262-f4ce7d00-4159-11eb-98d8-542a672bce8c.png)
![image](https://user-images.githubusercontent.com/2228347/102676323-470f9e00-415a-11eb-8d3f-e91d51e96908.png)
![image](https://user-images.githubusercontent.com/2228347/102676269-fc8e2180-4159-11eb-9bc4-0791f3eed857.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/5718672/Archive.zip)

**Comment by goyney** [comment] 2021-09-01 22:32
[![tunnel](https://materialdesignicons.com/icon/tunnel)](https://materialdesignicons.com/icon/tunnel)[![tunnel-outline](https://materialdesignicons.com/icon/tunnel-outline)](https://materialdesignicons.com/icon/tunnel-outline)

**Closed by goyney** 2021-09-01 22:32 UTC
Labels: Icon Request, Contribution
