### ISSUE TITLE
Fleur de Lys

### ISSUE THREAD

**Issue by Emrin** [Templarian/MaterialDesign#4688] opened 2019-12-21 10:11 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Examples

![image](https://user-images.githubusercontent.com/23482165/71306584-88a02880-23e2-11ea-81cc-c0f02482a824.png)
Any of these would do

**Comment by Croutonix** [comment] 2019-12-23 20:03
[![fleur-de-lys](https://user-images.githubusercontent.com/18645219/71378200-fe4bf600-2594-11ea-92ec-86f6d4e5888f.png)](https://github.com/Templarian/MaterialDesign/files/3996126/fleur-de-lys.zip)
```text
M12 2S9 4 9 7s2 5 2 9h-1s0-2-1-4c-2-4-6-2-6 1s2 3 2 3c0-3 3.5-3 3.5 0H7v2h3.5L9 20s1 1 2 0l1 2 1-2c1 1 2 0 2 0l-1.5-2H17v-2h-1.5c0-3 3.5-3 3.5 0 0 0 2 0 2-3s-4-5-6-1c-1 2-1 4-1 4h-1c0-4 2-6 2-9s-3-5-3-5z
```

**Comment by goyney** [comment] 2019-12-26 02:35
Duplicate of #2587.

**Closed by goyney** 2019-12-26 02:35 UTC
Labels: Icon Request
