### ISSUE TITLE
Bug: Advance exporting an icon at #00E676 results in #000000

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#2518] opened 2017-10-13 17:52 UTC
Here is what the advance export GUI shows: 

![screenshot 2017-10-13 at 1 50 54 pm](https://user-images.githubusercontent.com/18021678/31559138-993225ee-b01d-11e7-9df5-a7a97a4a95d3.png)

And here is the file I get:

![spotify-g-a400](https://user-images.githubusercontent.com/18021678/31559129-9270fcc6-b01d-11e7-9b7e-2044e4f9c963.png)

I checked this for multiple icons _and_ for various hex does similar to #00E676.

**Comment by Templarian** [comment] 2017-10-13 20:47
Will investigate this shortly. Hmm...

Thanks for bringing it to my attention.

**Comment by PeterShaggyNoble** [comment] 2017-10-27 17:38
@k5cents, I recently added a tool for exporting PNGs to [my sandbox site](https://petershaggynoble.github.io/MDI-Sandbox/) that might serve as a stopgap for you while the issue is being investigated. To access it, click on an icon and then hit `Download PNG` in the sidebar.

**Comment by goyney** [comment] 2020-08-05 02:41
This won't be an issue when the new site (#5161) is released, which is getting pretty close. We're not going to try and fix the old site anymore since it's going away. Closing.

**Closed by goyney** 2020-08-05 02:41 UTC
Labels: Bug, Site Feature
