### ISSUE TITLE
Seashell

### ISSUE THREAD

**Issue by mariovials** [Templarian/MaterialDesign#7302] opened 2023-11-22 19:44 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To represent the marine animal category "mollusks".
![image](https://github.com/Templarian/MaterialDesign/assets/1584766/3d99c59f-e72a-48fb-8491-8945b3535f5a)

### Give us an example of what this icon might look like.

A menu with animals by categories: mammals, birds, fish, mollusks, etc.

**Comment by mririgoyen** [comment] 2023-11-22 20:12
Dupe of #3780.

**Closed by mririgoyen** 2023-11-22 20:12 UTC
Labels: Icon Request
