### ISSUE TITLE
vk icon

### ISSUE THREAD

**Issue by voldser** [Templarian/MaterialDesign#6479] opened 2022-02-25 20:07 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

VK is a popular social network, an analogue of Facebook, with more than 500 million users. You can visit vk.com to learn more

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/59465471/155787031-e86200e0-757d-45c3-9661-984f021cbc6c.png)

### Upload the icon source.

[vk.zip](https://github.com/Templarian/MaterialDesign/files/8144268/vk.zip)

**Comment by goyney** [comment] 2022-02-25 20:10
Duplicate of #6478.

**Closed by goyney** 2022-02-25 20:10 UTC
Labels: Icon Request, Contribution
