### ISSUE TITLE
Polymer Bower html file

### ISSUE THREAD

**Issue by Adryd** [Templarian/MaterialDesign#1263] opened 2016-06-02 14:10 UTC
Suggestion: add the 'mdi.html' file to the main repository so it's easier for bower+polymer users to install

**Comment by Templarian** [comment] 2016-06-02 18:07
Duplicate of #791.

But I want to add some details clearing up why this hasn't shown any progress lately. The total file size is over 500kb at the moment to include all the icons. We need to look into a way to more effectively generate this file most likely via grunt/gulp to include just the icons the user needs.

**Closed by Templarian** 2016-06-02 18:07 UTC
Labels: Duplicate
