### ISSUE TITLE
Poison Icon

### ISSUE THREAD

**Issue by IamThePeter** [Templarian/MaterialDesign#1207] opened 2016-05-02 14:23 UTC
I find it odd that there is no poison (or pirate) icon. May i suggest something like this:

http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/simple-black-square-icons-signs/127573-simple-black-square-icon-signs-warning-poison1.png

**Comment by Templarian** [comment] 2016-05-02 15:08
I find it very odd also. I'm going to group this with the medical icons. We need to work on getting more medical related icons in.

Duplicate of #147

**Closed by Templarian** 2016-05-02 15:08 UTC
Labels: Duplicate
