### ISSUE TITLE
Icon for zip file

### ISSUE THREAD

**Issue by chinmay-amuratech** [Templarian/MaterialDesign#2022] opened 2017-04-17 10:08 UTC

**Comment by JapanYoshi** [comment] 2017-04-17 10:12
How do you miss [this](https://materialdesignicons.com/icon/zip-box)?!

**Comment by chinmay-amuratech** [comment] 2017-04-17 11:10
No. Not this one.
I would rather go with the icon of windows zip file or ubuntu's zip file.
Never mind. For now I'm using the one you shared. Thanks. :+1:

**Comment by PeterShaggyNoble** [comment] 2017-04-17 12:15
Closing as a duplicate of #1288.

**Closed by PeterShaggyNoble** 2017-04-17 12:15 UTC
