### ISSUE TITLE
new sort ordering icons

### ISSUE THREAD

**Issue by borit22** [Templarian/MaterialDesign#4653] opened 2019-12-08 14:39 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

1. For alpha sort ordering(A -> Z, Z -> A)
2. For date sort ordering(Past -> Future, Future -> Past)
2. For number sort ordering(1 -> 9, 9 -> 1)

## Examples
1. ![1_1](https://user-images.githubusercontent.com/56121013/70391361-76d38400-19e5-11ea-894f-c2ac78eb1d5c.png) ![1_2](https://user-images.githubusercontent.com/56121013/70391375-8fdc3500-19e5-11ea-8cfb-a3ad8160d231.png)

2. ![2_1](https://user-images.githubusercontent.com/56121013/70390994-3245e980-19e1-11ea-9b23-111e76ad979e.png) ![2_2](https://user-images.githubusercontent.com/56121013/70391029-8ea90900-19e1-11ea-992a-e2244d002b20.png)

3. ![3_1](https://user-images.githubusercontent.com/56121013/70391341-2a884400-19e5-11ea-9354-e2904777fdcb.png) ![3_2](https://user-images.githubusercontent.com/56121013/70391331-0b89b200-19e5-11ea-9b61-0c4879b894c5.png)

**Comment by Templarian** [comment] 2019-12-08 20:39
Duplicate of #4449

We just need to add them as they are already approved.

**Closed by Templarian** 2019-12-08 20:39 UTC
Labels: Icon Request
