### ISSUE TITLE
HTML Entities for webfont

### ISSUE THREAD

**Issue by GRA0007** [Templarian/MaterialDesign#758] opened 2015-10-19 03:41 UTC
The webfont needs a cheatsheet with the html entities for each icon, in case you want to directly type in an icon in a html document without using the css.

**Comment by Templarian** [comment] 2015-10-19 03:51
For the webfont to function the characters need to be wrapped in tags with the `class="mdi"` attribute. This font uses the extended unicode values that are shared between fonts and could represent any character.

Marked as a duplicate of #127.

**Closed by Templarian** 2015-10-19 03:51 UTC
Labels: Duplicate
