### ISSUE TITLE
robotic-lawnmower

### ISSUE THREAD

**Issue by iMarkus** [Templarian/MaterialDesign#2574] opened 2017-11-01 20:14 UTC
Lawnmowers are getting smarter and smarter. To use a dedicated icon for the current robotic lawnmower state an icon would be fine. Maybe one where the robot is in the charging station and another where it is.

![71yagh7ywdl _sl1500_](https://user-images.githubusercontent.com/12813354/32295420-868dee06-bf49-11e7-89da-e4a0e7683d1d.jpg)

**Comment by PeterShaggyNoble** [comment] 2017-11-01 20:37
Duplicate of #2522.

**Closed by PeterShaggyNoble** 2017-11-01 20:37 UTC

**Comment by iMarkus** [comment] 2017-11-01 20:46
oh sorry
