### ISSUE TITLE
Christmas tree icon request

### ISSUE THREAD

**Issue by gavyb** [Templarian/MaterialDesign#5694] opened 2020-12-11 12:25 UTC
I have:

- [X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like an icon to represent my Christmas Tree lights

## Examples

https://www.flaticon.com/free-icon/christmas-tree_1324667

**Comment by goyney** [comment] 2020-12-11 13:43
Duplicate of #5680.

**Closed by goyney** 2020-12-11 13:43 UTC
Labels: Icon Request
