### ISSUE TITLE
Weightlift

### ISSUE THREAD

**Issue by Yuanruili** [Templarian/MaterialDesign#4012] opened 2019-03-07 13:28 UTC
Olympic weightlift (clean-and-jerk)
![image](https://user-images.githubusercontent.com/12135487/53959903-3147fa80-40e5-11e9-864b-1b30fd108068.png)
[Clean-and-jerk.zip](https://github.com/Templarian/MaterialDesign/files/2941402/Clean-and-jerk.zip)

**Comment by goyney** [comment] 2019-03-07 13:38
See my comment on #4011.

**Comment by Yuanruili** [comment] 2019-03-07 13:43
Ok got it

**Comment by goyney** [comment] 2019-03-07 21:55
Closing as a duplicate of #4011.

**Closed by goyney** 2019-03-07 21:55 UTC
Labels: Icon Request :pencil2:
