### ISSUE TITLE
GU10 Downlight

### ISSUE THREAD

**Issue by Nalith** [Templarian/MaterialDesign#5389] opened 2020-07-30 18:38 UTC
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home automation software to indicate GU10 down lights.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment] 2020-07-31 02:18
Duplicate of #4597.

**Closed by goyney** 2020-07-31 02:18 UTC
Labels: Icon Request
