### ISSUE TITLE
Synthesizer related

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4346] opened 2019-08-20 00:58 UTC
I decided to make a bunch of synthesizer-related icons. Some were requested in #3036.

## Preview
`sine-wave`
![sine-wave](https://user-images.githubusercontent.com/8707990/63309047-a5472980-c338-11e9-900b-6f6917133fbe.png)
`cosine-wave`
![cosine-wave](https://user-images.githubusercontent.com/8707990/63309048-a6785680-c338-11e9-9a5d-d64ab4e6766f.png)

`square-wave` or `pulse-wave-square`
![square-wave](https://user-images.githubusercontent.com/8707990/63309050-a9734700-c338-11e9-975c-ee9ae7461806.png)
`pulse-wave-1` or `pulse-wave-wide`
![pulse-wave-1](https://user-images.githubusercontent.com/8707990/63309052-abd5a100-c338-11e9-8d16-830f3ea06b27.png)
`pulse-wave-2` or `pulse-wave-medium`
![pulse-wave-2](https://user-images.githubusercontent.com/8707990/63309053-ad06ce00-c338-11e9-8b4a-e1c4fea9bd89.png)
`pulse-wave-3` or `pulse-wave-narrow`
![pulse-wave-3](https://user-images.githubusercontent.com/8707990/63309056-ad9f6480-c338-11e9-8d47-8c5ed8ea576a.png)

`sawtooth-wave` variant 1
![sawtooth-wave](https://user-images.githubusercontent.com/8707990/63309057-aed09180-c338-11e9-9f43-1083cd8fc50b.png)
`sawtooth-wave` variant 2
![sawtooth-wave-variant](https://user-images.githubusercontent.com/8707990/63309058-b001be80-c338-11e9-9ad7-f26cc4ada729.png)

`triangle-wave`
![triangle](https://user-images.githubusercontent.com/8707990/63309225-58b01e00-c339-11e9-9de6-e9d6b4b70512.png)

`waveform` (requested in #4333)
![waveform](https://user-images.githubusercontent.com/8707990/63309060-b2641880-c338-11e9-87f4-7b75cb4db643.png)

`sound-pan`
![pan](https://user-images.githubusercontent.com/8707990/63309064-b42ddc00-c338-11e9-9b91-ad94bcf6a5c8.png)

## Zip Download

[synth-pack.zip](https://github.com/Templarian/MaterialDesign/files/3518197/synth-pack.zip)

**Comment by goyney** [comment] 2019-08-20 01:18
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/3036, but I'm going to close that one since this one has potential contributions.

We don't really need variants of each, we just need one standard version of each. Couple questions:
- `sine-wave` and `cosine-wave don't look very equal, is that intentional?
- `sawtooth-wave` and `triangle-wave` have a weird 1dp elbow, again intentional?
- I'm not a fan of that `waveform`, its too Minecraft-y. Don't think it solves #4333 either.

**Comment by goyney** [comment] 2019-08-20 01:21
My votes are for `sine-wave`, `cosine-wave`, `square-wave`, `sawtooth-wave` variant 2, and `triangle-wave`, once some of the concerns around them are cleared up.

**Comment by JapanYoshi** [comment] 2019-08-20 01:38
``sine-wave`` starts from a point where the slope is steep, but ``cosine-wave`` starts from a point where the slope is horizontal. So the underlying line is 2dp wider in ``cosine-wave`` to make the terminals fit the grid better.

I had to clip the top and bottom corners of ``sawtooth-wave`` and ``triangle-wave``, because they would have been too tall if they were left in.

I could whip up an alternative for ``waveform``, and make the blocky one stand for bit crush.

**Comment by goyney** [comment] 2019-08-20 03:30
Oops, think there was a misunderstanding when I asked about "`sine-wave` and `cosine-wave` don't look very equal".

![points](https://user-images.githubusercontent.com/1015040/63315410-1fe05c80-c2d9-11e9-907b-d613ed9245b8.jpg)

I mean these points look awkward. The crests look smooshed together and not like a smooth curve. And the ends of the `cosine` don't look quite right, almost skinnier than the rest of the line.

---

Also, when you get things fixed, can you please separate each contribution out into its own SVG. It's kind of a pain to dig through a single SVG with a bunch of layers. Also, use our preview generator so we can see things on the grid. Thanks! 😄

**Comment by JapanYoshi** [comment] 2019-08-20 05:21
Sine and Cosine were traced from an actual sine wave though? I'll tweak the inner edges for better appearance anyway...

![cosine](https://user-images.githubusercontent.com/8707990/63319447-74c5b680-c35d-11e9-865e-316da2dfa794.png)![sine](https://user-images.githubusercontent.com/8707990/63319448-74c5b680-c35d-11e9-9377-23787548da67.png)
____
Here's the updated, less blockier waveform.
![waveform](https://user-images.githubusercontent.com/8707990/63319539-cf5f1280-c35d-11e9-9d66-ae061a4ce3f0.png)
____
By the way, the preview generator doesn't work at all on my end. I'm piping the `d` I got from Inkscape's XML editor into this. It doesn't work either when I copy the `d` of the SVG from materialdesignicons.com. All that works is "WIP?" and "Action button".
![image](https://user-images.githubusercontent.com/8707990/63319415-5d86c900-c35d-11e9-8cf2-ffbf9249a675.png)

**Comment by goyney** [comment] 2019-08-20 14:33
> Sine and Cosine were traced from an actual sine wave though?

That's a good starting point, but we need icons to be Material to be included in the library.

**Comment by CoDEmanX** [comment] 2019-08-21 22:49
We might need to construct the path mathematically for an accurate result...

**Comment by goyney** [comment] 2020-05-08 03:04
`sine-wave` already exists as: (It is aliased)
[![current-ac](https://materialdesignicons.com/icon/current-ac)](https://materialdesignicons.com/icon/current-ac)

Added the others:
[![cosine-wave](https://materialdesignicons.com/icon/cosine-wave)](https://materialdesignicons.com/icon/cosine-wave)[![triangle-wave](https://materialdesignicons.com/icon/triangle-wave)](https://materialdesignicons.com/icon/triangle-wave)
[![sawtooth-wave](https://materialdesignicons.com/icon/sawtooth-wave)](https://materialdesignicons.com/icon/sawtooth-wave)[![square-wave](https://materialdesignicons.com/icon/square-wave)](https://materialdesignicons.com/icon/square-wave)
[![waveform](https://materialdesignicons.com/icon/waveform)](https://materialdesignicons.com/icon/waveform)

**Closed by goyney** 2020-05-08 03:04 UTC
Labels: Contribution, Icon Request
