### ISSUE TITLE
Dark mode icon

### ISSUE THREAD

**Issue by elselapatha** [Templarian/MaterialDesign#5807] opened 2021-01-21 19:17 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Dark mode representation icon (filled and oultined)

## Examples

like google material dark mode icon

**Comment by goyney** [comment] 2021-01-21 19:29
Duplicate of #5793.

**Closed by goyney** 2021-01-21 19:29 UTC
Labels: Icon Request
