### ISSUE TITLE
bag-personal-tag

### ISSUE THREAD

**Issue by mat2718** [Templarian/MaterialDesign#6559] opened 2022-04-22 19:20 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

outline icon version for property-tag. related to issue property-tag #6534 in upcoming icons milestone

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/22265388/164780177-4b0ff61a-4a70-4dcf-9db9-c6b17c846e4a.png)

### Upload the icon source.

[property-tag-outline (2).zip](https://github.com/Templarian/MaterialDesign/files/8543519/property-tag-outline.2.zip)

**Comment by Templarian** [comment] 2022-04-23 18:41
Renaming this as it would be called `bag-personal-tag` / `-outline`. Overlay modifiers are not outlined. That would still be solid.

**Comment by Ben-Heel** [comment] 2022-04-23 21:19
من الذي طلب هذا الرمز لم أطلب شي كل يوم رساله ولم أفهم ماهوا هذا الرمز انا مبدأ لا أزال اتعلم هل هناك تعليمات واضحه اكثر

**Comment by Templarian** [comment] 2022-04-26 03:14
Marking this one a duplicate of #6534

We can manage it in that issue.

**Closed by Templarian** 2022-04-26 03:14 UTC
Labels: Icon Request, Contribution
