### ISSUE TITLE
Here is my cyber-lights icon!!!

### ISSUE THREAD

**Issue by magranero** [Templarian/MaterialDesign#5537] opened 2020-09-25 12:05 UTC
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/18167085/94264846-c6188000-ff37-11ea-9d05-c0cdb765b785.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[cyber-lights.svg.zip](https://github.com/Templarian/MaterialDesign/files/5282617/cyber-lights.svg.zip)

**Comment by goyney** [comment] 2020-09-25 12:10
Duplicate of #5528.

**Closed by goyney** 2020-09-25 12:10 UTC
Labels: Contribution, Icon Request
