### ISSUE TITLE
Tire icon

### ISSUE THREAD

**Issue by scardinoandrea** [Templarian/MaterialDesign#5569] opened 2020-10-07 12:53 UTC
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/34484742/95332868-47fb9800-08ac-11eb-9581-c92addbe03b0.png)

## Zip Download

[tire.zip](https://github.com/Templarian/MaterialDesign/files/5340748/tire.zip)

**Comment by goyney** [comment] 2020-10-07 13:08
Duplicate of https://github.com/Templarian/MaterialDesign/issues/1308.

**Closed by goyney** 2020-10-07 13:08 UTC
Labels: Contribution, Icon Request
