### ISSUE TITLE
checkbox-marked-circle-outline with a plus

### ISSUE THREAD

**Issue by BUONJG** [Templarian/MaterialDesign#5942] opened 2021-04-20 12:41 UTC
Hello,

Please complete the checkbox icons with: https://www.gstatic.com/tasks/task-add-accent-light.svg

I would be usefull for adding a task in a todo list...

Regards,

I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon to add a task

## Examples

 https://www.gstatic.com/tasks/task-add-accent-light.svg

(checkbox-marked-circle-outline with a plus)

**Comment by achebotarev** [comment] 2021-09-09 13:58
This issue is similar to https://github.com/Templarian/MaterialDesign/issues/5636

**Comment by goyney** [comment] 2021-09-09 14:39
Yes, definitely a duplicate of #5636.

**Closed by goyney** 2021-09-09 14:39 UTC
Labels: Icon Request

**Comment by BUONJG** [comment] 2021-09-09 15:45
Yes, sorry the check on other issue is not easy...
Do you plan to integrate the icon requested on #5636?

Regards,
