### ISSUE TITLE
Different power sockets

### ISSUE THREAD

**Issue by GRA0007** [Templarian/MaterialDesign#752] opened 2015-10-14 22:37 UTC
Different power socket icons like the 'power-socket' icon, but for other countries, like seen on here: http://www.worldstandards.eu/electricity/plugs-and-sockets/
In particular type I from the link above ;)

**Comment by CoDEmanX** [comment] 2015-10-15 17:38
That seems very specific, and I'm not sure it will be recognizable at 24px. Also, some of them may look like smileys...

**Comment by GRA0007** [comment] 2015-10-16 00:49
Maybe, you don't really have to do anything but the 'main' power plugs (maybe you could do some more later if anyone else requests it) so that kinda comes down to the European and Australian plug.

**Comment by Templarian** [comment] 2015-10-16 00:58
It's always good to localize a application even the iconography so I'm going to say adding at least Europe and Australia would be a good idea.

This could be very important in home automation applications.

**Comment by quietmint** [comment] 2016-06-09 14:02
+1, at least for some version of this. I ended up here looking for something like [**fa-plug** from FontAwesome](http://fontawesome.io/icon/plug/)

**Comment by Templarian** [comment] 2017-02-18 05:48
I know this is older, but marking this as a duplicate of #1426 since that issue has contributions that will probably be added shortly. 😄

**Closed by Templarian** 2017-02-18 05:48 UTC
Labels: Icon Request
