### ISSUE TITLE
menu-close

### ISSUE THREAD

**Issue by psaulus13** [Templarian/MaterialDesign#7234] opened 2023-09-12 15:41 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To open the menu

### Give us an example of what this icon might look like.

Like the menu-open icon in the library but with arrow in the other side

**Comment by MrGrigri** [comment] 2023-09-14 16:14
This is a duplicate of #7071 and will be added with the next major release.

**Closed by MrGrigri** 2023-09-14 16:14 UTC
Labels: Icon Request, Duplicate
