### ISSUE TITLE
Open folder icon

### ISSUE THREAD

**Issue by ChrisNelsonPE** [Templarian/MaterialDesign#1835] opened 2017-02-03 20:35 UTC
There are lots of folders but they are all closed.

**Comment by JamesCoyle** [comment] 2017-02-03 20:41
As far as I can see it's impossible for us to create such an icon which follows the material guidelines. Do you have any ideas how it could be achieved without adding dimensionality?

**Comment by ChrisNelsonPE** [comment] 2017-02-03 20:49
The account-user has a squosh of dimensionality in that one user seems to be behind the other.

If you insist on flat-flat, the folder could be fully open with the tabbed back at the top and the notched front at the bottom.

**Comment by ChrisNelsonPE** [comment] 2017-02-03 20:52
book-open-page-variant has a page sticking out much as the front of a slightly-open folder would.

**Comment by MrGrigri** [comment] 2017-02-03 22:06
Duplicate of [#1645](https://github.com/Templarian/MaterialDesign/issues/1645) and [#1065](https://github.com/Templarian/MaterialDesign/issues/1065)

**Comment by PeterShaggyNoble** [comment] 2017-02-03 23:34
@ChrisNelsonPE, based on your comments, would `folder-multiple` not meet your needs?

![](https://materialdesignicons.com/icon/folder-multiple)

**Comment by Templarian** [comment] 2017-02-04 02:52
I'm closing all the folder open requests to conform with MD guidelines.

**Closed by Templarian** 2017-02-04 02:52 UTC
Labels: Duplicate, Needs More Information, Question

**Comment by ChrisNelsonPE** [comment] 2017-02-04 12:55
I'm not a fan of MD anyway but idea that it prevents you from creating a useful icon make me like it even less.

**Comment by Templarian** [comment] 2017-02-04 16:24
@ChrisNelsonPE https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/folder-open.svg (from Nov 29th).

We still include icons all the time in the repo that don't get community approval.

**Comment by Templarian** [comment] 2017-02-15 03:40
[![folder-open](https://materialdesignicons.com/icon/folder-open)](https://materialdesignicons.com/icon/folder-open)

😩

**Comment by GreenTurtwig** [comment] 2017-02-15 11:12
You finally gave in. :-P  
I totally agree that it just looks, odd... But now it's there if people need it at least.

**Comment by ChrisNelsonPE** [comment] 2017-02-15 11:54
Thank you!

**Comment by Inkata** [comment] 2017-03-03 22:41
In any event seems that the woff2 font as of NPM module mdi@1.8.36 does not contain the folder-open glyph.

Thanks!

**Comment by PeterShaggyNoble** [comment] 2017-03-03 23:28
@Inkata, it will be added in the next release; see https://materialdesignicons.com/history
