### ISSUE TITLE
Account w/ Shield

### ISSUE THREAD

**Issue by xubiod** [Templarian/MaterialDesign#2262] opened 2017-07-20 18:22 UTC
I used [this](http://editor.method.ac/) to make the icon, so this isn't the best it could be, but I though that Material Design could benefit from an icon like this. Method Editor also doesn't support "cutouts", so the shield is white and not transparent. I can't fix this with this tool, but I am going to get Inkscape later on my personal computer.

24x24:
![account-shield](https://user-images.githubusercontent.com/7144210/28432697-e2de3246-6d56-11e7-8e48-029d691b6e3e.png)

[account-shield.zip](https://github.com/Templarian/MaterialDesign/files/1163328/account-shield.zip)

**Comment by MrGrigri** [comment] 2017-07-20 19:25
Duplicate of #1742.

**Comment by xubiod** [comment] 2017-07-20 21:53
Bummer, I didn't see that when I was making it.

**Comment by MrGrigri** [comment] 2017-07-20 21:56
It doesn't exist in the repo yet but could be.

**Comment by JamesCoyle** [comment] 2017-07-20 22:22
Closing in favor of #1742.

**Closed by JamesCoyle** 2017-07-20 22:22 UTC
Labels: Consider Closing, Duplicate
