### ISSUE TITLE
Moneybag icon

### ISSUE THREAD

**Issue by seddik** [Templarian/MaterialDesign#5051] opened 2020-04-19 01:20 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

- Payments
- Financial stuff

## Examples

![image](https://user-images.githubusercontent.com/6674347/79676990-fcf9a580-81e3-11ea-8792-6b61309376b4.png)

**Comment by Templarian** [comment] 2020-04-19 03:05
Duplicate of #338

We don't add currency symbols to icons as it makes internationalization difficult.

**Closed by Templarian** 2020-04-19 03:05 UTC
Labels: Icon Request

**Comment by seddik** [comment] 2020-04-19 13:30
@Templarian in my opinion, that's not a reason to ignore theses types of icon, you already have home-currency_usd and cash-usd. an empty sack is meaningless. 

I see a currency moneybag is a must.

**Comment by Templarian** [comment] 2020-04-19 20:39
That one was added before we started enforcing this policy after 3.x. While it's a useful icon it's not one we can nicely support with all the various currency symbols.

Try and look for other icons in the set that might work better. There are some more generic cash icons. Like `account-cash` to show a persons financials.
