### ISSUE TITLE
License plate europe

### ISSUE THREAD

**Issue by Franki1986** [Templarian/MaterialDesign#3917] opened 2019-02-18 13:07 UTC
Hello,

I would like to use an europe license plate no.

[license-plate-eur.zip](https://github.com/Templarian/MaterialDesign/files/2875709/license-plate-eur.zip)

**Comment by PeterShaggyNoble** [comment] 2019-02-18 17:41
Duplicate of #712

**Closed by PeterShaggyNoble** 2019-02-18 17:41 UTC
Labels: Icon Request :pencil2:

**Comment by Franki1986** [comment] 2019-02-18 20:50
What is the reason for rejecting this or the other icon?

**Comment by goyney** [comment] 2019-02-18 20:56
This was closed because there is already a request for a license plate. You're better to ask your questions on the original issue.

**Comment by Templarian** [comment] 2019-02-18 22:47
@Franki1986 Looks like we closed it due to it not being legible at smaller sizes. Also that licenses look different in every country.

**Comment by CoDEmanX** [comment] 2019-03-04 08:00
@Templarian How about changing the *Language Conflict* label to *Language / Cultur Dependent* and add it here?
