### ISSUE TITLE
steam iron

### ISSUE THREAD

**Issue by rohamishop** [Templarian/MaterialDesign#6134] opened 2021-08-18 20:51 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples
https://img.icons8.com/ios/452/iron.png
Include any example images so we know what the icon should look like.

**Comment by goyney** [comment] 2021-08-19 00:21
Duplicate of #2752.

**Closed by goyney** 2021-08-19 00:21 UTC
Labels: Icon Request

**Comment by rohamishop** [comment] 2021-08-20 22:46
Reply for #2752.
Sorry I can find this Icon png or svg any where but there is not in "material design icon Library" !!!
I need there to copy and use just name for my Wordpress site. I don't need html code or image.
please look at my site menu. I used some compatible icon in material design site but the other not.
https://rohamishop.com/
thanks you so much
