### ISSUE TITLE
bill

### ISSUE THREAD

**Issue by Tarilonte** [Templarian/MaterialDesign#3078] opened 2018-04-18 01:09 UTC
bill icon
[bill-thick.zip](https://github.com/Templarian/MaterialDesign/files/1922120/bill-thick.zip)

![image](https://user-images.githubusercontent.com/29761068/38906243-c9b352be-428b-11e8-9cc5-1e895481bec5.png)

**Comment by GreenTurtwig** [comment] 2018-04-18 10:05
The dollar sign will be lost at 1x, as will likely happen to the folded corner.
The `receipt` icon should work in most cases:
[![](https://materialdesignicons.com/icon/receipt)](https://materialdesignicons.com/icon/receipt)

**Comment by PeterShaggyNoble** [comment] 2018-04-18 10:08
This is also a duplicate of #1010.

**Closed by PeterShaggyNoble** 2018-04-18 10:08 UTC
Labels: Contribution :heavy_check_mark:, Icon Request :pencil2:
