### ISSUE TITLE
cradle

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#4617] opened 2019-11-19 08:11 UTC
On request https://github.com/Templarian/MaterialDesign/issues/4493

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![cradle-outline](https://user-images.githubusercontent.com/5179676/69127462-f17a4500-0ab2-11ea-977e-bff46e70b98e.png)
![cradle-filled](https://user-images.githubusercontent.com/5179676/69128328-b6791100-0ab4-11ea-8486-64ac7bf05626.png)

## Zip Download
[cradle-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3862536/cradle-outline.svg.zip)
[cradle-filled.svg.zip](https://github.com/Templarian/MaterialDesign/files/3862620/cradle-filled.svg.zip)

**Comment by goyney** [comment] 2019-11-19 20:11
Not sure about that angle on the cover. I think I would make it straight, much like our `baby-carriage`.

[![baby-carriage](https://materialdesignicons.com/icon/baby-carriage)](https://materialdesignicons.com/icon/baby-carriage)

**Comment by goyney** [comment] 2019-11-19 20:12
Wait, this is a duplicate of #4493. Please go add your contributions to that issue.

**Closed by goyney** 2019-11-19 20:12 UTC
Labels: Contribution, Icon Request
