### ISSUE TITLE
Customer - Trade - Contract (ICon request)

### ISSUE THREAD

**Issue by baothanh591** [Templarian/MaterialDesign#1388] opened 2016-07-28 09:40 UTC
I would love to have these item
Customer - Trade - Contract

Please add them too

**Comment by baothanh591** [comment] 2016-07-28 10:24
![signature](https://cloud.githubusercontent.com/assets/8986785/17209603/1339c2b2-54e8-11e6-96b6-47259e6e5bdc.png)
![hands-salutation-of-two-businessmen](https://cloud.githubusercontent.com/assets/8986785/17209602/133987a2-54e8-11e6-8de4-94c924ee39f5.png)

**Comment by Templarian** [comment] 2016-07-28 16:36
Duplicate of #1040 and #330.

Material Design follows a very specific guidelines for each icon, but we can use these as reference.

**Closed by Templarian** 2016-07-28 16:36 UTC
