### ISSUE TITLE
Tire

### ISSUE THREAD

**Issue by mattcorner** [Templarian/MaterialDesign#4995] opened 2020-03-29 07:28 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
To distinguish between car parts. 

## Examples
So I've seen that a lot of tire requests have been closed because its hard to create something that looks like a tire in 2D without looking like a wheel, etc. I propose that the 'car-tire-alert' icon is released as car-tire without the alert symbol. For anyone using something with a tire icon, they should recognise the cross section of a tyre, and its a symbol that is universally used on dashboards of vehicles worldwide.

**Comment by Templarian** [comment] 2020-03-29 20:13
Duplicate of #1308

**Closed by Templarian** 2020-03-29 20:13 UTC
Labels: Icon Request

**Comment by mattcorner** [comment] 2020-03-30 00:52
Apologies, had misread that issue and thought it had been closed.
