### ISSUE TITLE
Mobile Network Signal Quality

### ISSUE THREAD

**Issue by BornToBeRoot** [Templarian/MaterialDesign#2901] opened 2018-03-12 17:48 UTC
Hello,

would be great if there are connection quality icons for wifi. Like them from google material: https://www.materialui.co/icon/signal-wifi-3-bar

Or something like this: 
![wifi](https://user-images.githubusercontent.com/16019165/37300245-c1a2794c-2625-11e8-95b7-7abb3b6e77b3.PNG)

But with the signal strengh from 0-4 (like the microsoft windows own wifi)

Greetings

**Comment by PeterShaggyNoble** [comment] 2018-03-12 17:51
WiFi quality is a duplicate of #586. Leaving this open as a request for mobile network signal quality icons.

**Comment by MrGrigri** [comment] 2018-03-12 19:19
There is an issue with this. Google handles it by opacifying the weak bars and keeping the stong bars fully opaque. With our `signal` icon, each bar is 3 pixels wide and MD guidelines state that outlines are supposed to be 2 pixels wide (4 pixels total with both sides). This cannot be accomplished in the constraints we have (24x24 pixels).

**Comment by MrGrigri** [comment] 2018-03-12 20:27
Here is what the community decided on. The outline is 1.5 pixels thin instead of the standard 2 pixels.

__note:__ Because of the MD guidelines, they are visually not physically centered to stay on the pixel grid.

![image](https://user-images.githubusercontent.com/4528551/37307271-fe8287ec-25ff-11e8-8708-cd0db6e13316.png) ![image](https://user-images.githubusercontent.com/4528551/37307454-a9f5ae60-2600-11e8-91b5-d0ce643bc50b.png) ![image](https://user-images.githubusercontent.com/4528551/37307498-c9bd7cc8-2600-11e8-969a-1b0ad131679c.png) ![image](https://user-images.githubusercontent.com/4528551/37307514-d6213ffe-2600-11e8-80aa-1b2f1169b8c3.png)

[signal-cellular.zip](https://github.com/Templarian/MaterialDesign/files/1804429/signal-cellular.zip)

**Comment by BornToBeRoot** [comment] 2018-03-12 22:25
They are great. With 24px it is not possible to add a 4 bar? Cause the Windows wifi signal is from 0 to 4.

**Comment by CoDEmanX** [comment] 2018-03-12 23:13
![network-cell-outline](https://user-images.githubusercontent.com/1309249/37314088-80664882-2652-11e8-952d-045cef9fe1aa.png)
[network-cell-outline.zip](https://github.com/Templarian/MaterialDesign/files/1804851/network-cell-outline.zip)

![network-cell-outline-alert](https://user-images.githubusercontent.com/1309249/37314190-172192cc-2653-11e8-9848-e59dd24d8843.png)
[network-cell-outline-alert.zip](https://github.com/Templarian/MaterialDesign/files/1804856/network-cell-outline-alert.zip)

![network-cell-off](https://user-images.githubusercontent.com/1309249/37314222-4376628a-2653-11e8-8557-2086d5e4f3fa.png)
[network-cell-off.zip](https://github.com/Templarian/MaterialDesign/files/1804858/network-cell-off.zip)

**Comment by BornToBeRoot** [comment] 2018-03-13 07:47
Yeah something like this.

**Comment by Templarian** [comment] 2018-03-14 02:22
![image](https://user-images.githubusercontent.com/338885/37379964-5a2453a0-2704-11e8-95c2-5397ad664091.png) ![image](https://user-images.githubusercontent.com/338885/37380015-8c14971c-2704-11e8-81b3-449606a4d073.png)

Agreeing that 3 bars would be the only option, as you can see 4 bars looks 'odd', and the 1px which we don't allow does not fit with the other designs.

**Comment by BornToBeRoot** [comment] 2018-03-14 08:27
You are right, the first example looks terrible 😄 

But the icons from @CoDEmanX may look great with 0 to 4 bars.

**Comment by Templarian** [comment] 2018-04-14 16:33
All 12 of these have been added (too long to link each inline, but they are there).

**Comment by PeterShaggyNoble** [comment] 2018-04-16 11:29
`network-strength-off-outline` was added twice and `network-strength-alert` should be renamed as `network-strength-4-alert`, for consistency with the WIFI icons.

**Comment by Templarian** [comment] 2018-04-16 15:17
Fixed.

**Closed by Templarian** 2018-04-16 15:17 UTC
Labels: Contribution :heavy_check_mark:
