### ISSUE TITLE
Cash register icon

### ISSUE THREAD

**Issue by puttykitties** [Templarian/MaterialDesign#2845] opened 2018-02-26 09:25 UTC
Curious how a cash register icon is missing when we have all the payments icon prepared.

It would really be helpful if you're doing ecomm or financial apps.

**Comment by PeterShaggyNoble** [comment] 2018-02-26 11:44
Thanks for the request but this is a duplicate of #850.

Don't forget to search existing issues before opening new ones.

**Closed by PeterShaggyNoble** 2018-02-26 11:44 UTC
