### ISSUE TITLE
cheatsheet not working

### ISSUE THREAD

**Issue by volarname** [Templarian/MaterialDesign#6077] opened 2021-07-22 12:16 UTC
cheatsheet not working on https://materialdesignicons.com/ anymore, please fix

**Comment by ozgurg** [comment] 2021-07-22 13:40
Until they reply, you can use this:: https://pictogrammers.github.io/@mdi/font/5.4.55/

**Comment by goyney** [comment] 2021-07-27 04:13
Duplicate of #6036.

**Closed by goyney** 2021-07-27 04:13 UTC
Labels: Bug
