### ISSUE TITLE
macaroni

### ISSUE THREAD

**Issue by MattiasTR** [Templarian/MaterialDesign#4177] opened 2019-06-04 09:17 UTC
Can be used for indicating the kinds of food that need to be bought when going to the store next time. 

I will be mounting pressure sensors on positions in the cupboard shelves and then trigger notifications with Home Assistant.

![macaroni2](https://user-images.githubusercontent.com/26295411/58867251-62bb6c80-86ba-11e9-8934-60126f59054d.png)

![2791-kokta_makaroner_500x380](https://user-images.githubusercontent.com/26295411/58867045-0c4e2e00-86ba-11e9-9df3-51b7049433f2.jpg)

**Comment by goyney** [comment] 2019-06-05 11:54
Possible duplicate of #3481 considering noodles are already going to be difficult to represent. Once we get one version of a noodle, I doubt we would add other variations.

**Comment by Templarian** [comment] 2019-06-05 21:48
Closing this one out as it's too niche. Without weird perspective or pipe look it would be difficult to recognize.

For those finding this searching for gluten use `mdi-barley-off`.

**Closed by Templarian** 2019-06-05 21:48 UTC
Labels: Consider Closing :door:
