### ISSUE TITLE
fluorescent lamp

### ISSUE THREAD

**Issue by FelisucoVFR** [Templarian/MaterialDesign#5735] opened 2021-01-02 22:57 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment] 2021-01-02 23:05
@FelisucoVFR Is this the same as this request #4450 ?

If not can you edit your issue to include examples / description of it's use.

**Comment by FelisucoVFR** [comment] 2021-03-25 14:36
> @FelisucoVFR Is this the same as this request #4450 ?
> 
> If not can you edit your issue to include examples / description of it's use.

Yes, that's it the same icon I would like.
Sorry for the delay....

**Comment by JamesCoyle** [comment] 2021-03-27 12:54
Duplicate of #4450

**Closed by JamesCoyle** 2021-03-27 12:54 UTC
Labels: Home Assistant, Icon Request, Needs More Info
