### ISSUE TITLE
Roof

### ISSUE THREAD

**Issue by fazeno** [Templarian/MaterialDesign#3569] opened 2018-10-07 18:11 UTC
![roof](https://user-images.githubusercontent.com/16246812/46585138-22451980-ca6d-11e8-9312-22ed10e20f33.png)

**Comment by PeterShaggyNoble** [comment] 2018-10-08 16:45
Duplicate of #1434 - please give that issue a 👍

**Closed by PeterShaggyNoble** 2018-10-08 16:45 UTC
Labels: Home Assistant :house:, Icon Request :pencil2:
