### ISSUE TITLE
[Icon Request] Pawn

### ISSUE THREAD

**Issue by mymindstorm** [Templarian/MaterialDesign#1115] opened 2016-03-25 04:00 UTC
Ex.
![alt text](http://www.charbase.com/images/glyph/9823)
![alt text](http://www.iconexperience.com/_img/i_collection_png/512x512/plain/chess_piece_pawn.png)

Thanks in advance for considering my request!

**Comment by CoDEmanX** [comment] 2016-03-25 11:52
Duplicate of #521

**Closed by CoDEmanX** 2016-03-25 11:52 UTC

**Comment by mymindstorm** [comment] 2016-03-25 16:17
That's odd, the search does not come up with those results for me
![screenshot 2016-03-25 at 11 15 52 am](https://cloud.githubusercontent.com/assets/6856311/14048252/14aa99a2-f27b-11e5-865a-cc39f4db56d0.png)

**Comment by CoDEmanX** [comment] 2016-03-25 16:31
The request is a duplicate, the original issue has not yet been fulfilled. infanf contributed icons, but is yet to be decided to add them.
