### ISSUE TITLE
water tap

### ISSUE THREAD

**Issue by Aryankids** [Templarian/MaterialDesign#5187] opened 2020-05-27 06:06 UTC
a water tap icon like 

https://www.123rf.com/photo_107316312_stock-vector-water-tap-icon-vector-isolated-on-white-background-for-your-web-and-mobile-app-design-water-tap-logo.html

**Comment by goyney** [comment] 2020-05-27 19:10
Duplicate of #5137.

**Closed by goyney** 2020-05-27 19:10 UTC
Labels: Icon Request
