### ISSUE TITLE
Sugestion deezer Icon

### ISSUE THREAD

**Issue by rparana** [Templarian/MaterialDesign#5008] opened 2020-04-01 19:11 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.

## Usage

This Icon can use to link the podcast plataform.

## Examples

[deezer-icon] https://image.flaticon.com/icons/png/512/49/49383.png

**Comment by Templarian** [comment] 2020-04-01 19:15
Duplicate of #1255

**Comment by Templarian** [comment] 2020-04-01 19:16
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Closed by Templarian** 2020-04-01 19:15 UTC
Labels: Icon Request, Rejected

**Comment by PeterShaggyNoble** [comment] 2020-04-02 08:35
This one's already available from SI:

[![image](https://user-images.githubusercontent.com/15157491/78227526-4b5d3380-74c5-11ea-86dd-f242c0994d88.png)](https://simpleicons.org/?q=deezer)
