### ISSUE TITLE
Air quality icons - PM25, PM10, CO, SO2, NO2

### ISSUE THREAD

**Issue by Spirituss** [Templarian/MaterialDesign#4204] opened 2019-06-20 10:40 UTC
I have:

- [ ] Searched all issues to make sure there isn't a request for this icon.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Hello, I'm currently looking for icons to indicate air quality. The next icons are wanted:
-  PM25 (could be performed as cloud with small points inside or just text)
-  PM10 (could be performed as cloud with bold points inside or just text)
-  CO (not CO2!)
-  SO2
-  NO2

## Examples

They could be performed similar to CO2 icon.

**Comment by goyney** [comment] 2019-06-20 12:46
Duplicate of https://github.com/Templarian/MaterialDesign/issues/2475.

**Closed by goyney** 2019-06-20 12:46 UTC
Labels: Icon Request

**Comment by Spirituss** [comment] 2019-08-30 14:22
Please mind that PM25 and PM10 are definitely NOT atmospheric gases, but are markers of air quality. Since I see that request for some gases is closed, I kindly ask to reopen this one.

**Comment by CoDEmanX** [comment] 2019-08-30 20:50
To quote goyney from that other issue:

> We have a full alphabetic and numeric set in the library which can easily be used to create any combination of letter and numbers. That's why those were added.

You can either do that or use plain text in your application.

**Comment by Spirituss** [comment] 2019-08-31 08:44
> To quote goyney from that other issue:
> 
> > We have a full alphabetic and numeric set in the library which can easily be used to create any combination of letter and numbers. That's why those were added.
> 
> You can either do that or use plain text in your application.

Could you please provide me with a link to this alphabetic and numeric set? I can't find it.

**Comment by CoDEmanX** [comment] 2019-08-31 08:54
Just search for `alpha` or `numeric`.

**Comment by Spirituss** [comment] 2019-08-31 09:43
Thanks!

**Comment by stefferber** [comment] 2021-01-10 19:48
I use for
- PM10 icon: `mdi:thought-bubble`
- PM2.5 icon: `mdi:thought-bubble-outline`
