### ISSUE TITLE
new icon for PM2.5

### ISSUE THREAD

**Issue by grampasso-lento** [Templarian/MaterialDesign#7294] opened 2023-11-16 02:03 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

weather and air conditions in home assistant, It would simply report the text PM2.5, much as the mdi:molecule-co2 icon.

### Give us an example of what this icon might look like.

It would simply report the text PM2.5, much as the mdi:molecule-co2 icon.

**Comment by mririgoyen** [comment] 2023-11-22 20:23
Dupe of #4204, #6449.

**Closed by mririgoyen** 2023-11-22 20:23 UTC
Labels: Icon Request
