### ISSUE TITLE
Please add Aquarium and Terrarium Icons

### ISSUE THREAD

**Issue by erkr** [Templarian/MaterialDesign#6076] opened 2021-07-22 10:22 UTC
Any abstract creativity will do :-)

**Comment by goyney** [comment] 2021-07-22 13:43
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

**Comment by goyney** [comment] 2021-07-22 13:43
Also, partial duplicate of #5153. And `fish-bowl` already exists.

**Closed by goyney** 2021-07-22 13:43 UTC
Labels: Icon Request
