### ISSUE TITLE
Hen

### ISSUE THREAD

**Issue by GUOLDEV** [Templarian/MaterialDesign#6380] opened 2021-12-24 01:10 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Hen

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/22019245/147303764-9adf50da-fed7-4962-b2a4-55c4d2715e0d.png)

### Upload the icon source.

[mdi-hen.svg.zip](https://github.com/Templarian/MaterialDesign/files/7772023/mdi-hen.svg.zip)

**Comment by goyney** [comment] 2021-12-24 01:35
Duplicate of #3455.

**Closed by goyney** 2021-12-24 01:35 UTC
Labels: Icon Request
