### ISSUE TITLE
University OR College Icon

### ISSUE THREAD

**Issue by IbadurRehman14** [Templarian/MaterialDesign#3300] opened 2018-07-04 07:14 UTC
Hello there
I would like to suggest a icon for University or College.

![university-icon](https://user-images.githubusercontent.com/40762312/42262073-c2ddb554-7f87-11e8-8a62-f99428c0f226.png)

**Comment by MrGrigri** [comment] 2018-07-05 15:36
Would `school` not work for you? 

![school](https://materialdesignicons.com/icon/school)

**Comment by PeterShaggyNoble** [comment] 2018-07-06 09:52
Duplicate of #2173 and #3282

**Closed by PeterShaggyNoble** 2018-07-06 09:52 UTC
Labels: Icon Request :pencil2:, Needs More Information :information_source:
