### ISSUE TITLE
Ripple

### ISSUE THREAD

**Issue by sureshreddyputta** [Templarian/MaterialDesign#3092] opened 2018-04-20 12:27 UTC
There is no icon for ripple.

**Comment by PeterShaggyNoble** [comment] 2018-04-20 13:26
Thanks for the request. However, if you're referring to the brand icon, this is a duplicate of #2713, otherwise see #2363.

Please don't forget to search existing icons and issues before posting a new request.

**Closed by PeterShaggyNoble** 2018-04-20 13:26 UTC
