### ISSUE TITLE
code points change

### ISSUE THREAD

**Issue by splitbrain** [Templarian/MaterialDesign#644] opened 2015-08-28 12:22 UTC
It seems like the code points for the various icons change each time the (full) font is rebuild. Eg. ```mdi-key``` used to be ```f378``` but is now ```f3a7```. This means the font can only be used through the given CSS file. However that's not what I want to do. Is there any chance to adjust the build mechanism to make sure the code points of icons do not change between releases?

**Comment by CoDEmanX** [comment] 2015-08-28 12:45
See here:
https://github.com/Templarian/MaterialDesign/issues/247#issuecomment-87749666
https://github.com/Templarian/MaterialDesign/issues/492#issuecomment-120724671
https://github.com/Templarian/MaterialDesign/issues/253#issue-65583219

I agree that this is less than ideal. I believe it's technically possibly to re-use former codepoints, because every icon should have an ID in the backend, which withstands renames and other changes. The codepoints could either be directly derived from this ID, or a mapping be stored of IDs and previously used codepoints to look the old codepoints up and add new ones if there's no key for an icon ID. The latter approach could also be based on icon names if renaming is desired to change the codepoint (but I see no point in this, would be more useful change codepoints when icons are edited if at all). @Templarian?

**Comment by splitbrain** [comment] 2015-08-28 12:52
I'd be happy to help if someone could point me towards the source of the build script. I can't seem to locate it in the repo

**Comment by CoDEmanX** [comment] 2015-08-28 13:07
It's Templarian's personal / closed-source / patented build script if I'm not mistaken, and we couldn't code this without access to the backend as well.

**Comment by Templarian** [comment] 2015-08-28 20:29
The glyph positions are always going to be changing for each release in the webfont. Eventually people will be able to build custom fonts.

I have a column in the database for static font positions for a designer oriented font that will be coming out in the future.

https://materialdesignicons.com/getting-started Read the sass section (this helper method will be included in the next release as I have updated the scripts internally).

Ha, @CoDEmanX the process isn't that closed source. It actually just uses a heavily modified version of the https://github.com/sapegin/grunt-webfont tool. I would suggest always using the CSS classes for now.

**Comment by Templarian** [comment] 2015-08-28 20:32
Duplicate of #247, as the main issue is a probably won't fix type issue.

**Comment by Templarian** [comment] 2015-08-28 20:33
By the way, I do _really_ need to finish typing up documentation on how to build this with grunt-webfont. I just haven't gotten around to writing a tutorial yet.

**Comment by splitbrain** [comment] 2015-08-28 20:37
This is not  a very satisfactory answer. Let me explain my use case. We want to include the whole font in DokuWiki to give plugins a wide choice of icons to use. however, most of the icons won't be used in the end. so it makes no sense to include the whole lookup table of CSS. instead each plugin author should be able to simply write the content definition for the icon he uses. 
really, as you can see from the various comments @CoDEmanX linked, I am not the only one that needs fixed code points. this has absolutely nothing to do with a "designer approach" this needs to be fixed in the Web fonts. please reopen.

**Comment by Templarian** [comment] 2015-08-28 20:48
Oh yea, I see what you mean, sort of. Why can't they use the CSS classes exactly in their plugins?

`<span class="mdi mdi-account"></span> Look an icon to the left`

**Comment by CoDEmanX** [comment] 2015-08-28 21:51
@Templarian: I still don't see the exact issue why static codepoints aren't possible other than for a future designer oriented font? Is it because grunt-webfont assigns them in an auto-incrementing fashion against an alphabetically sorted list of input files? Shouldn't be hard to change that... I also found this:

https://github.com/sapegin/grunt-webfont/blob/master/tasks/webfont.js#L360

which looks to me like you can export and import codepoints somehow?

**Comment by Templarian** [comment] 2015-08-28 23:46
They are definitely possible @CoDEmanX  (it's actually partially coded on my end also). It's how I will be generating the designer font file.

It's just not on the road map at the moment to implement for webfonts. As the icon count increases (think several thousand) it's not even going to be remotely useful to have all the icons in the same webfont. I will most likely be moving the icons into several different package options (rich text editor, image pack, logos pack, etc...). Even with woff2 the file size of the icon pack is going to get a little overkill.

In basically 1 year we added basically 694 community icons (and Google is adding them just as fast).

Might be able to do it, but right now it is a low priority issue in terms of features that users will actually benefit from.

**Comment by splitbrain** [comment] 2015-08-29 09:31
Plugin authors can not simply use the CSS classes because I don't want to include them in DokuWiki. 

In addition the classes alone are not very flexible - you may want to use the icons in other ways than using a before content. Simplest use case: you may want to use it in a after content.

Also fixed code points should be supported when subsetting the font. A symbol should always use the same code point. In the full font as well as when it is exported into a custom font.

We may very well decide to use a subfont for DokuWiki, but even then we will include more icons than we use in the core for plugin authors to use.

If you don't want to work on it, please at least release the generation tools so we could implement our own font-generator base on it.

**Comment by Templarian** [comment] 2015-08-29 18:54
I'm going to reopen this back up. The issue will track the grunt build script (including the fixed code points).

I'll work on getting this in after the new export tooling.

**Comment by stefan-kolb** [comment] 2015-11-18 12:59
:+1:

**Comment by matthiasgeiger** [comment] 2015-11-18 13:03
Stability of code points is important if the font is directly used (e.g., for font-based icons in desktop applications).

Would be glad if you fix this for further releases!

**Comment by simonharrer** [comment] 2015-11-18 14:42
:+1:

**Comment by Templarian** [comment] 2015-11-18 15:26
This will be addressed in a coming release (not the next release, but most likely the release after that). The database changes are almost done. Just need to fix up the build to correctly map the code points (and handle deprecated icons).

**Comment by matthiasgeiger** [comment] 2015-11-18 19:42
Great!

**Comment by mydudechris** [comment] 2016-01-14 02:44
:+1:

**Comment by Templarian** [comment] 2016-01-18 02:50
Slowly getting there. You can view the preview the fixed code points on the cheatsheet page.

**Note: There is no release matching this cheatsheet yet.**

https://materialdesignicons.com/cheatsheet

Things to do before this releases:

- [ ] Clean up the design on the cheatsheet page and add 1 click copy to clipboard.
- [ ] Create build step for a TTF/OTF font specifically for designers to download on the cheatsheet page.
- [ ] Update the build step to include the code points (already wrote the db query for this step).
- [ ] Move things around on the front page to include a Cheatsheet link.
- [ ] Publish a new version of the font for both Developers and Designers.

Extra:

- [ ] Write a cache layer similar to the homepage to prevent excessive DB load.

**Comment by SnakesRG** [comment] 2016-03-02 18:19
@Templarian 

> https://materialdesignicons.com/cheatsheet

This is not functional, can you fixed it ? 

Thanks,
Benjamin

**Comment by Templarian** [comment] 2016-03-02 18:22
I changed a bunch of database stuff. This page will go live with the next release.

The cheatsheet is useless for 1.4.x as that doesn't use fixed code points.

**Comment by SnakesRG** [comment] 2016-03-02 18:30
@Templarian Hum, else, you can add the code content (f191 for a bell icon) in the preview ? exemple: https://gyazo.com/2c77d92576d06972d9e5532c410a64b3.
I think its is not difficult, and it is helpful. 

PS: I'm French, sorry for my bad English (:

**Comment by Templarian** [comment] 2016-03-02 18:36
Yea, that might be a good idea. For the next release code points will only be visible in the cheatsheet page.

The website will always show the latest icons, but the cheatsheet page will let one select and view icons based on the version they were added. This will be useful if one is using an older version going forward.

**Comment by Templarian** [comment] 2016-03-03 08:53
- Preview: http://cdn.materialdesignicons.com/1.5.54-dev/
- Download: http://cdn.materialdesignicons.com/1.5.54-dev/download.zip

It's 2:52am... definitely not deploying this for a bit as there were a lot of changes to the font build steps and I haven't had time to check everything actually exported okay.

**Comment by SnakesRG** [comment] 2016-03-03 16:58
@Templarian It's good! But you can add the unicode of the icons ? Exemple: https://gyazo.com/024788df806023770021b3764de38ddd
This is important for me, and maybe, all users who use .class:before { content: "\UNICODE"; } 

Thanks for your attention,
Snake's a.k.a Benjamin

**Comment by Templarian** [comment] 2016-03-03 20:42
https://materialdesignicons.com/cheatsheet is more what you're looking for, but I'll add a toggle switch html entities and unicode.

Ignore the excessive load time on that page cache is disabled and that is a very large database query.

**Comment by SnakesRG** [comment] 2016-03-03 21:11
@Templarian your page doesn't load. :disappointed: (15 minutes awaiting approximately) 
Can you fix it or add the unicode in http://cdn.materialdesignicons.com/1.5.54-dev/ when you have the time ?

Thanks a lot !

**Comment by matthiasgeiger** [comment] 2016-03-04 08:07
Cheatsheet works fine for me.
@SnakesRG Here's a screenshot:
![materialdesign-screenshot](https://cloud.githubusercontent.com/assets/676652/13521297/b74e98f6-e1e7-11e5-8cdd-770d88a7f31f.png)

@Templarian Thanks for working on this! The cheatsheet solution in combination with fixed code points would be fine for [my use case](https://a.fsdn.com/con/app/proj/jabref/screenshots/JabRef3.0-web-search.png). @SnakesRG proposal to integrate it in the preview would be even better ;-)

**Comment by simonharrer** [comment] 2016-03-04 08:21
Thank you. Nice work!

**Comment by SnakesRG** [comment] 2016-03-04 16:35
@matthiasgeiger Thanks for the screenshot :p (this work on Edge, but not on Gooogle Chrome) 
Unfortunately, this page doesn't list the unicode of icons. :/ 

Exemple:
The unicode for icon 'bell' is f191, but on the cheatsheet's page, the code is F09A (i know is not the unicode, this is Hex) 
But I would like the unicode of this icon .. :)

**Comment by Templarian** [comment] 2016-03-04 16:37
@SnakesRG I think there might be some confusion. 1.5.54 will be the first release with fixed code points. Before that the code points changed every release (alphabetical starting with `f001`).

**Comment by SnakesRG** [comment] 2016-03-04 16:42
@Templarian It's okay, I will wait the functionality for view the unicode of a icon in a page (maybe you can add it in http://cdn.materialdesignicons.com/1.5.54-dev/.)

Thanks,

**Comment by Templarian** [comment] 2016-03-05 10:09
@SnakesRG http://cdn.materialdesignicons.com/1.5.54-dev/ Updated (click any of them in modern browser copies the character to the clipboard).

Also the designer files... [MaterialDesignIconsDesign.zip](http://cdn.materialdesignicons.com/1.5.54-dev/MaterialDesignIconsDesign.zip)

**Comment by SnakesRG** [comment] 2016-03-05 12:36
@Templarian thanks to update !
But I can't get the unicode from your page :(
Maybe, just update the cheastsheet page with the 1.5.54 version ? (https://fortawesome.github.io/Font-Awesome/cheatsheet/) and after add the unicode in the home page, like that font awesome using (http://screencloud.net/v/pzwW) ? :p

I would like replace font awesome on my website to MaterialDesigns, but my CSS is coded with : class:before {content: "\unicode";} 
And I don't want change all with the <i> balise, just I change the unicode :p

**Comment by matthiasgeiger** [comment] 2016-03-06 10:26
@SnakesRG If you do not want to wait, you can perform the lookup manually:
Determine the name of the Icon you want to add on the cheatsheet or the website. Using the name just search for it in the ```materialdesignicons.css``` file - here you can find the mappings to unicode:

```
.mdi-access-point:before {
  content: "\f101";
}
```

**Comment by SnakesRG** [comment] 2016-03-06 18:17
It's good for me ;)
@Templarian close the issue ? 

Good job man! (:

**Comment by Templarian** [comment] 2016-03-06 18:30
I'm wrapping up some browser testing and verification of the latest icon package / design package.

http://cdn.materialdesignicons.com/1.5.54/
https://materialdesignicons.com/design

Let me know if you see anything broken. If not I'll be doing the bower / npm deploys tonight. At that point I will close the issue (and a couple others related to this release).

**Comment by Templarian** [comment] 2016-03-07 03:36
Bower / NPM updated. First release with static code points going forward.

**Closed by Templarian** 2016-03-07 03:36 UTC
Labels: Webfont Feature
