### ISSUE TITLE
Power socket EU

### ISSUE THREAD

**Issue by Jocke1970** [Templarian/MaterialDesign#1426] opened 2016-08-10 17:39 UTC

**Comment by JamesCoyle** [comment] 2016-08-10 17:41
For reference: http://www.worldstandards.eu/electricity/plugs-and-sockets/

**Comment by JapanYoshi** [comment] 2016-09-11 13:26
So @Jocke1970 which type are you talking about?

**Comment by GreenTurtwig** [comment] 2016-09-11 14:02
I'm assuming the European one since it's included in the title and it's used in quite alot of countries in Europe.
![puush-linux 2016-09-11 at 03 00 52](https://cloud.githubusercontent.com/assets/15905797/18417760/be4b86ac-7830-11e6-859c-8fd87b3e93db.png)

**Comment by Jocke1970** [comment] 2016-09-11 16:21
Type C is most useful for icon, as far as i can see.

**Comment by JamesCoyle** [comment] 2016-09-11 16:27
Two circles surrounded by a circle would work for that. The US and UK variants would also be useful and perhaps Type I too. That would cover most regions.

**Comment by panzaeron** [comment] 2016-10-01 01:17
Here comes a type F icon, I use this in my homeautomation visu
![power-socket-eu-type-f](https://cloud.githubusercontent.com/assets/3792195/19010675/f0e6b786-8784-11e6-8bf5-4bb5e9c56e18.png)

[power-socket-eu-type-f.svg.txt](https://github.com/Templarian/MaterialDesign/files/504042/power-socket-eu-type-f.svg.txt)

**Comment by GreenTurtwig** [comment] 2016-10-14 07:42
Got two here, UK and EU. Not the best in my opinion, but it works. :+1:   
![puush-linux 2016-10-14 at 08 41 49](https://cloud.githubusercontent.com/assets/15905797/19379499/214a7092-91ea-11e6-8d32-b759dc9f0c31.png)

[plugs.zip](https://github.com/Templarian/MaterialDesign/files/528931/plugs.zip)

**Comment by bigwoof** [comment] 2017-01-10 06:19
I agree that adding the various international plug icons to the set would be great (but tedious)

**Comment by PeterShaggyNoble** [comment] 2017-02-16 16:52
Could this be considered a dupe of #752?

**Comment by wopian** [comment] 2017-02-16 17:33
The current [`power-socket`](https://materialdesignicons.com/icon/power-socket) seems to be a [C14 coupler socket](https://en.wikipedia.org/wiki/IEC_60320#C13.2FC14_coupler) - which is only used for very specific devices.

**Comment by Templarian** [comment] 2017-05-24 04:26
[![power-socket-eu](https://materialdesignicons.com/icon/power-socket-eu)](https://materialdesignicons.com/icon/power-socket-eu) [![power-socket-uk](https://materialdesignicons.com/icon/power-socket-uk)](https://materialdesignicons.com/icon/power-socket-uk) [![power-socket-us](https://materialdesignicons.com/icon/power-socket-us)](https://materialdesignicons.com/icon/power-socket-us)

**Closed by Templarian** 2017-05-24 04:26 UTC
Labels: Contribution, High Priority, Icon Request
