### ISSUE TITLE
Emotions

### ISSUE THREAD

**Issue by dmitry8887** [Templarian/MaterialDesign#479] opened 2015-07-02 13:18 UTC
Might be an overlap with emoji but would be nice to get some basics support for emotions - at least the most common 6-7 icons used by most forums.

**Comment by Templarian** [comment] 2015-07-02 16:26
Can you update your issue with the list of core ones you think should be included. That way they can be checked off as they are added.

Google added a couple  of new stock ones also that will be synced in soon.

**Comment by CoDEmanX** [comment] 2016-03-30 08:41
This is actually a duplicate of #134, which comes with a list of common emoticons.

**Closed by CoDEmanX** 2016-03-30 08:41 UTC
Labels: Duplicate, Icon Request
