### ISSUE TITLE
Vent Closed / Air-Filter Closed

### ISSUE THREAD

**Issue by usingapc** [Templarian/MaterialDesign#6615] opened 2022-05-30 00:14 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

showing that a smartvent(Flair, Keene, etc) is closed in Home Assistant.  I currently use the Air-Filter icon when open.   Modifying the current Air-Filter icon to show that the air flow has stopped would work.

### Give us an example of what this icon might look like.

![air-filter-closed-vertical-louvers](https://user-images.githubusercontent.com/90284468/170897296-fcc3e246-2fc4-494e-9809-2d929bc79ce1.svg)
![air-filter-closed-no-louvers](https://user-images.githubusercontent.com/90284468/170897297-0db2d578-570f-4b0b-a758-c02c4aff8f3d.svg)
![air-filter-closed-horizontal-louvers](https://user-images.githubusercontent.com/90284468/170897298-6904abd2-28f1-433f-89ca-673d6306b487.svg)

**Comment by goyney** [comment] 2022-05-30 17:34
Seems like a potential duplicate of #5115.

**Comment by goyney** [comment] 2022-06-16 03:37
We're going to capture this in #5115. Please follow that issue for status updates.

**Closed by goyney** 2022-06-16 03:37 UTC
Labels: Icon Request, Duplicate, Consider Closing
