### ISSUE TITLE
chicken

### ISSUE THREAD

**Issue by xabi62** [Templarian/MaterialDesign#5022] opened 2020-04-06 19:24 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to create views to watch the cameras of the chicken coop and what could be better than an icon of a chicken for these views

## Examples

<img src="https://lh3.googleusercontent.com/proxy/PkIuEKEZ9MWor-Mtl5lnY9nKzS5ePVYaUYzh8CKUg1GvGNdzwUckNlu---n7rNPfrJUC-R0FJwemuAzWxtlkJc-1_Y1emoaVhKyoiEq67xbWSDKvuif_YhSRSQFvf2B4S24" height="400" width="400">

**Comment by goyney** [comment] 2020-04-06 19:27
Duplicate of #3455. Please search, like you claimed to have done.

**Closed by goyney** 2020-04-06 19:27 UTC
Labels: Icon Request
