### ISSUE TITLE
Google classroom icon

### ISSUE THREAD

**Issue by Isetnt2** [Templarian/MaterialDesign#3091] opened 2018-04-20 06:52 UTC
Would like to see a google classroom icon,

**Comment by CoDEmanX** [comment] 2018-04-20 07:41
Isn't that pretty much like https://petershaggynoble.github.io/MDI-Sandbox/?icon=account-group ?

Otherwise it would need to be added as brand icon, but I'm not sure if it meets the MDI requirements. It has too many details for a generic icon IMO.

**Comment by GreenTurtwig** [comment] 2018-04-20 07:52
Here's the guidelines: https://developers.google.com/classroom/brand

The main issue is the transparent people in the background.

**Comment by PeterShaggyNoble** [comment] 2018-04-20 08:11
Duplicate of #1950.

**Closed by PeterShaggyNoble** 2018-04-20 08:11 UTC
Labels: Icon Request :pencil2:
