### ISSUE TITLE
Completely transparent icon.

### ISSUE THREAD

**Issue by SefDik** [Templarian/MaterialDesign#5702] opened 2020-12-15 17:52 UTC
Completely transparent icon.

The idea here is that there is nothing to show, no border, no fill, absolutely nothing.

It can then be used on/over an existing image (lamp/car/switch/door) whatever so the original image or part of it is visible but the 'blank' icon is not but can be detected by a tap or mouse click.  The use I have in mind is on a Home Automation floor-plan.
/0^0\

**Comment by goyney** [comment] 2020-12-15 18:02
Duplicate of #5130 #2858 #1167 #501 #352...

Please *do not* remove our issue template. One of the checkboxes in that template instructs you to search before posting your request.

**Closed by goyney** 2020-12-15 18:02 UTC
Labels: Icon Request

**Comment by SefDik** [comment] 2020-12-16 11:00
Sincere apologies goyney, I'm a newcomer but learning.
I did search the 'icons' themselves but I did NOT search the requests forum, really sorry!
I accept the closure.
/0^0\
