### ISSUE TITLE
Cubes/Stacked Cubes

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2343] opened 2017-08-23 14:42 UTC
Needed an alternate Cube and Cubes icon.

![cube](https://user-images.githubusercontent.com/20706106/29621739-9e3889ee-87ef-11e7-93b5-a34ec017bc1c.png)
![cubes](https://user-images.githubusercontent.com/20706106/29621743-9fa0cd8c-87ef-11e7-94e3-6eca6c296f46.png)

[cube.zip](https://github.com/Templarian/MaterialDesign/files/1245770/cube.zip)

**Comment by OctoberJemini** [comment] 2017-08-23 18:13
Made a minor modification on the CUBES SVG.  The top corner was to pointy according the the material design specifications.

[Cube.zip](https://github.com/Templarian/MaterialDesign/files/1246515/Cube.zip)

**Comment by mbarakaja** [comment] 2017-08-25 19:16
I have requested something similar too in #1916

**Comment by Templarian** [comment] 2017-08-30 04:47
Closing as a duplicate of #1916 as mentioned above. Lets keep the discussion there. I think I'll be adding a few of @mbarakaja's designs.

**Closed by Templarian** 2017-08-30 04:47 UTC
Labels: Contribution, Icon Request
