### ISSUE TITLE
Angel List Icon

### ISSUE THREAD

**Issue by NewETown** [Templarian/MaterialDesign#950] opened 2016-01-05 20:00 UTC
Angel List is a great resource with a cool icon (Font-Awesome has one!) that can be found here: https://angel.co/

Being able to use this icon along side the other social icons would be very appreciated :)

**Comment by Templarian** [comment] 2016-01-05 20:02
Duplicate of #920

**Closed by Templarian** 2016-01-05 20:02 UTC

**Comment by NewETown** [comment] 2016-01-05 20:25
@Templarian Ah sorry about that, I didn't search without the open filters enabled. Should I +1 the other thread?

**Comment by Templarian** [comment] 2016-01-05 20:34
Sure, but probably not one I'm going to add since it's too niche of an icon and does not fall into the social media branding. Going to be trying to remove non-social media over time.

**Comment by jhabdas** [comment] 2017-08-26 04:20
Looks like this has been requested twice now. Can this issue be reopened please?
