### ISSUE TITLE
Car License plate 

### ISSUE THREAD

**Issue by PenriteOil** [Templarian/MaterialDesign#7134] opened 2023-06-14 06:41 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

car registration plate

### Give us an example of what this icon might look like.

![290081](https://github.com/Templarian/MaterialDesign/assets/42527764/1c46c8b3-e090-4b5c-a0a2-ea459729dcf7)

**Comment by mririgoyen** [comment] 2023-06-15 21:45
Duplicate of https://github.com/Templarian/MaterialDesign/issues/712, https://github.com/Templarian/MaterialDesign/issues/3917, https://github.com/Templarian/MaterialDesign/issues/4451, https://github.com/Templarian/MaterialDesign/issues/4973, https://github.com/Templarian/MaterialDesign/issues/5757, https://github.com/Templarian/MaterialDesign/issues/6331.

**Closed by mririgoyen** 2023-06-15 21:45 UTC
Labels: Icon Request
