### ISSUE TITLE
car-hood(-lock && -lock-open)

### ISSUE THREAD

**Issue by brylee123** [Templarian/MaterialDesign#7114] opened 2023-05-23 15:29 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Tracking the status of my car's hood.

1 Icon for just the Hood
1 Icon for Hood Locked (or closed)
1 Icon for Hood Unlocked (or open)

### Give us an example of what this icon might look like.

![image](https://github.com/Templarian/MaterialDesign/assets/22011502/4c2cc60c-0be7-462b-95e2-2f763ef89c81)

**Comment by andrejsharapov** [comment] 2023-05-25 10:35
It will most likely look like this 😄 And for issue #7115.
![image](https://github.com/Templarian/MaterialDesign/assets/44722574/602061d3-bbfa-49d3-bbc5-54cab647658c)

**Comment by mririgoyen** [comment] 2023-05-31 17:49
Duplicate of #5170.

**Closed by mririgoyen** 2023-05-31 17:49 UTC
Labels: Icon Request
