### ISSUE TITLE
PayPal icon

### ISSUE THREAD

**Issue by mtpamir** [Templarian/MaterialDesign#2854] opened 2018-02-28 02:20 UTC
PayPal is a one of the most popular payment methods. the logo can be used on the website to show that the site owner accepts PayPal.

PayPal logo: https://developer.paypal.com/docs/classic/api/logos_marks/

![paypal2](https://user-images.githubusercontent.com/217026/36766464-358144bc-1c60-11e8-9fb7-9f828fcd4d0e.JPG)
![paypal3](https://user-images.githubusercontent.com/217026/36766465-35bce580-1c60-11e8-922f-5e55c1bf0263.JPG)
![paypal1](https://user-images.githubusercontent.com/217026/36766466-35f39f9e-1c60-11e8-9b7b-54509564f98d.JPG)

**Comment by Templarian** [comment] 2018-02-28 02:22
Duplicate of #297

**Closed by Templarian** 2018-02-28 02:22 UTC
