### ISSUE TITLE
New Icon Request for Physician and Patient

### ISSUE THREAD

**Issue by salipour105** [Templarian/MaterialDesign#3005] opened 2018-04-02 18:35 UTC
Is there an icon available in Material UI to represent a physician or patient?

- Patient = person icon with heart
- Doctor = person icon with stethoscope

**Comment by Templarian** [comment] 2018-04-02 18:40
- `patient` is a duplicate of #1416
- `doctor` is a duplicate of #2245

Please use the search.

**Closed by Templarian** 2018-04-02 18:40 UTC
