### ISSUE TITLE
Terrace

### ISSUE THREAD

**Issue by ApplesandPears** [Templarian/MaterialDesign#5209] opened 2020-06-04 01:39 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Outdoor Icon, used for balcony, terrace, etc.

## Examples

![image](https://user-images.githubusercontent.com/56008284/83705355-fd73c180-a614-11ea-8473-80fece710e46.png)

Thank you!

**Comment by goyney** [comment] 2021-08-31 18:14
Duplicate of #4378.

**Closed by goyney** 2021-08-31 18:14 UTC
Labels: Icon Request, Home Assistant
