### ISSUE TITLE
Air Compressor

### ISSUE THREAD

**Issue by lithgowlights** [Templarian/MaterialDesign#6371] opened 2021-12-15 22:59 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

My shed has 2 air compressors, one large, one small, that are controlled by smart switches. I'd like a dedicated air compressor Icon please.

### Give us an example of what this icon might look like.

![depositphotos_239866586-stock-illustration-air-compressor-icon-trendy-air](https://user-images.githubusercontent.com/16928091/146277746-643af573-380c-439a-a3fe-6eb9cfeca34d.jpg)

This is a bit complex, but you could remove the water icon on the right and the safety valve "floating" next to it and simplify the entire shape

**Comment by goyney** [comment] 2021-12-15 23:03
Duplicate of #6079.

**Closed by goyney** 2021-12-15 23:03 UTC
Labels: Icon Request
