### ISSUE TITLE
Source/input Hdmi number

### ISSUE THREAD

**Issue by Nik18111997** [Templarian/MaterialDesign#5931] opened 2021-04-12 20:47 UTC
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home assistant lg webos remote control

## Examples
 
![images__01](https://user-images.githubusercontent.com/81594558/114459508-ea406380-9be0-11eb-9141-891c085b5569.png)

**Comment by goyney** [comment] 2021-04-12 20:50
This is literally a duplicate of #5930.

**Closed by goyney** 2021-04-12 20:50 UTC
Labels: Icon Request
