### ISSUE TITLE
Cannot download icons

### ISSUE THREAD

**Issue by lisongting** [Templarian/MaterialDesign#2188] opened 2017-06-22 03:15 UTC
I want to down load some icon from https://materialdesignicons.com/
but the browser shows that 
*Fatal error: Class 'Imagick' not found in /home/templarian/webapps/materialdesignicons/api/endpoints.php on line 1319*
Any icon shows the same problem.

**Comment by Templarian** [comment] 2017-06-22 03:21
Duplicate of #2181

**Closed by Templarian** 2017-06-22 03:21 UTC
