### ISSUE TITLE
Contribution: Gas Can Icon

### ISSUE THREAD

**Issue by augustin32** [Templarian/MaterialDesign#2241] opened 2017-07-14 14:43 UTC
A gas canister icon.
![gas-can24](https://user-images.githubusercontent.com/14167196/28216904-ec3a053a-68bb-11e7-9b59-1bd623a1aa42.png)
![gas-can36](https://user-images.githubusercontent.com/14167196/28216906-ee247768-68bb-11e7-86b2-f42dd060d327.png)
![gas-can48](https://user-images.githubusercontent.com/14167196/28216910-f0e69210-68bb-11e7-96ec-5aa94d876c11.png)

[gas-can.zip](https://github.com/Templarian/MaterialDesign/files/1148741/gas-can.zip)

**Comment by Templarian** [comment] 2017-07-14 16:32
Duplicate of `fuel`.

**Closed by Templarian** 2017-07-14 16:32 UTC
