### ISSUE TITLE
Vehicle licence plate

### ISSUE THREAD

**Issue by PedroCuadra** [Templarian/MaterialDesign#5757] opened 2021-01-06 12:58 UTC
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm on a car service project. So i need a way to represent a plate. I know that there are `car` and `account-card` icons but i'm using them for another purpose. 

## Examples

![image](https://user-images.githubusercontent.com/14881608/103770081-2ffaf800-5004-11eb-804e-6d4ca1dc9a65.png)

![image](https://user-images.githubusercontent.com/14881608/103770750-45245680-5005-11eb-84df-1df864edc135.png)

**Comment by goyney** [comment] 2021-01-06 15:02
Duplicate of #712, #3917, #4451, #4973.

> * [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.

**Closed by goyney** 2021-01-06 15:02 UTC
Labels: Icon Request
