### ISSUE TITLE
vanity-light(-outline)

### ISSUE THREAD

**Issue by bruhautomation** [Templarian/MaterialDesign#4460] opened 2019-10-02 20:00 UTC
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/14144928/66077179-71614580-e52d-11e9-82c2-cc7918f5300c.png)

![image](https://user-images.githubusercontent.com/14144928/66077213-84741580-e52d-11e9-925b-b2bf3ee5319f.png)

## Zip Download

[vanity_light.zip](https://github.com/Templarian/MaterialDesign/files/3683095/vanity_light.zip)

**Comment by goyney** [comment] 2019-10-02 20:03
You said you followed Material guidelines, but you didn't. :( Can you please take another pass?

**Comment by goyney** [comment] 2019-10-02 20:03
Also, potential duplicate of #4437.

**Comment by bruhautomation** [comment] 2019-10-02 21:26
I certainly tried to, @goyney! 😢 

Can you please provide some more feedback?

![image](https://user-images.githubusercontent.com/14144928/66081530-27c92880-e536-11e9-86bc-db1843a81028.png)


I am aware that the stroke width is not 2px, but I saw other examples in the MDI library that use 1px widths so I thought it may be okay. 

Examples:
 ![image](https://user-images.githubusercontent.com/14144928/66082734-c2c30200-e538-11e9-96a3-228a81d45876.png) 
![image](https://user-images.githubusercontent.com/14144928/66082831-ff8ef900-e538-11e9-872f-764f7b21e434.png)


I realize that the top bar does not have a squared stroke terminal. My logic is that it is not a stroke, but rather representative of the body of the light fixture and could use rounded corners (like the t-shirt icon does).  
![image](https://user-images.githubusercontent.com/14144928/66082875-17ff1380-e539-11e9-9100-396078d3d1be.png)

Cheers!

**Comment by Templarian** [comment] 2019-10-02 21:33
- Rare cases we make the exception for the `1dp` width. I think there is room in this design to use `2dp` wide lines.
- The round ends in this case wouldn't apply as its a decorative feature of the icon.

I think this can be iterated on to use `2dp`. Might have to eave the shade outlines 1.5.

**Comment by MrGrigri** [comment] 2019-10-02 22:32
Idk how I feel about the outlined variant...but it's there just in case.

![vanity-light](https://user-images.githubusercontent.com/4528551/66086681-09612e00-e532-11e9-8e45-773d88969ce8.png) ![vanity-light-outline](https://user-images.githubusercontent.com/4528551/66086708-1e3dc180-e532-11e9-975e-7b6853e4350b.png)

---
#### Files
[vanity-light.zip](https://github.com/Templarian/MaterialDesign/files/3683650/vanity-light.zip)

**Comment by bruhautomation** [comment] 2019-10-02 23:03
Sounds good! I'll stick to that 2px guideline closer in future submissions. Thanks for the feedback!

Let me know if you would like any additional revisions for this icon 👍

**Comment by goyney** [comment] 2019-10-03 20:22
[![vanity-light](https://materialdesignicons.com/icon/vanity-light)](https://materialdesignicons.com/icon/vanity-light)

**Closed by goyney** 2019-10-03 20:22 UTC
Labels: Contribution, Icon Request
