### ISSUE TITLE
winner

### ISSUE THREAD

**Issue by guykevin** [Templarian/MaterialDesign#6044] opened 2021-06-30 13:11 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

![winner](https://user-images.githubusercontent.com/56883887/123966137-061c0000-d9ad-11eb-82f7-078148f428d9.png)

**Comment by goyney** [comment] 2021-06-30 22:41
Duplicate of #6043.

**Closed by goyney** 2021-06-30 22:41 UTC
Labels: Icon Request
