### ISSUE TITLE
Icon for Invoice

### ISSUE THREAD

**Issue by gayugokhale** [Templarian/MaterialDesign#5610] opened 2020-10-31 12:29 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

![20201031_175702 1](https://user-images.githubusercontent.com/28901723/97779251-d78e2100-1ba2-11eb-932b-15426fd70f94.jpg)

**Comment by Templarian** [comment] 2020-11-01 22:43
Duplicate of #1010

For internationalization reasons we do not include currency or words within icons. Please use the above issue to see other suggestions.

**Closed by Templarian** 2020-11-01 22:43 UTC
Labels: Icon Request
