### ISSUE TITLE
bag

### ISSUE THREAD

**Issue by MrGlenThomas** [Templarian/MaterialDesign#3379] opened 2018-08-12 12:20 UTC
like the medical-bag, but just a bag that is not medical (without the +)

**Comment by JamesCoyle** [comment] 2018-08-13 10:26
![image](https://user-images.githubusercontent.com/10384436/44026626-9181cf30-9eeb-11e8-8c4f-87a07b9d1c41.png)

[bag.zip](https://github.com/Templarian/MaterialDesign/files/2282608/bag.zip)

**Comment by MrGlenThomas** [comment] 2018-08-13 11:02
Beautiful! 😍

**Comment by JamesCoyle** [comment] 2018-08-13 14:59
I always forget to change the icon name in the preview... 😂

**Comment by goyney** [comment] 2018-11-20 16:35
This is a duplicate of submission in #141 by @Alekhen.

**Closed by goyney** 2018-11-20 16:35 UTC
Labels: Contribution :heavy_check_mark:, Icon Request :pencil2:
