### ISSUE TITLE
Electric motor

### ISSUE THREAD

**Issue by chma31** [Templarian/MaterialDesign#6385] opened 2021-12-28 14:52 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Hello,

Would be great when an electric motor icon is added to the MDI library. I saw a similar request aged about 2 years but without follow-up.
I would use to show whether some of my electric motors are being powered or not (like when opening a garage door) or for a lifter.

Regards.

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/96373325/147578455-a38e4543-c6be-457e-8581-148643553790.png)

**Comment by chma31** [comment] 2021-12-28 14:53
I forgot to mention I 'll use it under Home Assistant.

**Comment by goyney** [comment] 2021-12-28 15:22
Duplicate of #4457.

**Closed by goyney** 2021-12-28 15:22 UTC
Labels: Icon Request
