### ISSUE TITLE
Chandelier icon

### ISSUE THREAD

**Issue by rainlance** [Templarian/MaterialDesign#2954] opened 2018-03-24 11:36 UTC
How about a Chandelier icon?

**Comment by Templarian** [comment] 2018-03-24 15:54
I'm going to close this issue as a duplicate of #1712 since we have designs created.

Could use more feedback in that open issue if these designs would work for you or if variants are needed. We know lighting is a large use of Home Automation.

**Closed by Templarian** 2018-03-24 15:54 UTC

**Comment by rainlance** [comment] 2018-08-09 19:49
Sorry for the late answer: The ceiling-light and floor-lamp are perfect. Thank you !
