### ISSUE TITLE
icon for Car Trunk and Engine Hood

### ISSUE THREAD

**Issue by BenGamingGER** [Templarian/MaterialDesign#6531] opened 2022-03-29 14:41 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'm currently working with friends on a GTA roleplay server. We use many of your icons. We haven't seen these before.

### Give us an example of what this icon might look like.

![95139](https://user-images.githubusercontent.com/52014489/160637297-682c133c-720a-45d6-b483-f3b4d60ed786.png)
![png-transparent-car-hood-vehicle-dashboard-computer-icons-car-angle-text-car-thumbnail](https://user-images.githubusercontent.com/52014489/160637318-ffc21fa6-317f-4e2f-b471-d1db526347a1.png)

**Comment by goyney** [comment] 2022-03-29 14:44
Duplicate of #5170.

**Closed by goyney** 2022-03-29 14:44 UTC
Labels: Icon Request
