### ISSUE TITLE
icons to holidays

### ISSUE THREAD

**Issue by lucas-marciano** [Templarian/MaterialDesign#1181] opened 2016-04-18 12:28 UTC
For exemple:
Christmas, birthdays, 4th july, Easter etc.

**Comment by Templarian** [comment] 2016-04-18 17:00
https://materialdesignicons.com/icon/candycane
https://materialdesignicons.com/icon/ornament
https://materialdesignicons.com/icon/ornament-variant
There are 3 different cake icons for birthdays.

4th of july is probably a duplicate of #1174.

Easter... Rabbit or a Egg maybe.

**Comment by timothyjc** [comment] 2016-05-05 09:30
Easter could also be a cross, though I think a rabbit might work well too.
I would like a Halloween pumpkin if possible too.

**Comment by PeterShaggyNoble** [comment] 2018-02-28 17:33
- Rabbit has its own issue in #2614 and cross is included in #1074
- Pumpkin is covered in #729
- [`pine-tree`](https://materialdesignicons.com/icon/pine-tree) should cover Christmas tree

Closing here. If you're still in need of icons to represent any other times of the year, please open a new issue for each one, taking care to search the existing issues first.

**Closed by PeterShaggyNoble** 2018-02-28 17:33 UTC
Labels: Icon Request :pencil2:
