### ISSUE TITLE
license-plate

### ISSUE THREAD

**Issue by Chej0** [Templarian/MaterialDesign#4973] opened 2020-03-13 18:43 UTC
need a icon that represents the license plate of a car ... something like this
![images](https://user-images.githubusercontent.com/26882572/76650414-375a8d80-6528-11ea-916f-0537639b3ea7.png)

**Comment by Templarian** [comment] 2020-03-13 18:45
Duplicate of #712

**Closed by Templarian** 2020-03-13 18:45 UTC
