### ISSUE TITLE
Tire

### ISSUE THREAD

**Issue by seanmitchell90** [Templarian/MaterialDesign#4135] opened 2019-05-06 12:54 UTC
Here's a suggestion: 
![tire](https://user-images.githubusercontent.com/50327294/57226222-2110a680-6fd4-11e9-9b53-1d489fc7bfe3.png)

**Comment by PeterShaggyNoble** [comment] 2019-05-06 12:58
Duplicate of #1308

**Closed by PeterShaggyNoble** 2019-05-06 12:58 UTC
