### ISSUE TITLE
Customs icon

### ISSUE THREAD

**Issue by Doeke** [Templarian/MaterialDesign#2770] opened 2018-01-24 13:29 UTC
I don't think there's anything like that yet, here's an example:

![image](https://user-images.githubusercontent.com/240530/35334493-e5753c0c-0112-11e8-9a67-65328875c704.png)

**Comment by MrGrigri** [comment] 2018-01-24 14:54
Would [passport](https://materialdesignicons.com/icon/passport) work?

![passport](https://materialdesignicons.com/icon/passport)

**Comment by Doeke** [comment] 2018-01-25 14:58
My use case is for customs clearance of cargo, I don't think passport fits.

Alternatively a stamp icon might work for my use case, something like this but filled

![image](https://user-images.githubusercontent.com/240530/35394475-28338bfe-01e8-11e8-8632-addbf49bd848.png)

**Comment by MrGrigri** [comment] 2018-01-26 15:11
The stamp request would be a duplicate of #621.

**Comment by PeterShaggyNoble** [comment] 2018-04-12 15:50
Closing as a dupe of #621, which now includes a contribution.

**Closed by PeterShaggyNoble** 2018-04-12 15:50 UTC
Labels: Icon Request :pencil2:, Needs More Information :information_source:
