### ISSUE TITLE
Window Shutter 50 %

### ISSUE THREAD

**Issue by wanfr** [Templarian/MaterialDesign#7178] opened 2023-07-28 07:43 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

window shutter partially open

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/62714660/e5392bdc-fea8-4f1b-a3df-bd0f8df8d6eb)

### Upload the icon source.

[window-shutter-50%.svg.zip](https://github.com/Templarian/MaterialDesign/files/12191375/window-shutter-50.svg.zip)

**Comment by mririgoyen** [comment] 2023-07-30 18:11
Please search (as you stated you had).

Duplicate of https://github.com/Templarian/MaterialDesign/issues/5733, https://github.com/Templarian/MaterialDesign/issues/5872, https://github.com/Templarian/MaterialDesign/issues/6277, https://github.com/Templarian/MaterialDesign/issues/6740, https://github.com/Templarian/MaterialDesign/issues/6754, https://github.com/Templarian/MaterialDesign/issues/7129,
https://github.com/Templarian/MaterialDesign/issues/7152.

**Closed by mririgoyen** 2023-07-30 18:11 UTC
Labels: Icon Request, Contribution
