### ISSUE TITLE
Denied

### ISSUE THREAD

**Issue by vicianm** [Templarian/MaterialDesign#3857] opened 2019-01-25 15:45 UTC
https://www.iconfinder.com/icons/114648/delete_denied_icon

![denied](https://user-images.githubusercontent.com/156647/51756114-94934580-20c0-11e9-8107-062903bf41fb.png)

**Comment by Templarian** [comment] 2019-01-25 16:09
Duplicate of `cancel`. Added an alias.

**Closed by Templarian** 2019-01-25 16:09 UTC
Labels: Alias :arrows_clockwise:, Duplicate/Already Included :bookmark_tabs:
