### ISSUE TITLE
student

### ISSUE THREAD

**Issue by Arafat1243** [Templarian/MaterialDesign#5444] opened 2020-08-23 17:01 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment] 2020-08-23 17:53
@Arafat1243 The template isn't options. Please fill it in. 👍

**Comment by Arafat1243** [comment] 2020-08-24 09:16
[https://png.pngtree.com/png-vector/20190118/ourlarge/pngtree-vector-male-student-icon-png-image_326762.jpg](url)

**Comment by viktor-yakubiv** [comment] 2020-08-27 08:59
I feel like this is out of scope of the material icons. At least, Google Material feel like gender and professionally neutral, the library contains only 'user'. If we add a 'student' user, we may end up with redrawing whole unicode professionals range.

**Comment by allisonvarnell** [comment] 2020-08-27 09:36
Perhaps instead of “student” you could call it researcher”?

> I feel like this is out of scope of the material icons. At least, Google Material feel like gender and professionally neutral, the library contains only 'user'. If we add a 'student' user, we may end up with redrawing whole unicode professionals range.

**Comment by goyney** [comment] 2020-09-09 02:35
This is a duplicate of #5401.

**Closed by goyney** 2020-09-09 02:35 UTC
Labels: Icon Request, Needs More Info
