### ISSUE TITLE
boiler icon

### ISSUE THREAD

**Issue by gyengus** [Templarian/MaterialDesign#2958] opened 2018-03-26 14:20 UTC
I would like an icon for boiler.
Some example: https://www.google.hu/search?q=boiler+icon&rlz=1C5CHFA_enHU695HU698&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwj8x_Ctl4raAhXlF5oKHdoRAr4QsAQIJg&biw=1679&bih=865

**Comment by PeterShaggyNoble** [comment] 2018-03-26 14:21
This is a duplicate of #2900.

**Comment by GreenTurtwig** [comment] 2018-03-26 14:21
Not to be rude, but did you search (or even look at them first page of issues). :-)

**Closed by PeterShaggyNoble** 2018-03-26 14:21 UTC
