### ISSUE TITLE
Fuel level

### ISSUE THREAD

**Issue by saumilsdk** [Templarian/MaterialDesign#2759] opened 2018-01-22 09:02 UTC
Need icons like fuel low/moderate/good icons to display fuel level in a car

**Comment by MrGrigri** [comment] 2018-01-22 18:50
How about these? I'm not sure on the names though; maybe `fuel-high`, `fuel-medium`, and `fuel-low`. I know that this is the `barrel` icon, so maybe `barrel-*`. Thoughts?


![image](https://user-images.githubusercontent.com/4528551/35238209-102011f2-ff6a-11e7-9b21-7ef5cc48ee16.png) ![image](https://user-images.githubusercontent.com/4528551/35238175-fc6d5958-ff69-11e7-927d-143fdc5d8947.png) ![image](https://user-images.githubusercontent.com/4528551/35238152-e9c49fd2-ff69-11e7-9d27-59e6271b127a.png)

[fuel-level.zip](https://github.com/Templarian/MaterialDesign/files/1653200/fuel-level.zip)

**Comment by PeterShaggyNoble** [comment] 2018-01-24 16:09
Didn't we have a request recently for high/medium/low variants of the `gauge` icon? Would this not be a dupe of that?

**Comment by MrGrigri** [comment] 2018-01-24 16:13
I do remember that...but I do not remember where.

**Comment by PeterShaggyNoble** [comment] 2018-01-24 16:20
Ah, wait, no; it was #2683 requesting variants of the *`speedometer`* icon.

**Comment by MrGrigri** [comment] 2018-01-26 20:27
Would #2774 work?

**Comment by Templarian** [comment] 2018-01-28 07:07
Closing this out in-favor the Gauge icons which will be in the next release.

Thanks @MrGrigri, but it's going to be too niche at the moment.

**Closed by Templarian** 2018-01-28 07:07 UTC
Labels: Icon Request

**Comment by saumilsdk** [comment] 2018-01-28 07:11
Thank you so much for everyone's prompt reply.
