### ISSUE TITLE
coins

### ISSUE THREAD

**Issue by fabianoshark** [Templarian/MaterialDesign#6335] opened 2021-11-20 22:19 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This icon would be used to illustrate the cost of an item.

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/45877739/142742436-da4e4322-25e3-4ee1-b840-6826138a4569.png)

**Comment by goyney** [comment] 2021-11-20 23:56
Duplicate of #2619.

**Closed** 2021-11-20 23:57 UTC
Labels: Icon Request, Duplicate
