### ISSUE TITLE
light-recessed-multiple

### ISSUE THREAD

**Issue by schmittyd** [Templarian/MaterialDesign#7426] opened 2024-04-19 04:27 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Home Assistant multiple recessed lights group

### Give us an example of what this icon might look like.

![light-recessed-multiple-2](https://github.com/Templarian/MaterialDesign/assets/12869594/5090da48-e0a7-4ff3-8b41-090c39ef3e5a)
![light-recessed-multiple-3](https://github.com/Templarian/MaterialDesign/assets/12869594/0e7ca577-3813-48ca-9ee9-87c6338cfdb6)
![light-recessed-multiple-4](https://github.com/Templarian/MaterialDesign/assets/12869594/500764ce-e8af-4861-b14b-d1deab29c1e4)

**Comment by mririgoyen** [comment] 2024-04-23 14:36
Dupe of #6841.

**Closed by mririgoyen** 2024-04-23 14:36 UTC
Labels: Icon Request
