### ISSUE TITLE
Do we support ligatures?

### ISSUE THREAD

**Issue by blendsdk** [Templarian/MaterialDesign#3312] opened 2018-07-09 12:50 UTC
Hi,

The icon font files originally provided by Google supported a pretty nice feature called "ligatures"
Do we support this? 

At the moment the CSS file is very large and will get larger as new icons are added. With ligatures we won't be needing a separate css selector for each icon.

Any thoughts?

**Comment by goyney** [comment] 2018-07-09 12:51
Duplicate of https://github.com/Templarian/MaterialDesign/issues/1013.

**Closed by goyney** 2018-07-09 12:51 UTC

**Comment by PeterShaggyNoble** [comment] 2018-07-09 16:08
Even with ligatures we'd need to maintain the CSS files who those who wouldn't want to use ligataures. And the ligatures would only increase the size of the font files too.

If the physical size of the files is a concern for you then you should look into using SVG instead of the webfont, which is something we're actively encouraging everyone to do.

**Comment by blendsdk** [comment] 2018-07-09 16:13
Thank you. I was just looking into this option after my failed attempt to see if 'liga' was going to work . Could you please help me understand why SVG is encouraged instead of webfonts here?

**Comment by Templarian** [comment] 2018-07-09 16:25
@blendsdk Every month and a half we add roughly 100+ icons. The font will never be an ideal way to use the icons as we reach over 3k icons. We'll be adding TypeScript and a ES6 module shortly for more 3rd party integrations.

TBH, we're never going to add ligature support, it's just not a priority unfortunately.

**Comment by blendsdk** [comment] 2018-07-09 18:24
@Templarian thank you. It is clear now.
