### ISSUE TITLE
unshare / share-off

### ISSUE THREAD

**Issue by hargagan** [Templarian/MaterialDesign#2748] opened 2018-01-17 00:11 UTC
Sharing a file or folder has an icon available but there is no icon available for unshare. Requesting the team to provide one for un-sharing the file or folder.

**Comment by MrGrigri** [comment] 2018-01-17 00:28
What do you suggest?

**Comment by GreenTurtwig** [comment] 2018-01-17 00:30
Duplicate of https://github.com/Templarian/MaterialDesign/issues/1325

**Closed by GreenTurtwig** 2018-01-17 00:30 UTC
