### ISSUE TITLE
 Sql Sub query

### ISSUE THREAD

**Issue by YousefGhafouri** [Templarian/MaterialDesign#5104] opened 2020-04-22 17:23 UTC
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue.

**Comment by goyney** [comment] 2020-04-23 00:05
Duplicate of #5103.

**Closed by goyney** 2020-04-23 00:05 UTC
Labels: Icon Request

**Comment by YousefGhafouri** [comment] 2020-04-23 05:27
Hello
I'm sorry,I didn't write an explanation for them, because it's a little difficult for them to explain!
Sql Query refers to the commands used to interact with the Microsoft SqlServer database.
These commands can include other commands called Sql SubQuery.
Example:
SELECT Id, 
	   Name,
	   Family,
	   (SELECT Address 
    FROM PersonnelAddress
    WHERE dbo.PersonnelAddress.PersonnelId = Personnel
   ) AS Address
FROM dbo.Personnel

These commands are called Sql Suery and the part that identifies the address is called Sql SubQuery.
