### ISSUE TITLE
Unshare

### ISSUE THREAD

**Issue by aqume** [Templarian/MaterialDesign#4232] opened 2019-07-07 09:41 UTC
I have:

- [ ] Searched all issues to make sure there isn't a request for this icon.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment] 2019-07-07 18:32
Duplicate of #1395. Please search before posting.

**Closed by goyney** 2019-07-07 18:32 UTC
Labels: Icon Request
