### ISSUE TITLE
businessman

### ISSUE THREAD

**Issue by Tarilonte** [Templarian/MaterialDesign#3077] opened 2018-04-18 01:03 UTC
businessman icon
[businessman.zip](https://github.com/Templarian/MaterialDesign/files/1922107/businessman.zip)

![image](https://user-images.githubusercontent.com/29761068/38906132-19baab1e-428b-11e8-95b1-e44218038478.png)

**Comment by GreenTurtwig** [comment] 2018-04-18 10:01
Duplicate of https://github.com/Templarian/MaterialDesign/issues/2341
Please post your contribution over there. :cat2:

**Closed by GreenTurtwig** 2018-04-18 10:01 UTC
Labels: Duplicate/Already Included :bookmark_tabs:
