### ISSUE TITLE
ceiling hood

### ISSUE THREAD

**Issue by Schrikt** [Templarian/MaterialDesign#6571] opened 2022-04-28 18:00 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Represent my hood that is buildin my ceiling in my domotica software (home assistant).

### Give us an example of what this icon might look like.

It should represent this kind of hood:
https://www.siemens-home.bsh-group.com/uk/productlist/cooking-and-baking/ventilation/island-chimney-and-ceiling-hoods/ceiling-hoods/LR96CAQ50B#/Tabs=section-highlights/Togglebox=accessories/Togglebox=combinables/Togglebox=manuals/Togglebox=accessoriesOthers/

it could look something like this:
![image](https://user-images.githubusercontent.com/60716169/165817453-65549b3e-84ed-4a6f-b501-0c6fcfce091f.gif)

**Comment by goyney** [comment] 2022-05-02 03:41
This is going to have the same problem as https://github.com/Templarian/MaterialDesign/issues/1826. However, this is much more niche and probably won't get a special exception. It took 4 years for us to relent and break Material guidelines to add the can light. I really don't think this makes the cut.

**Comment by Schrikt** [comment] 2022-05-02 05:15
The problem is also that there is no generic alternative for a hood. So even if this does not make the cut (although and go not completely see the comparison with the can) it would be nice to have a hood icon at all.

**Comment by goyney** [comment] 2022-05-04 00:24
The `fan` icons seem like they would be the generic icon for this, no?

**Comment by Mariusthvdb** [comment] 2022-05-14 15:20
while contemplating the Hood please see https://github.com/Templarian/MaterialDesign/issues/5738 too?

**Comment by goyney** [comment] 2022-07-08 21:14
I think that #5738 is a much more reasonable way to handle this use case. It removes the perspective problem completely. I'm closing this one as a duplicate of that issue and we'll handle it there.

**Closed by goyney** 2022-07-08 21:14 UTC
Labels: Icon Request, Consider Closing

**Comment by snetekombinerke** [comment] 2025-01-23 20:15
Hi,
I also have a need for this icon. Any progress ? 
Can this hue icon be added to mdi ? 
hue:cooker-hood-trapezoid
hue:cooker-hood-curve

Best regards
