### ISSUE TITLE
Flood Light

### ISSUE THREAD

**Issue by tbtgspence** [Templarian/MaterialDesign#5430] opened 2020-08-17 05:11 UTC
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For use in Home Assistant to indicate a flood light that would typically be installed on the exterior of a home.

## Examples

Something like this, turned into an icon.

![image](https://user-images.githubusercontent.com/34466356/90359291-5a282b00-e00d-11ea-91f2-2cbfd1fd0fb5.png)

**Comment by goyney** [comment] 2020-08-17 12:04
Possible duplicate of #5036.

**Comment by tbtgspence** [comment] 2020-08-18 05:51
Definitely not the same kind of light.  The picture I showed clearly indicates a very common household light installed outside many garages, corners of houses, etc.  The light shown in 5036 looks more like a stage light or something like that.  It would not indicate the same thing at all in a home automation situation.

**Comment by tbtgspence** [comment] 2020-08-18 05:56
If you just Google "outdoor flood light", you'll see that the majority of shopping results are similar to what I've asked for.  There are a few that would be similar to #5036, so I'm not invalidating his request, but you can see from the majority of results that they aren't the same.

![image](https://user-images.githubusercontent.com/34466356/90475699-d0e02980-e0dc-11ea-89e3-efe04a4e9475.png)

**Comment by goyney** [comment] 2021-08-30 21:37
Duplicate of #5036.

**Closed by goyney** 2021-08-30 21:37 UTC
Labels: Icon Request
