### ISSUE TITLE
Flags for all countries.

### ISSUE THREAD

**Issue by davisharry** [Templarian/MaterialDesign#7188] opened 2023-07-31 03:21 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To show all the countries, and I need the flag icon.

### Give us an example of what this icon might look like.

Just the flag for all countries

**Comment by Templarian** [comment] 2023-07-31 03:56
@davisharry How would that work for an icon pack that is monotone?

Would most likely be too detailed for this set.

**Comment by MrGrigri** [comment] 2023-07-31 14:46
Agreed, this would be impossible for a monochrome icon pack. [Here is a reference](https://www.worldometers.info/geography/flags-of-the-world/) for the countries.

**Comment by mririgoyen** [comment] 2023-08-01 17:53
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/4906.

**Closed by mririgoyen** 2023-08-01 17:53 UTC
Labels: Icon Request, Needs More Info
