### ISSUE TITLE
Hairdresser Icons, beauty Salon icons

### ISSUE THREAD

**Issue by mauro16** [Templarian/MaterialDesign#5166] opened 2020-05-18 23:54 UTC
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment] 2020-05-19 01:43
This is a duplicate of #2121, which was closed because of no solid examples or specific icon requests.

We have `hair-dryer(-outline)`. We also have an open issue for a hairbrush (#3752).

I'm going to close this one as well. If you have ideas for specific icons to support your use case, please open a new request, one per icon, and fill out our template, indicating potential usage and examples of what it might look like.

**Closed by goyney** 2020-05-19 01:43 UTC
Labels: Icon Request
