### ISSUE TITLE
Weather Icon set

### ISSUE THREAD

**Issue by adbstyle** [Templarian/MaterialDesign#1318] opened 2016-06-27 09:21 UTC
hi folks
here's my weather icon set. the design elements are derived from google icons as well as the icons from Austin Andrews.
you may publish and improve them.

cheers adrian bader

[weather icon set.zip](https://github.com/Templarian/MaterialDesign/files/334464/weather.icon.set.zip)

**Comment by Templarian** [comment] 2016-07-14 01:35
[![weather-lightning-rainy](https://materialdesignicons.com/icon/weather-lightning-rainy)](https://materialdesignicons.com/icon/weather-lightning-rainy) [![weather-snowy-rainy](https://materialdesignicons.com/icon/weather-snowy-rainy)](https://materialdesignicons.com/icon/weather-snowy-rainy)

Two so far have been incorporated (modified heavily, but included). Looking at getting some of these others in.

**Comment by goyney** [comment] 2018-11-25 05:06
This is a duplicate of #541, but they both have Contributions. We'll need to consolidate the two issues and decided what path to take with the icons provided.

**Comment by goyney** [comment] 2018-11-26 05:03
Now that we've inventoried this issue, we've created and combined it with another master weather-related issue since there were two very large issues regarding weather icons. We'll track the work of the addition of the additional 5 icons from this issue there. Please follow issue #3736 to keep up-to-date with the progress. Thank you for your contribution.

**Closed by goyney** 2018-11-26 05:03 UTC
Labels: Contribution :heavy_check_mark:, Icon Request :pencil2:
