### ISSUE TITLE
Earlybird icon

### ISSUE THREAD

**Issue by grijal** [Templarian/MaterialDesign#1498] opened 2016-09-09 12:42 UTC
Something like this
![](https://resources.kamernet.nl/Content/images/redesign/common/eb_white.png) (is transparent)

or

![](http://kvsocial.com/bonus/wp-content/uploads/2015/07/114672-magic-marker-icon-animals-animal-bird1.png)

**Comment by PeterShaggyNoble** [comment] 2018-03-14 16:04
This is a duplicate of #895

**Closed by PeterShaggyNoble** 2018-03-14 16:04 UTC
