### ISSUE TITLE
paperplane-circle-outline

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6652] opened 2022-06-15 09:46 UTC
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

We find the only 'send' icon in the current MDI library lacking some recognizability, therefor we created this send-variant, called 'paperplane'. We created a stand alone version, a solid circle version and this outline circle version.

### Share a preview of your contribution.

![preview-paperplane-circle-outline](https://user-images.githubusercontent.com/107536590/173797881-994b3941-aeea-461b-b556-025ed1aad58f.png)

### Upload the icon source.

[paperplane-circle-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/8908052/paperplane-circle-outline.svg.zip)

**Comment by goyney** [comment] 2022-06-15 10:21
Duplicate of #6650.

**Closed by goyney** 2022-06-15 10:21 UTC
Labels: Icon Request, Contribution
