### ISSUE TITLE
Steel Beam / Steel I Beam

### ISSUE THREAD

**Issue by Dimtrivh** [Templarian/MaterialDesign#4641] opened 2019-12-02 09:41 UTC
We are no longer accepting brand icons. Learn more: http://dev.materialdesignicons.com/roadmap/brand-icons
-->

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Used for showing steel

## Examples

![195_stainless-steel-metal-h-profile-512](https://user-images.githubusercontent.com/39410964/69948642-4a54cf00-14f0-11ea-8c7a-6ffe6533f7df.png)

**Comment by goyney** [comment] 2019-12-02 14:04
Duplicate of #4188. Please don't double post.

**Closed by goyney** 2019-12-02 14:04 UTC
Labels: Icon Request
