### ISSUE TITLE
shutter middle

### ISSUE THREAD

**Issue by mla4ger** [Templarian/MaterialDesign#5872] opened 2021-02-28 19:44 UTC
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
You have a closed shutter and an open shutter, but there is noch shutter between open und closed. 

## Examples

You can use the window-shutter-alert but without exclamation mark

**Comment by GoTTi74** [comment] 2021-02-28 23:56
+1 Just wanted to add this as well.
Since the "window-shutter" has 4 bars, it would be neat to have icons with 1, 2, 3 & 4 bars.

**Comment by goyney** [comment] 2021-03-01 02:01
Duplicate of #5733.

**Closed by goyney** 2021-03-01 02:01 UTC
Labels: Icon Request
