### ISSUE TITLE
"image" and "image-broken-variant" missing from icon svg font

### ISSUE THREAD

**Issue by code-mc** [Templarian/MaterialDesign#856] opened 2015-11-21 13:43 UTC
These two (and potentially more) are missing from the font but are listed on the website. I only checked the SVG source file but I assume they are all auto generated.

If these are on the "to be added list" please close this issue. But I assumed you looked over them as they are both google-official.

**Comment by CoDEmanX** [comment] 2015-11-21 15:06
[image](https://materialdesignicons.com/icon/image) is available in the [SVG font](https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont/master/fonts/materialdesignicons-webfont.svg), but it has a different name: `file-image-box`

The following appear to be missing, but I think that's because there has been some renaming:
- book-open-variant
- cake-layered
- google-wallet

**Comment by code-mc** [comment] 2015-11-21 15:18
Ok, thank you!

**Comment by CoDEmanX** [comment] 2015-11-21 16:28
I can confirm that,
- google-wallet > wallet
- cake-layered > cake-variant
- book-open-variant > book-open

The names on the left are the new names. The names on right are used for other icons on the page already, but this is not yet reflected in the fonts because of the pending release.

So the issues with all 4 "missing" icons should resolve with the next release.

**Comment by Templarian** [comment] 2015-11-22 08:37
I'm going to close this issue out.

**Closed by Templarian** 2015-11-22 08:37 UTC
Labels: Question
