### ISSUE TITLE
silverware upright (suggesting -on)

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#3204] opened 2018-05-26 14:50 UTC
please consider adding a mdi:silverware version with the fork and knife (or spoon) in parallel upright position .
it would accommodate an -off and -on situation: crossed for off, parallel for on ;-)
would be cool indeed if possible ,
thanks
Marius

**Comment by GreenTurtwig** [comment] 2018-05-28 11:45
This is `restaurant` in the stock set, should probably get it added as a variant to `silverware-variant`, although that's already a variant itself...
Renaming `silverware-variant` to `knife-and-fork` and adding it as `knife-and-fork-variant` could be a solution.

**Comment by hvbhome** [comment] 2018-06-06 07:47
would be appreciated indeed.thx

**Comment by PeterShaggyNoble** [comment] 2018-07-12 09:17
Duplicate of #1802

**Closed by PeterShaggyNoble** 2018-07-12 09:17 UTC
Labels: Icon Request :pencil2:, Stock Google Icon :squirrel:
