### ISSUE TITLE
Icon for Dehumidifier

### ISSUE THREAD

**Issue by Sawadee2u** [Templarian/MaterialDesign#6140] opened 2021-08-20 16:50 UTC
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Dehumidifier related data ( power etc) in Home Automation. The same MDI icon for humidifier could be used simply by changing the + to a -

### Give us an example of it's usage.

Used for power monitoring in Home Assistant

The same MDI icon for humidifier could be used simply by changing the + to a -

**Comment by goyney** [comment] 2021-08-20 16:53
Duplicate of #5956. Please search in the future.

**Closed by goyney** 2021-08-20 16:53 UTC
Labels: Icon Request
