### ISSUE TITLE
Google Fit Scales Icons

### ISSUE THREAD

**Issue by MaximilianKeppeler** [Templarian/MaterialDesign#1788] opened 2017-01-21 19:25 UTC

**Comment by Croutonix** [comment] 2017-01-22 02:52
Like this?
![image](https://cloud.githubusercontent.com/assets/18645219/22179509/f0d84762-e023-11e6-9d87-6dcd30c27f55.png)

**Comment by MaximilianKeppeler** [comment] 2017-01-22 10:41
I meant a "recording weight" - icon. Sorry. 

![screenshot_20170122-083107](https://cloud.githubusercontent.com/assets/15075376/22181919/a5636716-e097-11e6-88ef-52ab9a6655ac.png)

**Comment by PeterShaggyNoble** [comment] 2017-01-23 13:46
That's a scale, not a weight. A few options you could use:

![](https://materialdesignicons.com/icon/scale-bathroom) ![](https://materialdesignicons.com/icon/speedometer) ![](https://materialdesignicons.com/icon/gauge) ![](https://materialdesignicons.com/icon/scale) ![](https://materialdesignicons.com/icon/scale-balance)

**Comment by MaximilianKeppeler** [comment] 2017-01-23 19:38
Oh ok, then I searched after the wrong word. Thanks. (Thought I wish to have the Google Fit weight scale, since it does fit better.)

**Comment by GreenTurtwig** [comment] 2018-04-18 14:50
[![](https://user-images.githubusercontent.com/15905797/38939594-2fd9912c-4320-11e8-9afa-ea38aa209291.png)](https://github.com/Templarian/MaterialDesign/files/1924559/weight-fitness.zip)

**Comment by goyney** [comment] 2018-11-25 03:49
This is a duplicate of #2547.

**Closed by goyney** 2018-11-25 03:49 UTC
Labels: Icon Request :pencil2:, Stock Google Icon :squirrel:
