### ISSUE TITLE
excel icon

### ISSUE THREAD

**Issue by davidsalomon14** [Templarian/MaterialDesign#601] opened 2015-08-12 11:44 UTC
I WILL HAPPY WITH EXCEL ICON.
I NEED ICON TO IMPORT DATA TO EXCEL FILE.

THANKS
DAVID

**Comment by CoDEmanX** [comment] 2015-08-12 11:48
https://materialdesignicons.com/icon/file-excel-box
https://materialdesignicons.com/icon/file-excel
Duplicate of #368

PS: Captain Caps and his SHIFT crew is not welcome here.

**Closed by CoDEmanX** 2015-08-12 11:48 UTC

**Comment by Templarian** [comment] 2015-08-12 14:38
Ha. Yea what @CoDEmanX said.

Due to the size constraints app style icons are not included. So the file variants are the best choice.
